### ISSUE TITLE
Port to more languages

### ISSUE THREAD

**Issue by mlissner** [matomo-org/device-detector#5257]
It looks like this has all the ingredients to be portable to other languages. Probably the top ones to do would be Python, Ruby and JavaScript. 

From a quick glance it looks like the trick would be:
- Write a parser in language X
- Tweak the tests to use the parser in language X

Looks pretty darned easy, actually. Would be a fantastic contribution that'd make this **the** parser library, regardless of your platform.

**Comment by sanchezzzhak** [comment]
base port piwik nodejs
https://github.com/sanchezzzhak/node-device-detector
you can take full project if you wish

**Comment by miron341** [comment]
;/

**Comment by totpero** [comment]
Hi,
I'm also trying to write .NET C# version of  DeviceDetector. I will share my beta version on github.

**Comment by sgiehl** [comment]
I'll add a list of known ports to the README. If anyone finds a new one, feel free to create a PR to extend the list

**Comment by mngsk** [comment]
Hi, I just published a Java version at https://github.com/mngsk/device-detector.
It's not quite ready for production use, as it is lacking unit tests, but I'll get into it soon.

**Comment by Findus23** [comment]
@mngsk Thanks, I added it to https://devicedetector.lw1.at/ports

If you want to, you can make a PR to add it to the README.
