### ISSUE TITLE
Tweak http://devicedetector.net/index.php to supply json

### ISSUE THREAD

**Issue by rlf** [matomo-org/device-detector#5371]
Hi.

Great project!

Could you tweak the index.php above, so it can serve json as well?

Or do you fear the added traffic that might generate?

**Comment by sgiehl** [comment]
That should more be used as a demo, not a service.
If you need the detection why don't you use the device detector package itself?

**Comment by rlf** [comment]
Well, because that would require me to setup a php enabled web-service, and I'm not on that architecture currently.

Also, updating to the latest definitions would not happen automatically, but would require a "reinstall", pull or what-ever from the device-detector project.

And I assume scraping the demo-page html isn't something you would incourage :D

**Comment by sgiehl** [comment]
For updating composer could be used. On which server architecture do you need the detection?

The server running the demo is not meant to be used as an API, so guess it might just be to slow to use it as that.
