### ISSUE TITLE
Win10-IE11 on desktop is recognized as tablet

### ISSUE THREAD

**Issue by edibusl** [matomo-org/device-detector#5375]
The device type of Win10, IE11 (desktop) is recognized as tablet instead of desktop.
User agent: 
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko

**Comment by sgiehl** [comment]
Your device has a touch display, correct?
We currently assume that all devices running windows 10 having touch enabled are tablets as most windows 10 touch devices are tablets

**Comment by edibusl** [comment]
It's HP Spectre X360 - it indeed has a touch display.
But it's not a tablet. It's a regular laptop - so why categorizing it as a tablet?

**Comment by sgiehl** [comment]
The User-Agent only gives information that it is a Windows 10 and that the device has touch enabled.
As most windows tablets and desktop/laptop pcs are not sending device information on Windows 10 it is only possible to assume what device type it could be.

I decided to assume that all those devices are tablets as the number of desktop/laptop pcs having touch enabled is approximately smaller than tablet devices having touch enabled.

**Comment by edibusl** [comment]
Got it.
User agents of other OSs/browsers do pass more specific information about the device?
Or are there assumption in other types of OSs as well?
Thanks.

**Comment by sgiehl** [comment]
most other non desktop os do pass information about the device. These kind of assumption is only done for windows (touch) devices

**Comment by edibusl** [comment]
Hi,
Sorry for bothering, but now also Win8-IE10 combination is detected as "Tablet" instead of "Desktop":
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0; Touch)

Is this possible to recognize the right type for Win8 maybe?
There are lots of touch laptops nowadays and many/some of them are detected as tablets.

Thanks

**Comment by sgiehl** [comment]
Same for Windows 8, and maybe other versions of windows that provide the `Touch` fragment for devices with touch display.

There are exactly two options for all those devices:
- detect all as desktop (which will include all tablet false/positives)
- detect all as tablets (which will include all desktop false/positives)

I currently don't have any stats if there are more tables or more desktop devices with touch running windows.

**Comment by edibusl** [comment]
Thanks, I understand the problem.
DeviceAtlas detect those 2 user agents as desktops, not tablets. Is this because they manually go over all user agents? (I understand that it's a big effort to go over all existing user devices)
Thanks.

**Comment by leeoniya** [comment]
@sgiehl

I just ran into this during testing.

To make matters worse, Win10 x64 IE11 reports Touch when there is no actual touch capability on this device (Lenovo T440s). There's also a bug report here: https://answers.microsoft.com/en-us/ie/forum/ie11-iewindows_10/useragent-string-ua-string-returned-from-ie11-on/ec0c2a52-6ca6-4333-8633-409de9759f58 

`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko`

It might be worth re-opening this issue to serve as visible PSA even if there's no obvious solution.

**Comment by mohammadbhaji** [comment]
Hi Team,
Do we have any latest update?

**Comment by sgiehl** [comment]
I'm not sure how we should handle that best. We could remove move the assumption that all windows devices having the `Touch` fragment are tablets. That would fix the detection for incorrectly detected laptops. But all windows tablets would be detected as desktops then, as well. I'm not sure which assumption is more falsely. Any opinions?

**Comment by mohammadbhaji** [comment]
Probably we should understand how Google Chrome skipping the Touch.

Regards,
Mohammadrafi Bhajisahib,
Certified Scrum Master,
Aspire Systems India Pvt Ltd,
Mobile: +91 9840952716

[cid:image001.png@01D29206.BCA932F0]

**Comment by sgiehl** [comment]
Google Chrome shouldn't add the `Touch` fragment at all. And even if, device detector would ignore it. It is only relevant for Internet Explorer on Windows devices.

**Comment by sanchezzzhak** [comment]
since IE has sunk into oblivion, I don't think it's necessary to solve this issue.
