### ISSUE TITLE
Iceweasel should be tracked as Firefox

### ISSUE THREAD

**Issue by nidico** [matomo-org/device-detector#5389]
(Moved from piwik/piwik#9336 as suggested)

In piwik/piwik#1167 it was already concluded that "GNU/Debian rebranded firefox should not appear in different segments". I fully agree with this - the browser split happened due to smaller licensing issues, but is irrelevant from an analytics point of view in my opinion.

Nevertheless, Piwik currently tracks firefox and iceweasel separately.

I'd suggest to treat iceweasel treated as firefox again.

Related note: Chrome and Chromium are currently also tracked separately. I don't have a clear opinion on that one though, they indeed feel like more different browsers than firefox and iceweasel do.

**Comment by sgiehl** [comment]
I don't think we should change that, as it means a loss of information.
Even if the information is small it might be useful or required for others using device detector.

For changing the tracking behavior in Piwik maybe you could create a plugin that changes the detected browser before the tracking data is saved.

**Comment by nidico** [comment]
I've [asked the Iceweasel maintainers](https://lists.alioth.debian.org/pipermail/pkg-mozilla-maintainers/2015-December/027009.html) about their opinion on the issue.

**Comment by terryelmo650** [comment]
The issue is my battery not charing
