### ISSUE TITLE
Cache question: ApcuCache vs PhpFileCache

### ISSUE THREAD

**Issue by denis-n** [matomo-org/device-detector#5572]
Hi,

I'm new to php caching. I've read on [this page](http://docs.doctrine-project.org/projects/doctrine-common/en/latest/reference/caching.html) that PhpFileCache is not optimal for high concurrency and I'm not sure what exactly that means.

Question: do you think that ApcuCache is more suitable for high load site or maybe you can recommend some other cache?

**Comment by bpolaszek** [comment]
As a new feature, it would be nice if Device Detector implement PSR-6 cache.
This is a new PHP standard about caching, that allow you to use different types of caching (file, apcu, redis, mysql, ...)
http://www.php-fig.org/psr/psr-6/
The Symfony Cache component is a great implementation of that standard:
https://github.com/symfony/cache

**Comment by denis-n** [comment]
Today I've made my first benchmark tests.

wrk -t2 -c5 -d5s -H 'User-Agent: dfasdfdafadfad5asd6f5as4df654' --timeout 2s http://10.99.0.10

Results: 
**PhpFileCache:**

Running 5s test @ http://10.99.0.10
  2 threads and 5 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.60ms    1.63ms  48.27ms   94.17%
    Req/Sec   795.82    136.62     1.02k    69.00%
  7922 requests in 5.00s, 1.44MB read
Requests/sec:   1582.94
Transfer/sec:    295.18KB

**ApcuCache:**
Running 5s test @ http://10.99.0.10
  2 threads and 5 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.65ms    1.82ms  36.19ms   89.97%
    Req/Sec   435.18     50.75   626.00     78.00%
  4334 requests in 5.01s, 808.19KB read
Requests/sec:    865.67
Transfer/sec:    161.43KB

According to results, PhpFileCache is faster.

**Comment by denis-n** [comment]
Another round:

**PhpFileCache**
wrk -t12 -c400 -d30s -H 'User-Agent: dfasdfdafadfad5asd6f5as4df654' --timeout 2s http://10.99.0.10
Running 30s test @ http://10.99.0.10
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    55.95ms  111.67ms   1.43s    86.67%
    Req/Sec     3.03k   709.14     7.76k    74.05%
  1083048 requests in 30.04s, 357.59MB read
  Non-2xx or 3xx responses: 1071026
Requests/sec:  36056.48
Transfer/sec:     11.90MB

**ApcuCache**
wrk -t12 -c400 -d30s -H 'User-Agent: dfasdfdafadfad5asd6f5as4df654' --timeout 2s http://10.99.0.10
Running 30s test @ http://10.99.0.10
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    69.39ms  136.00ms   1.59s    85.94%
    Req/Sec     2.73k   672.40     6.28k    69.33%
  970952 requests in 30.06s, 320.85MB read
  Non-2xx or 3xx responses: 961960
Requests/sec:  32299.62
Transfer/sec:     10.67MB

**Comment by denis-n** [comment]
Actually my VPS' have 4 CPU and some article suggests I should be using 4 threads:

**PhpFileCache**
wrk -t4 -c400 -d30s -H 'User-Agent: dfasdfdafadfad5asd6f5as4df654' --timeout 2s http://10.99.0.10
Running 30s test @ http://10.99.0.10
  4 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    36.76ms   69.98ms 912.23ms   86.75%
    Req/Sec    10.26k     1.52k   15.53k    84.25%
  1226445 requests in 30.07s, 403.98MB read
  Non-2xx or 3xx responses: 1206428
Requests/sec:  40786.59
Transfer/sec:     13.43MB

**ApcuCache**
wrk -t4 -c400 -d30s -H 'User-Agent: dfasdfdafadfad5asd6f5as4df654' --timeout 2s http://10.99.0.10
Running 30s test @ http://10.99.0.10
  4 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    60.99ms  118.69ms 892.28ms   86.12%
    Req/Sec     9.65k     1.98k   16.74k    75.00%
  1152399 requests in 30.04s, 380.88MB read
  Non-2xx or 3xx responses: 1142259
Requests/sec:  38360.37
Transfer/sec:     12.68MB

**Comment by denis-n** [comment]
**Memcached**
wrk -t4 -c400 -d30s -H 'User-Agent: dfasdfdafadfad5asd6f5as4df654' --timeout 2s http://10.99.0.10
Running 30s test @ http://10.99.0.10
  4 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.36ms   68.45ms   2.00s    98.82%
    Req/Sec     7.81k     1.64k   20.56k    78.39%
  925310 requests in 30.05s, 306.86MB read
  Socket errors: connect 0, read 0, write 0, timeout 1199
  Non-2xx or 3xx responses: 924027
Requests/sec:  30792.78
Transfer/sec:     10.21MB

**Without cache**
wrk -t4 -c400 -d30s -H 'User-Agent: dfasdfdafadfad5asd6f5as4df654' --timeout 2s http://10.99.0.10
Running 30s test @ http://10.99.0.10
  4 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.79ms   69.06ms   1.98s    98.73%
    Req/Sec     7.75k     1.66k   22.40k    79.58%
  925971 requests in 30.06s, 307.07MB read
  Socket errors: connect 0, read 0, write 0, timeout 1224
  Non-2xx or 3xx responses: 924676
Requests/sec:  30808.06
Transfer/sec:     10.22MB

Looks like it's true that Memcached (and probably Redis) are not really that fast. Of course they have features which other types of caching are missing.

**Comment by GregOriol** [comment]
@denis-n The results might vary from setup to setup, but here are a few things to help:

PhpFileCache, as its name suggests, is a cache performed with files, on disk. So if your disk is very fast, SSDs for example, it will could work well enough. If your disk is a more traditional HDD, this type of cache will be much slower.

ApcuCache is a cache performed with APCu, in memory. It should therefore be very fast. APC is however an "old" php component that was deprecated in php5.6, and is not used anymore. It's variant APCu can still be installed, and is quite easy to install, but it is not much recommended nowadays. And from what I remember, it's local to your php instance.

If you are looking for a good/powerful/modern cache system, you should have a look into implementations with redis/memcache: these are harded to install as they require to setup servers, but are in memory (ie. very fast), well documented, have many features like distribution on many instances, can be shared by many php servers, ...

**Comment by GregOriol** [comment]
@sgiehl Maybe this issue could be closed as it is not related to DeviceDetector but more a general question about caching?

**Comment by denis-n** [comment]
Sure.
