### ISSUE TITLE
HHVM class_exists bug

### ISSUE THREAD

**Issue by denis-n** [matomo-org/device-detector#5575]
Hi,

I think I found a bug.

I was using your library with NGINX+PHP7 and with HHVM and 
when HHVM is in [Repo Authoritative](https://docs.hhvm.com/hhvm/advanced-usage/introduction) 
mode code below is not working as expected.
(It's working in default HHVM mode).

Code:
`var_dump(class_exists('Doctrine\Common\Cache\CacheProvider'), class_exists('\Doctrine\Common\Cache\CacheProvider'));`

It always shows `true and true`, except when HHVM is in Repo Authoritative mode.
In this case it returns `true and false`

I noticed this condition is in more than in one place.

**Comment by sgiehl** [comment]
Sorry, I'm not familiar with HHVM. Our tests on travis are running on HHVM, but I guess in default mode.
How can it be turned in Repo Authoritative mode?

**Comment by denis-n** [comment]
You can find how here
https://docs.hhvm.com/hhvm/advanced-usage/repo-authoritative#automatic-script

P.S. For me this is not high priority, I decided to use NGINX.
