### ISSUE TITLE
problem with Qwant bot

### ISSUE THREAD

**Issue by voxdemonix** [matomo-org/device-detector#5589]
Don't know why but piwik does not recognize the bot of Qwant search engine.

referer : "Qwantify/1.0"
regex in code : 'Qwantify'
Line code : [bot.yml#L782](https://github.com/piwik/device-detector/blob/master/regexes/bots.yml#L782)
[screenshot](https://framapic.org/akGhn9D0VqF9/DKLzxqugg5mI.png)

**Comment by voxdemonix** [comment]
Their is a problem too with Facebook External Hit (bot from facebook that verify content of link posted by facebook's user)

Referer : facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
regex in code : facebookexternalhit|facebookplatform
Line code : [bots.yml#L376](https://github.com/piwik/device-detector/blob/master/regexes/bots.yml#L376)


[screenshot](https://framapic.org/yoLyaJ8qvM1l/DyOcQ8Q26nPz.png)

**Comment by sgiehl** [comment]
which version of Piwik are you using? the detection library is only updated with Piwik. So if you have an older version running it might occur that some detection don't work yet

**Comment by voxdemonix** [comment]
Piwik version : 3.0.2
i update directly when you lunch the new version :)
Same problem with Bubing.

Thank you for your great work sgiehl ;)
