### ISSUE TITLE
OpenFin container detected as Chrome

### ISSUE THREAD

**Issue by pankajparashar-zz** [matomo-org/device-detector#5604]
[OpenFin](https://github.com/openfin/) is a secure HTML5 container that uses the Blink rendering engine. Piwik detects this as Chrome browser. However, the useragent string does say "OpenFin".

```js
>>> navigator.userAgent
"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 OpenFin/6.49.12.65 Safari/537.36"
```

Is there a way to identify this as OpenFin instead of Chrome? Any input is appreciated. Thanks

**Comment by sgiehl** [comment]
Sure. As long as OpenFin is contained in the useragent we can add a detection for that.
Won't be able to work on this the coming days, so i you need it quickly, feel free to issue a PR

**Comment by sgiehl** [comment]
See https://github.com/piwik/device-detector/pull/5556 or https://github.com/piwik/device-detector/pull/5436

**Comment by sgiehl** [comment]
Btw. you need to add the regex in the yml file before the chrome detection, otherwise it won't work, as detection aborts as soons as any regex matches
