### ISSUE TITLE
Additional browsers

### ISSUE THREAD

**Issue by Findus23** [matomo-org/device-detector#5609]
Now that we are using https://github.com/alrra/browser-logos/tree/master/src for the browser icons, we may add support for some of the browsers they have icons for.

Unfortunatly many of them don't have an unique user agent, but I'll see what I can find.

**Comment by sgiehl** [comment]
Could you maybe add the full list here, so we can check what we have - and what we need to investigate?

**Comment by Findus23** [comment]
# Current Browsers
## [adblock browser](https://adblockbrowser.org/)
- [ ] added
- seems to have no unique user agent

## [Beaker](https://beakerbrowser.com/)
- [ ] added

## [Blisk](https://blisk.io/)
- [ ] added

## [Boat](http://www.boatmob.com/mobile/product_browser_free.html)
- [ ] added

## [Browser.html](https://github.com/browserhtml/browserhtml#readme)
- [ ] added

## [Cent](https://www.centbrowser.com/)
- [ ] added

## Chrome Beta/Dev/Canary
- probably don't need to be detected as seperate browsers
- maybe check if they are detected as Chrome

## [Coast](https://www.opera.com/mobile/coast)
- [ ] added

## [Cốc Cốc](https://coccoc.com/)
- [ ] added
- "among the five most popular browsers in Vietnam"
- user agents similar to 
    - `Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/45.0 Chrome/39.0.2171.98 Safari/537.36`
    - `Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) coc_coc_browser/42.0 CoRom/36.0.1985.146 Chrome/36.0.1985.146 Safari/537.36`

## [Dooble](http://dooble.sourceforge.net/)
- [ ] added

## [Epic](https://www.epicbrowser.com/)
- [ ] added

## Firefox Beta/Developer Edition/Aurora/Nightly
- as Chrome

## [Firefox Focus](https://github.com/mozilla-mobile/focus)
- [ ] added

## [Iridium](https://github.com/iridium-browser)
- [ ] added

## [MIHTool](http://www.mihtool.com/)
- [ ] added
- not really a browser

## [Min](https://palmeral.github.io/min/)
- [ ] added


## [NetSurf](http://www.netsurf-browser.org/)
- [ ] added

## [NW.js](https://nwjs.io/)
- [ ] added
- not really a browser

## [Onion](https://mike.tig.as/onionbrowser/)
- [ ] added

## Opera Mini
- maybe detect it as a seperate browser as it is completly different from opera and opera mobile

## [Opera Neon](https://www.opera.com/computer/neon)
- [ ] added
- more a concept than a browser

## [Orbitum](https://orbitum.com/) 
- [ ] added

## [PhantomJS](http://phantomjs.org/)
- [ ] added

## [Polarity](http://polarityweb.weebly.com/)
- [ ] added

## [QupZilla](https://www.qupzilla.com/)
- [ ] added

## [qutebrowser](https://www.qutebrowser.org/)
- [ ] added

##[Tob](https://github.com/JRock007/Tob)
- [ ] added

##[Tofino](https://mozilla.github.io/tofino/)
- [ ] added

##[Tor(browser)](https://www.torproject.org/)
- [ ] added

##[WaterFox](https://www.waterfoxproject.org/)
- [ ] added

## Gnome Web
https://github.com/piwik/device-detector/pull/5527

There is a even longer list of outdated browsers, but they are getting even more obscure: 
https://github.com/alrra/browser-logos/tree/master/src/archive

**Comment by Findus23** [comment]
Most important ones have been added in the meantime and PhantomJS is also discussed in #5691.
