### ISSUE TITLE
Problem with DoctrineCache PhpFileCache

### ISSUE THREAD

**Issue by esurov** [matomo-org/device-detector#5619]
Hey folks!
We're using piwik/device-detector for device type detection: smartphone|tablet|desktop. And we've been happy with it for years. But recently I noticed we have a lot of errors in the NGINX error log like:

2017/05/29 05:45:22 [error] 835#0: *4363896 FastCGI sent in stderr: "PHP message: include(/tmp/30/446f637472696e654e616d65737061636543616368654b65795b5d.doctrinecache.php): failed to open stream: No such file or directory
PHP message: include(): Failed opening '/tmp/30/446f637472696e654e616d65737061636543616368654b65795b5d.doctrinecache.php' for inclusion (include_path='.:/usr/share/php')" while reading response header from upstream, client: 172.31.15.22, server: localhost, request: "POST /nexage.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:"

I tried to understand what's wrong, but can't figure out the source of the error. Could you advice please?

Thanks,
-Gene

**Comment by ThaDafinser** [comment]
AFAIR the file_exists and similar checks are disabled at doctrine for performance reason, so sometimes you see those warnings.

**Comment by esurov** [comment]
Thank you for your message!

I checked doctrine cache source code here:

/var/www/html/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php:112Doctrine\Common\Cache\PhpFileCache::includeFileForId

https://github.com/doctrine/cache/commit/0d46cc6973cbb62d90b1af595b58cd29b29a1a6b#diff-e934b971462b29fadee2591a97620fa6

they have changed it in master. They still don't check with file_exists, but replacing the error handler with an empty one. My question addresses more the fact why we're getting these warnings just now? We've never had them before.

**Comment by ThaDafinser** [comment]
multiple possible reasons:
- changed php version / error reporting or handling
- updated composer deps
- ...

**Comment by esurov** [comment]
I'm thinking about switching Doctrine Cache to dev-master. Not sure it's a good idea though.
