### ISSUE TITLE
Problem with Exabot

### ISSUE THREAD

**Issue by Zefling** [matomo-org/device-detector#5630]
Every day I have entries of ...

FAI: Exabot
Browser : Safari
System : Linux

User agent : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) NG/6.5.24024 Safari/538.1

It's very strange.

**Comment by sgiehl** [comment]
The useragent does not contain any bot fragments, so it will be detected as normal device.
What exactly is your problem?

**Comment by Zefling** [comment]
It's this visitor in Piwik and in my server log I found this user agent. For me, it's a bot, not au real user.

**Comment by sgiehl** [comment]
Hm. I don't see any possibility how we could detect that

**Comment by Zefling** [comment]
Okay, but Safari on Linux doesn't exist yet.

**Comment by sgiehl** [comment]
That's true. But guess we can't easily start ignoring useragents that don't make sense, as some device do that on purpose. An IE on windows phones for example has in some cases fragments for Windows, Android and iOS as well as for Safari, Chrome and IE.
