### ISSUE TITLE
Change model names of Samsung Galaxy devices (GALAXY -> Galaxy)

### ISSUE THREAD

**Issue by freekering** [matomo-org/device-detector#5644]
Official English notation is 'Galaxy', not 'GALAXY'.
(http://www.samsung.com/us/mobile/galaxy/)

**Comment by sgiehl** [comment]
@sanchezzzhak do you think we should change them? I don't have a strong opinion on it. 
Otherwise guess we could simply close the issue

**Comment by sanchezzzhak** [comment]
"Galaxy" In uppercase lowercase it looks pretty nice. I'm for +)

**Comment by sgiehl** [comment]
Ok. Then I'll leave the issue open. Feel free to rename that if you have some time. Otherwise I might look into it when I find some free time...
