### ISSUE TITLE
Usage with piwik C# API client?

### ISSUE THREAD

**Issue by Tennyleaz** [matomo-org/device-detector#5664]
I am using piwik tracking api within my C# client, how can I insert the brand/model information in my user agent string?
For example, like:
```C#
int osMajor = 6;
int osMinor = 2;
string strBrand = "Dell";
string UA = "Mozilla/5.0 (Windows NT " + osMajor + "." + osMinor + "; WOW64; en-US;"  + strBrand + ")";
// Mozilla/5.0 (Windows NT 6.2; WOW64; en-US; Dell)
```
is it possible?

**Comment by sgiehl** [comment]
Useragents on Windows usually don't include information about brand or model. So Device Detector doesn't try to detect any. There are only a few exceptions. Some brands add a vendor fragment to the useragent. See https://github.com/piwik/device-detector/blob/master/regexes/vendorfragments.yml

**Comment by Tennyleaz** [comment]
Get it.
After some testing, most known brands could be detected and shown in Piwik dashboard.
I tested few (Asus, Dell, HP), they show up correctly, but is marked as Windows **Phones** instead of Windows **Desktop**.
For example, `(Windows NT 6.0; WOW64; en-US; Dell)` shows a _Windows Vista phone by Dell_.
This will mess with our different platform, such as a real smart-phone device.
Could I let piwik know I am using a desktop instead?

**Comment by sgiehl** [comment]
Keywords like `Dell`, `Asus` or `HP` only occur in mobile user agents an so they are detected as those.
If you wish to have it detected as desktop with a brand use one of the vendor fragments like `MDDCS` fo `Dell`
