### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by stixpunk** [matomo-org/device-detector#5666]
I have problem with memory consumption. On version 3.7.5 used memory is only about 0.07MB but after upgrading to 3.8.1 or 3.8.2 it takes 2MB+. PHP version is 7.1.10, test script:

```php
<?php
require("../vendor/autoload.php");

$dd = new DeviceDetector\DeviceDetector($_SERVER['HTTP_USER_AGENT']);
$dd->setCache(new Doctrine\Common\Cache\PhpFileCache('../tmp/dd_cache/'));
$dd->parse();

$brand = $dd->getBrandName();
$model = $dd->getModel();

echo $_SERVER['HTTP_USER_AGENT']."<hr>".$brand." - ".$model;
?>
```

Any ideas where can be problem?

**Comment by sgiehl** [comment]
Don't have any idea. Need to profile this when I have some time

**Comment by sanchezzzhak** [comment]
I did a little research among `327099` useragents

| useragents | time     | memory   | memoryMax | timeMax | bots | os     | osVersion | osPlatform | browser | browserVersion | browserEngine | browserEngineVersion | deviceType | deviceBrand | deviceModel | timeAverage | memoryAverage |
|------------|----------|----------|-----------|---------|------|--------|-----------|------------|---------|----------------|---------------|----------------------|------------|-------------|-------------|-------------|---------------|
| 327099     | 581.3499 | 58739840 | 4.82 Mb   | 0.1466  | 2756 | 308370 | 285021    | 19669      | 256779  | 224583         | 249523        | 91446                | 294814     | 255165      | 241273      | 0.0018      | 179.58 byte   |

No memory leaks detected.
