### ISSUE TITLE
Adding support for Clover devices?

### ISSUE THREAD

**Issue by anyagk** [matomo-org/device-detector#5690]
Hi, I'm an engineer at [ShopKeep](www.shopkeep.com) and we (very gratefully!) use your gem to parse the useragents of our iPad point of sale registers to get OS, OS version, and device info. 

We are building out a version of our register to work on Clover devices, so would like to add their 6 Android tablets/smartphone devices. Their model names/numbers are fairly straightforward:

|Manufacturer|Model Number|Model Name|Type|
| ---|---:|---|---|
|Clover|C100|Clover Station|Tablet|
|Clover|C201|Clover Mobile (Wi-Fi + 3G)|Tablet|
|Clover|C300|Clover Mini (Wi-Fi)|Tablet|
|Clover|C301|Clover Mini (Wi-Fi + 3G)|Tablet|
|Clover|C401U|Clover Flex|Smartphone|
|Clover|C100|Clover Station (2018)|Tablet|

More info can be found here:
https://docs.clover.com/build/clover-devices/#targeting-clover-devices

The devices don't have browsers as they are locked down solely for taking payments and doing other point of sale related activities.

Do the core maintainers prefer to add devices themselves or do they prefer to get PRs?

**Comment by sgiehl** [comment]
If those devices don't have a browser where exactly are their useragents used? Do you have some example useragents? which can be used to create the regexes?

**Comment by anyagk** [comment]
They use a Firefox browser useragent. We inject the Clover device model into the useragent (e.g. `Clover/C300`) our cash register app sends to our backend, and then use your gem to parse that useragent. The more I look into it, the more it seems we should roll our own device detection on the backend since this is a little different use case than your gem is designed for. Thanks for your time.
