### ISSUE TITLE
Chrome headless detection

### ISSUE THREAD

**Issue by etienne-martin** [matomo-org/device-detector#5691]
Hi guys, 

I'm about to add support for Chrome Headless.

The implementation is fairly simple, we just need to look for `HeadlessChrome` in the user agent string.

My question is: 

Should we treat Chrome Headless as a bot or just a regular browser?

**Comment by sgiehl** [comment]
Not sure about that. Wouldn't add it as bot, not sure if browser would be best solution. We maybe could add it as library in https://github.com/piwik/device-detector/blob/master/regexes/client/libraries.yml ? Any other opinions?

**Comment by etienne-martin** [comment]
I wouldn't treat it as a library because even if it's headless, it is still a fully fledged browser with a real web engine (Blink).

**Comment by sgiehl** [comment]
then let's add as browser

**Comment by madiedinro** [comment]
I've found o lot of similar traffic, but phantom. `Mozilla/5.0 (Unknown; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1`

**Comment by sgiehl** [comment]
PhantomJS is similar to Chrome Headless

**Comment by etienne-martin** [comment]
Yes thanks, I'm planning on adding PhantomJS detection too.

**Comment by Findus23** [comment]
I'm not entirely sure if HeadlessChrome should be included in Matomo reports.

I ran all tests from https://observatory.mozilla.org/ and a visit in Matomo was counted. I think it was this one:
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/64.0.326
4.0 Safari/537.36
```
