### ISSUE TITLE
Keeps getting "client parser not found in"

### ISSUE THREAD

**Issue by edgren** [matomo-org/device-detector#5697]
Hello there!
I've downloaded the necessary files and using this code:

```
require_once 'classes/device-detector/DeviceDetector.php';

$dd = new DeviceDetector\DeviceDetector($_SERVER['HTTP_USER_AGENT']);

$dd->parse();

if($dd->isBot()) {
	$botInfo = $dd->getBot();
} else {
	$clientInfo = $dd->getClient();
	$osInfo = $dd->getOs();
	$device = $dd->getDevice();
	$brand = $dd->getBrandName();
	$model = $dd->getModel();
}
```

Now I'm getting this error message:
```
Fatal error: Uncaught Exception: client parser not found in D:\Websites\edgren-master\classes\device-detector\DeviceDetector.php:243 Stack trace: #0 D:\Websites\edgren-master\classes\device-detector\DeviceDetector.php(170): DeviceDetector\DeviceDetector->addClientParser('FeedReader') #1 D:\Websites\edgren-master\rss.php(10): DeviceDetector\DeviceDetector->__construct('Mozilla/5.0 (Wi...') #2 {main} thrown in D:\Websites\edgren-master\classes\device-detector\DeviceDetector.php on line 243
```

What have I missed?

**Comment by Findus23** [comment]
Hi,

It seems like the following check is failing because one of the `DeviceDetector\Parser\Client\*` classes is missing. 
https://github.com/matomo-org/device-detector/blob/e2ed52ea44f799a2e3a5f20364d1530b2ec7b87e/DeviceDetector.php#L230-L243
I think the error is that you are only requiring the main class and not the rest of DeviceDetector. 
So you'll either need to write your own autoloader ([which may get complicated](https://github.com/matomo-org/device-detector/issues/5505)) or use [composer](https://getcomposer.org/) (which I'd really recommend you as it will make fetching dependencies (`mustangostang/spyc`), updating DeviceDetector and many other things far easier. )

**Comment by sgiehl** [comment]
Thanks @Findus23 for answering.

**Comment by edgren** [comment]
Thank you for your answer, @Findus23, but the code you gave me is exactly the same that is in the official code. I have never used Composer and installed it for Windows/XAMPP earlier today because of this.

How can I fetch things in Composer for Windows? And how can I update DeviceDetector through it?

**Comment by Findus23** [comment]
One you have the `composer` executable ([check here](https://getcomposer.org/doc/00-intro.md#installation-windows) for info on how to get it), you can install DeviceDetector with `composer require piwik/device-detector`.
You will then have a `composer.json` (which lists all your installed libraries), a `composer.lock` (which helps to always install the exact same versions) and a `vendor/` folder, which includes the libraries.

In your code you'll then just need to require the `vendor/autoload.php`.

**Comment by edgren** [comment]
Okej. Where can I find these `autoload.php`, `composer.lock` and `composer.json`? And if I must create `autoload.php` by my self, what will it contain and where shall I put it? In `myproject/vendor`?

**Comment by Findus23** [comment]
You don't need to move any file anywhere. You just open your project directory in a terminal, execute `composer require piwik/device-detector` and it creates the file in this directory.

**Comment by edgren** [comment]
Oh! Neat!

```
PS C:\Users\edgren.EDGREN-PC> composer require piwik/device-detector
Using version ^3.9 for piwik/device-detector
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing mustangostang/spyc (0.6.2): Downloading (100%)
  - Installing piwik/device-detector (3.9.1): Downloading (100%)
piwik/device-detector suggests installing doctrine/cache (Can directly be used for caching purpose)
Writing lock file
Generating autoload files
```

The files was in the location I was in when I opened PowerShell, so I moved them into my project folder. Still the same error message. The files are located in `myproject/vendor` at this moment. What have I missed?

**Comment by Findus23** [comment]
Did you replace
`require_once 'classes/device-detector/DeviceDetector.php';`
with 
`require_once 'vendor/autoload.php';`?

**Comment by edgren** [comment]
Ah! I knew I've missed something! :P Everything works now! Many thanks for your patience and help!
