### ISSUE TITLE
LOGICOM ID bot 553

### ISSUE THREAD

**Issue by mkdev-jaugusto** [matomo-org/device-detector#5701]
Hi,

Some more LOGICOM smartphones, are being detected as BOT's

1.
https://www.logicom-europe.com/smartphones/611-id-bot-553.html

Sample user-agent:
Mozilla/5.0 (Linux; Android 6.0; IDbot553 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

2.
https://www.logicom-europe.com/smartphones/607-m-bot-551.html
Sample user-agent:
Mozilla/5.0 (Linux; Android 6.0; M BOT 551 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36

3.
https://www.logicom-europe.com/smartphones/597-b-bot-50.html
Sample user-agent:
Mozilla/5.0 (Linux; Android 6.0; B BOT 550 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.124 Mobile Safari/537.36

I suppose all these models in the below link have the problem, but I don't have user agents for them.
https://www.logicom-europe.com/recherche?controller=search&orderby=position&orderway=desc&search_query=BOT

Thanks,

**Comment by mkdev-jaugusto** [comment]
Still some more logicom devices being set as BOTS

In my opinion, the detection of bots shouldn't have a "generic" detection, but work only with a list of well identified bots.

Mozilla/5.0 (Linux; Android 6.0; B BOT 50 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.116 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 6.0; B BOT 550 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 6.0; IDbot553 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 6.0; IDbot553PLUS Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 6.0; M BOT 551 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 6.0; POWER BOT Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 7.0; ID bot 53 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 7.0; ID bot 53+ Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 7.0; M bot 51 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 7.0; M bot 54 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 7.0; M bot 60 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36

Thanks.

**Comment by sgiehl** [comment]
I've improved the detections. Those devices should be detected correctly now
