### ISSUE TITLE
WebOS regex is incorrect. 

### ISSUE THREAD

**Issue by luckily** [matomo-org/device-detector#5713]
Hi, The WebOS regex is incorrect. 
WebOS is LG-TV's OS now.
The correct keyword is `Web0S`(zero) instead of `WebOS`(O)

My advice is 
```
- regex: '(?:webOS|Web0S|Palm webOS)(?:/(\d+[\.\d]+))?'
```

For example. WebOS TV 3.x user-agent is:
```
Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.2.1 Chrome/38.0.2125.122 Safari/537.36 WebAppManager
```

You can see as below link:
http://webostv.developer.lge.com/discover/specifications/webos-tv-platform/web-engine/

https://github.com/matomo-org/device-detector/blob/master/regexes/oss.yml#L160

Thanks.

**Comment by GregOriol** [comment]
@luckily Could you make the change, add a test with your user-agent and submit a pull request?
