### ISSUE TITLE
Cheatsheet?

### ISSUE THREAD

**Issue by daybugging** [matomo-org/device-detector#5717]
Hey there,
do you know of a list with all available methods? Or do I have to crawl through the source?

// Edit:
README doesn't tell about `isDesktop()` function. 

Thx!

**Comment by sgiehl** [comment]
Nope, there isn't one atm.

All relevant methods should be within DeviceDetector.php. Maybe I'll generate a PHPDoc for it when I have some time...

**Comment by daybugging** [comment]
Thanks for the quick reply, one more thing:
- The README lacks proper tutorial on how to implement the built-in (file?) cache, how would I do that?
- Strangely, the current release of Doctrine throws an error when following the PhpFileCache instructions in README

Good day to you!

**Comment by S1SYPHOS** [comment]
@daybugging:
Quick overview of the most relevant methods:

```php
// Configuration Methods
setCache()
setYamlParser()
discardBotInformation()
skipBotDetection()

// General Device Type Methods
isBot()
isMobile()
isDesktop()
isTouchEnabled() // win8 tablets only

// General Client Type Methods
getBot() array
getClient() array|string
getOs() array|string
getDevice()
getDeviceName()
getBrand()
getBrandName()
getModel()
getUserAgent()

// Specific Device Type Methods
isSmartphone()
isFeaturePhone()
isTablet()
isPhablet()
isConsole()
isPortableMediaPlayer()
isCarBrowser()
isTV()
isSmartDisplay()
isCamera()

// Specific Client Type Methods
isBrowser()
isFeedReader()
isMobileApp()
isPIM()
isLibrary()
isMediaPlayer()
```

Unless stated, all `isSomething()` methods return booleans, all `getSomething()` methods return strings.
