### ISSUE TITLE
Bot Detection Issue

### ISSUE THREAD

**Issue by dabajabaza** [matomo-org/device-detector#5720]
piwik/device-detector (3.10.0):

Found in server logs some user-agents that aren't detected as bots.

- HubSpot Website Grader (web-crawlers@hubspot.com)
- python-requests/2.18.4

**Comment by Findus23** [comment]
Hi,

The latter isn't necessarily a bot but rather a common Python library to make HTTP requests. I wouldn't detect it as a bot.
