### ISSUE TITLE
Web Browser as Chrome detected

### ISSUE THREAD

**Issue by eleracmp** [matomo-org/device-detector#5722]
I use the device-detector with the standard browser of some android devices. It was detected as Chrome or Chrome mobile. For some of them it works with old device versions, but not for the new ones.

**Comment by Findus23** [comment]
Hi,
Are you sure it wasn't a Chrome browser? 
Can you more details about those browsers: Which Android version are they running on? What is the name of the webbrowser? And most importantly: What is their user agent?
You can find it out by e.g. visiting http://useragent.mkf.solutions

**Comment by eleracmp** [comment]
I send you an screenshoot with the user agent and the var_dump of the data
from device-detector. I used my elephone p6000 with his standard browser.
