### ISSUE TITLE
Mac Chrome cannot detect brand，Model

### ISSUE THREAD

**Issue by deathkel** [matomo-org/device-detector#5728]
* version :3.10.1
* User-Agent
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

```php
        $userAgent = $_SERVER['HTTP_USER_AGENT'];
        $dd = new DeviceDetector();
        $dd->setUserAgent($userAgent);
        $dd->parse();
        var_dump($dd->getBrand());
        var_dump($dd->getBrandName());
        var_dump($dd->getModel());
```

**Comment by sgiehl** [comment]
This useragent does not contain any direct information about the model or brand. Nevertheless we could assume that the brand is `Apple` as MacOS normally does not run on other hardware.

**Comment by deathkel** [comment]
will it support in future
