### ISSUE TITLE
Incorrect iOS User-Agent Strings

### ISSUE THREAD

**Issue by olivierphl** [matomo-org/device-detector#5729]
I have a question on something that is very important to me . It is going to sound like a stupid detail :(

An IPhone 5 was synch to an office 365 email. It did capture the correct devide ID number and IOS and type of Iphone ( an iPhone5) BUT instead of giving the correct iOS User-Agent String it gave an incorrect one. I believe the iOS User-Agent String listed for this iPhone 5 is Apple:

Apple-iPhone5C1/1001.525

but the one captured by Office 365 is showing

Apple-iPhone5C1/1101.5

Why would that be? Isn't this automated? Why would a program like Office 365 not get the correct name and number??

Thanks . Hopefully one of you geniuses can shed some light on this for me :)

**Comment by sgiehl** [comment]
Sorry, I don't have an answer on that. But at least it shouldn't make a difference for the detection with device detector, as that number is not used for any detection.

**Comment by mimmi20** [comment]
@olivierphl As I can see on [this site](https://justworks.ca/blog/ios-and), you got an update from iOS 6 to iOS 7
