### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by mostafiz80** [matomo-org/device-detector#5730]
Fatal error: Uncaught Error: Class 'DeviceDetector\DeviceDetector\Yaml\Symfony' not found in C:\xampp\htdocs\newbeta\test.php:22 Stack trace: #0 {main} thrown in C:\xampp\htdocs\newbeta\test.php on line 22

**Comment by Findus23** [comment]
Hi, the line in the example code is just optional to show that you can use another yaml parser. If you want to use the default parser, just don't add it.

**Comment by mostafiz80** [comment]
if i echo then its getting blank 
my code is <?php


require_once 'vendor/autoload.php';

use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\DeviceParserAbstract;

// OPTIONAL: Set version truncation to none, so full versions will be returned
// By default only minor versions will be returned (e.g. X.Y)
// for other options see VERSION_TRUNCATION_* constants in DeviceParserAbstract class
DeviceParserAbstract::setVersionTruncation(DeviceParserAbstract::VERSION_TRUNCATION_NONE);

$dd = new DeviceDetector($userAgent);

// OPTIONAL: Set caching method
// By default static cache is used, which works best within one php process (memory array caching)
// To cache across requests use caching in files or memcache
//$dd->setCache(new Doctrine\Common\Cache\PhpFileCache('./tmp/'));

// OPTIONAL: Set custom yaml parser
// By default Spyc will be used for parsing yaml files. You can also use another yaml parser.
// You may need to implement the Yaml Parser facade if you want to use another parser than Spyc or [Symfony](https://github.com/symfony/yaml)


// OPTIONAL: If called, getBot() will only return true if a bot was detected  (speeds up detection a bit)

  $clientInfo = $dd->getClient(); // holds information about browser, feed reader, media player, ...
  $osInfo = $dd->getOs();
  $device = $dd->getDevice();
  $brand = $dd->getBrandName();
  $model = $dd->getModel();

echo $osInfo;

**Comment by sgiehl** [comment]
you need to set `$userAgent` to any useragent that should be parsed...

**Comment by Findus23** [comment]
@sgiehl I think we should make both things a bit more clear in the reader (even though it seems obvious) as I also had the exact same questions on the forum https://forum.matomo.org/t/device-detector-product/27715/12

**Comment by sgiehl** [comment]
I've modified to readme a bit in https://github.com/matomo-org/device-detector/commit/6e0a5d2ab2335b39fcb1c61a17ed6dd6474de599
