### ISSUE TITLE
I want get device brand name and os info

### ISSUE THREAD

**Issue by mostafiz80** [matomo-org/device-detector#5731]
I want get device brand name and os info.
i installed using composer. but i didn't get the data 
when i echo this things   $osInfo = $dd->getOs();
  $device = $dd->getDevice();
  $brand = $dd->getBrandName();
  $model = $dd->getModel();

i get 0 1 like this

**Comment by sgiehl** [comment]
Which useragent are you trying to parse? And how does the full code look like?
