### ISSUE TITLE
Useragents not detected

### ISSUE THREAD

**Issue by gemal** [matomo-org/device-detector#5732]
We run a bit booking site in Denmark and have a lof of detections. These are some of the sone that are not detected:
```
Mozilla/5.0 (Linux; Android 6.0.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.1 Chrome/65.0.3325.109 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 7.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.1 Chrome/66.0.3359.126 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 7.0; DLI-L22 Build/HONORDLI-L22) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 YaBrowser/17.11.0.526.00 Mobil
Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.0.2 Chrome/65.0.3325.109 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 8.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.0.2 Chrome/64.0.3282.137 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 8.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.0.2 Chrome/65.0.3325.109 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 8.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.1 Chrome/66.0.3359.126 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 5.1.1; en-us; T01 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Mobile Safari/537.36
Mozilla/5.0 (Maemo; Linux; U; Sailfish; Mobile; rv:38.0) Gecko/38.0 Firefox/38.0 SailfishBrowser/1.0
Mozilla/5.0 (X11; U; Linux x86_64; da-DK) AppleWebKit/537.36 (KHTML, like Gecko)  Chrome/30.0.1599.114 Safari/537.36 Puffin/5.2.2IP
Mozilla/5.0 (X11; U; Linux x86_64; da-DK) AppleWebKit/537.36 (KHTML, like Gecko)  Chrome/30.0.1599.114 Safari/537.36 Puffin/5.2.2IT
Mozilla/5.0 (X11; U; Linux x86_64; de-de) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.117 Safari/537.36 Puffin/7.0.6.18027AP
YelpWebView/1.5 Android/7.0 YelpApp/9.10.0 (x-screen-scale 1.0;)
```

**Comment by sgiehl** [comment]
3 is fixed. will have a look at 8 and imho the last one is no bot. That seems to be the [YelpApp](https://www.yelp.com/mobile). Will add it to apps...

**Comment by sgiehl** [comment]
`T01` seems not to be very useful as device identifier. It might be a MeeGoTab T01 with Android. Those pc sticks are shipped with windows, but seem to be compatible with android. But it's hard to say if it's such a stick or another device with `T01` as identifier...

**Comment by Findus23** [comment]
@sgiehl according to [this](https://www.handsetdetection.com/device-detection-database/devices/eken/t01/) it seems to be an Eken T01 tablet.

**Comment by sgiehl** [comment]
and [WURFL](http://www.tera-wurfl.com/explore/?action=wurfl_id&id=acer_liquid_z330_ver1) would detect it as Acer Liquid Z330 LTE

**Comment by Findus23** [comment]
Ah, I thought `LMY47V` would be a device-id, but it is the android build. In this case I'd say it is impossible to know which `T01` is meant.

**Comment by sgiehl** [comment]
So, everything we could improve based on the user agents should be improved now :)

**Comment by gemal** [comment]
I'm using "3.10.1"

```
		$dd = new DeviceDetector("Mozilla/5.0 (Linux; Android 6.0.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.1 Chrome/65.0.3325.109 Mobile Safari/537.36");
		$dd->parse();
		$deviceName = $dd->getDeviceName();
```

Here `deviceName` will be empty

**Comment by Findus23** [comment]
@gemal 
Indeed, but if you look closely at
`Mozilla/5.0 (Linux; Android 6.0.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/4.1 Chrome/65.0.3325.109 Mobile Safari/537.36`
you see that the only information in it is that:
- they are using Firefox Focus 4.1
- they are using Android 6.0.1

If there are no more information in the user agent itself, DeviceDetector can't infer more.
