### ISSUE TITLE
ParserAbstract's buildByMatch method seems weird

### ISSUE THREAD

**Issue by GregOriol** [matomo-org/device-detector#5737]
* what was the reason to limit to $1 $2 $3? Right now there doesn't seem to be any use for more, but hardcording this technical limit might cause some trouble when one would want to use $4
* also, why not break the loop when a $x is not found? There doesn't seem to be any reason to catch a value with the regex and not use it as a replacement? it could enhance perfs a tiny bit by stopping the loops earlier?

**Comment by sanchezzzhak** [comment]
Count how many replacements can be through the method `substr_count ($item, '$'));` 

```
    protected function buildByMatch($item, $matches)
    {
        for ($nb=1, $cnt= substr_count ($item, '$')); $nb<=$cnt; $nb++) {
            if (strpos($item, '$' . $nb) === false) {
                continue;
            }
            $replace = isset($matches[$nb]) ? $matches[$nb] : '';
            $item = trim(str_replace('$' . $nb, $replace, $item));
        }
        return $item;
    }
}
```

**Comment by GregOriol** [comment]
@sanchezzzhak that doesn't seem to work better and seems a bit less efficient (consider for example that item is "$1 $2 $3 $1" and it will fail by trying $4 for nothing, also using substr_count would parse the whole string while the aim is to faster)

Actually, I'm wondering about something like:
```
    protected function buildByMatch($item, $matches)
    {
        $search = array();
        $replace = array();

        for ($nb = 1; $nb <= count($matches)-1; $nb++) {
            $search[] = '$'.$nb;
            $replace[] = $matches[$nb];
        }

        $item = trim(str_replace($search, $replace, $item));

        return $item;
    }
```

**Comment by sanchezzzhak** [comment]
@GregOriol yes you are right, extra iterations will be present
