### ISSUE TITLE
Broken PHP requirements

### ISSUE THREAD

**Issue by kAlvaro** [matomo-org/device-detector#5743]
[Minimum PHP version](https://github.com/matomo-org/device-detector/blob/746721a9003dd1e98f8a45542bb8cc45554e7e40/composer.json#L25) is 5.3.2:

    "require": {
        "php": ">=5.3.2",
        "mustangostang/spyc": "*"
    },

Current version uses [short array syntax](https://github.com/matomo-org/device-detector/blob/746721a9003dd1e98f8a45542bb8cc45554e7e40/DeviceDetector.php#L682) thus needs PHP/5.4:

    if (empty($this->brand) && in_array($osShortName, ['ATV', 'IOS', 'MAC'])) {
        $this->brand = 'AP';
    }

> PHP Parse error:  syntax error, unexpected '[' in /.../vendor/piwik/device-detector/DeviceDetector.php on line 682

**Comment by sgiehl** [comment]
Thanks for the report.
