### ISSUE TITLE
What is the expected Device output?

### ISSUE THREAD

**Issue by AnilGupte** [matomo-org/device-detector#5745]
Using the sample code, namely:
		$dd = new DeviceDetector($userAgent);
		$dd->parse();
		$device = $dd->getDevice();
		$brand = $dd->getBrandName();
		$model = $dd->getModel();

What output should be expected to $device, $brand, $model?  I am getting only 0 or 1 for $device and blank strings for the rest.  Here are some of the User Agent strings I am using:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

Also, is there any documentation, even informal?
Thanx for advice and help.

**Comment by sgiehl** [comment]
Your example user agents are all from desktop clients and do not contain any information about brand or model. For other examples and their returns you can have a look at all the test fixtures like: https://github.com/matomo-org/device-detector/blob/master/Tests/fixtures/smartphone-2.yml

**Comment by sgiehl** [comment]
which useragent exactly reports as android?

**Comment by AnilGupte** [comment]
Great!  See, it would have helped if there was even a basic smidgen of documentation. I wouldn't have needed to bother you. :-)

Thanx much for your help.
