### ISSUE TITLE
I think my adjustment is going wrong using composer.

### ISSUE THREAD

**Issue by umairsagar43** [matomo-org/device-detector#5751]
Fatal error: Uncaught Error: Class 'Spyc' not found in D:\xampp\htdocs\DeviceDetector\Yaml\Spyc.php:17 Stack trace: #0 D:\xampp\htdocs\DeviceDetector\Parser\ParserAbstract.php(155): DeviceDetector\Yaml\Spyc->parseFile('D:\\xampp\\htdocs...') #1 D:\xampp\htdocs\DeviceDetector\Parser\ParserAbstract.php(243): DeviceDetector\Parser\ParserAbstract->getRegexes() #2 D:\xampp\htdocs\DeviceDetector\Parser\Bot.php(53): DeviceDetector\Parser\ParserAbstract->preMatchOverall() #3 D:\xampp\htdocs\DeviceDetector\DeviceDetector.php(623): DeviceDetector\Parser\Bot->parse() #4 D:\xampp\htdocs\DeviceDetector\DeviceDetector.php(587): DeviceDetector\DeviceDetector->parseBot() #5 D:\xampp\htdocs\DeviceDetector\index.php(33): DeviceDetector\DeviceDetector->parse() #6 {main} thrown in D:\xampp\htdocs\DeviceDetector\Yaml\Spyc.php on line 17

**Comment by sgiehl** [comment]
Seems the dependency is not correctly installed...
