### ISSUE TITLE
NZ devices and useragents

### ISSUE THREAD

**Issue by Doozler** [matomo-org/device-detector#5752]
I have some New Zealand model codes, mostly samsung, and various other useragents if you are interested....

First time user, sorry if this isnt the right way to go about this...

Where would you like them and in what form?

**Comment by sgiehl** [comment]
@Doozler feel free to attach the list here or send it by mail to stefan@matomo.org

**Comment by sgiehl** [comment]
@Doozler  didn't receive anything till now. Feel free to send if you want or create a new issue with it.
I'll close this issue now.
