### ISSUE TITLE
Tracking device on which email has opened or clicked

### ISSUE THREAD

**Issue by sibbu2005** [matomo-org/device-detector#5753]
Hi,
This lib is working for me , I have implemented and created a test detecting script. I want to use this lib for a campaign application. This application send bulk email and when email is opened  I record the information like email and other static info. At the same page I am using this lib to get the device and OS info , but not working. 

When Link is redirected from email clients it displays BOT.

Suppose I send a mail to my sibbu2005@gmail.com and when I am opening this email on my mobile brower while login into gmail account , it does fetch the information, but it fetch as BOT.

**Comment by sgiehl** [comment]
Most web mail providers are using image proxies. That means when you open an email the images inside it won't be fetched directly from the original source. Instead the images are loaded from a proxy server, where the provider prefetches and caches the images. The prefetching is mainly done with bot like useragents. That's the reason why you see a bot beeing detected.

Tracking pixels/images in emails might only work correctly when they are opened in standalone email clients like thunderbird, outlook,..

**Comment by sibbu2005** [comment]
Thansk @sgiehl
