### ISSUE TITLE
A few missing brands and models

### ISSUE THREAD

**Issue by liviuconcioiu** [matomo-org/device-detector#5764]
- [x] Brand: Alcatel
Model: One Touch Pixi 3
User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; 4003A Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.93 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: One Touch Pixi 3
User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; en-us; 4027X Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36

- [x] Brand: Hyundai
Model: Ultra Air
User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; Ultra Air Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36

- [x] Brand: Bitel
Model: B8604
User-Agent: Mozilla/5.0 (Linux; Android 4.4.3; B8604 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Huawei
Model: P8 Lite
User-Agent: Mozilla/5.0 (Linux; Android 5.0; hi6210sft Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Oppo
Model: Neo 7
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; A33f Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36

- [x] Brand: Oppo
Model: A37
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; A37fw Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: One Touch Pop 3
User-Agent: Mozilla/5.0 (Linux; Android 5.1; 5015A Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.85 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: One Touch Pop 3
User-Agent: Mozilla/5.0 (Linux; Android 5.1; 5016A Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: One Touch Pixi 3
User-Agent: Mozilla/5.0 (Linux; Android 5.1; 5017A Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: One Touch Pop 3
User-Agent: Mozilla/5.0 (Linux; Android 5.1; 5025G Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Essential
Model: PH-1
User-Agent: Mozilla/5.0 (Linux; Android 8.1.0; PH-1 Build/OPM1.180104.234) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Sony
Model: Xperia XZ1
User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; SOV36 Build/47.1.C.9.34) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Sony
Model: Xperia XZ1
User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; G8342 Build/47.1.A.12.235; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: LG
Model: Fortune 2
User-Agent: Mozilla/5.0 (Linux; Android 7.1.2; LM-X210CM Build/N2G47H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36

- [x] Brand: BlackBerry
Model: KEYone
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; BBB100-7 Build/NMF26F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: BlackBerry
Model: KEYone
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; BBB100-1 Build/NMF26F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Kogan
Model: Agora 6 Plus
User-Agent: Mozilla/5.0 (Linux; Android 7.0; Kogan Agora 6Plus Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: aiwa
Model: AW790
User-Agent: Mozilla/5.0 (Linux; Android 7.0; AW790 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Wiko
Model: U Pulse Lite
User-Agent: Mozilla/5.0 (Linux; Android 7.0; U PULSE LITE Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Orange
Model: Rise 33
User-Agent: Mozilla/5.0 (Linux; Android 7.0; Orange_Rise_33 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Orange
Model: Rise 31
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Orange-Rise31 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36

- [x] Brand: Hyundai
Model: Ultra Live II
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Ultra Live II Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Wolder
Model: Wiam #24
User-Agent: Mozilla/5.0 (Linux; Android 6.0; WIAM #24 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Vonino
Model: Zun X
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Zun X Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

and this one is a Phablet

- [x] Brand: Coolpad
Model: REVVL Plus
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; REVVLPLUS C3701A Build/143.02.171026.3701A-TMO) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

**Comment by sgiehl** [comment]
should now all be detected correctly
