### ISSUE TITLE
Google Podcasts

### ISSUE THREAD

**Issue by pierrocknroll** [matomo-org/device-detector#5773]
Hi,

According to this doc : 
https://developers.google.com/search/docs/data-types/podcast#analytics

You can know in the user agent if the "Google Podcasts" app has been used.

Thanks a lot

**Comment by sgiehl** [comment]
@pierrocknroll  do you have a website hosting podcasts?
According to the description it suggests to look for `GSA`. But afaik `GSA` might already be added by the Android search bar

**Comment by pierrocknroll** [comment]
@sgiehl Yes

Oh really ? Maybe you could handle GoogleChirp for now ?

**Comment by liviuconcioiu** [comment]
Detection for Google Podcasts on iOS has been added here: https://github.com/matomo-org/device-detector/blob/092830418af8d0da202dda55a059a5aec45de1a5/regexes/client/mobile_apps.yml#L715

For Android devices right now is impossible to detect.

Issue should be closed.
