### ISSUE TITLE
Via Browser Android

### ISSUE THREAD

**Issue by tsteur** [matomo-org/device-detector#5775]
I'm using this browser but I don't think we can detect the browser based on the agent I presume?
https://play.google.com/store/apps/details?id=mark.via.gp&hl=en

> Mozilla/5.0 (Linux; Android 7.0; SM-G920F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/68.0.3440.85 Mobile Safari/537.36

**Comment by sgiehl** [comment]
No. Doesn't seem the useragent contains any fragments that can lead to the correct browser.
It will be detected as Chrome Mobile...
