### ISSUE TITLE
2 more useragents that is not detected

### ISSUE THREAD

**Issue by gemal** [matomo-org/device-detector#5777]
We run a large restaurant booking site and found a few more useragents that doesn't detect:

`Mozilla/5.0 (X11; U; Linux x86_64; en-HK) AppleWebKit/537.36 (KHTML, like Gecko)  Chrome/30.0.1599.114 Safari/537.36 Puffin/5.2.0IT`
`Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; XBLWP7; ZuneWP7)`

**Comment by sgiehl** [comment]
@gemal  Thanks for the report.
Those useragents do not include any fragments that allow a detection for a specific device. Nevertheless browser and operating system should be detected correctly for both useragents. So there is nothing we could do there...
