### ISSUE TITLE
IE10 user agent detected as IE9 browser

### ISSUE THREAD

**Issue by davidloubere** [matomo-org/device-detector#5778]
Hello, the user agent `Mozilla/5.0 (MSIE 10.0; Windows NT 6.1; Trident/5.0)` is detected as if it were IE9. However, client info are reported as follow:
```
[
  "type" => "browser"
  "name" => "Internet Explorer"
  "short_name" => "IE"
  "version" => "9.0"
  "engine" => "Trident"
  "engine_version" => "5.0"
]
```

Looks like a bug to me, no?

**Comment by sgiehl** [comment]
Well, it might not be fully correct, but also is not wrong. We first try to match the Trident version.
And according to Microsoft the Trident version 5.0 was only used in IE 9. See https://en.wikipedia.org/wiki/Trident_(software)#Release_history
So actually it can't be a IE 10 using Trident 5.

**Comment by davidloubere** [comment]
Agree. What puzzles me is that the UA mentioned above comes packaged with User-Agent Switcher (1.0.43) for Chrome, which is an extension provided by Google.
