### ISSUE TITLE
A few missing brands and models

### ISSUE THREAD

**Issue by liviuconcioiu** [matomo-org/device-detector#5782]
Smartphones

- [x] Brand: AKAI
Model: Neo
User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; AKAI_NEO Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: U5 Plus
User-Agent: Mozilla/5.0 (Linux; Android 7.0; 4047A Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: A3 Plus
User-Agent: Mozilla/5.0 (Linux; Android 7.0; 5011A Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: A3 Plus
User-Agent: Mozilla/5.0 (Linux; Android 7.0; 5049G Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: A3 XL
User-Agent: Mozilla/5.0 (Linux; Android 7.0; 9008A Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: U3
User-Agent: Mozilla/5.0 (Linux; Android 6.0; 4049G Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: OneTouch Pixi 3
User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; 4009A Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.109 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: OneTouch Pixi 3
User-Agent: Mozilla/5.0 (Linux; Android 4.4.2; 4027A Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.89 Mobile Safari/537.36

- [x] Brand: Alcatel
Model: OneTouch Pixi 4
User-Agent: Mozilla/5.0 (Linux; Android 5.1; es-mx;  8050G Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.76 Mobile Safari/537.36

- [x] Brand: Bitel
Model: B9501
User-Agent: Mozilla/5.0 (Linux; Android 6.0; B9501 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36

- [x] Brand: BlackBerry
Model: KEYone
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; BBB100-2 Build/NMF26F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

- [x] Brand: BLU
Model: Studio View XL
User-Agent: Mozilla/5.0 (Linux; Android 7.0; Studio View XL Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Bluboo
Model: S8
User-Agent: Mozilla/5.0 (Linux; Android 7.0; BlubooS8 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Bmobile
Model: AX1075
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; AX1075 Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Comio
Model: P1
User-Agent: Mozilla/5.0 (Linux; Android 7.0; COMIO P1 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Coolpad
Model: Cool Play 6
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; VCR-I0 Build/VCRSIN00X1000DPX1709300) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.85 Mobile Safari/537.36

- [x] Brand: Doogee
Model: Valencia 2 Y100 Pro
User-Agent: Mozilla/5.0 (Linux; Android 5.1; Valencia2_Y100pro Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

- [x] Brand: FNB
Model: ConeXis X1
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; ConeXis X1 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/49.0.2623.105 Mobile Safari/537.36

- [x] Brand: GoMobile
Model: Onyx Mini
User-Agent: Mozilla/5.0 (Linux; Android 7.0; GO Onyx Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36

- [x] Brand: HTC
Model: One M9
User-Agent: Mozilla/5.0 (Linux; Android 7.0; 0PJA2 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Huawei
Model: Honor 5A
User-Agent: Mozilla/5.0 (Linux; Android 6.0; CAM-TL00 Build/HONORCAM-TL00) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Huawei
Model: Honor 9i
User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; LLD-AL20 Build/HONORLLD-AL20) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Huawei
Model: Honor 9 Lite
User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; LLD-AL10 Build/HONORLLD-AL10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Mobile Safari/537.36

- [x] Brand: Karbon
Model: K9 Smart Grand
User-Agent: Mozilla/5.0 (Linux; Android 7.0; K9 Smart Grand Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36

- [x] Brand: Kempler & Strauss
Model: Alumini 3.0
User-Agent: Mozilla/5.0 (Linux; Android 7.0; Alumini3Plus Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Lava
Model: Flair Z1
User-Agent: Mozilla/5.0 (Linux; Android 5.0; Flair Z1 Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36

- [x] Brand: Meizu
Model: M5s
User-Agent: Mozilla/5.0 (Linux; Android 6.0; M5s Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.131 Mobile Safari/537.36

- [x] Brand: Miray
Model: MPM-AVA4501
User-Agent: Mozilla/5.0 (Linux; Android 4.4.4; MPM-AVA5501 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36

- [x] Brand: MYRIA
Model: Wide 2
User-Agent: Mozilla/5.0 (Linux; Android 7.0; Myria_Wide_2 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36

- [x] Brand: Oppo
Model: A3
User-Agent: Mozilla/5.0 (Linux; Android 8.1.0; PADM00 Build/O11019) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

- [ ] Brand: Padgene
Model: S9
User-Agent: Mozilla/5.0 (Linux; Android 5.1; S9 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

- [x] Brand: Polaroid
Model: Turbo E
User-Agent: Mozilla/5.0 (Linux; Android 7.0; P4526A Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: Polaroid
Model: Cosmo K
User-Agent: Mozilla/5.0 (Linux; Android 7.0; P5006A Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36

- [x] Brand: SKY
Model: 4.5LM
User-Agent: Mozilla/5.0 (Linux; Android 5.1; SKY 4.5LM Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

- [x] Brand: Silent Circle
Model: Blackphone 2
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Blackphone 2 Build/MOB31Z) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.92 Mobile Safari/537.36

- [x] Brand: Sonim
Model: XP7700
User-Agent: Mozilla/5.0 (Linux; Android 5.1.1; XP7700 Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

- [x] Brand: Sony
Model: Xperia XA1 Plus
User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; G3416 Build/48.1.A.2.21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36

- [x] Brand: TCL
Model: Gala G60
User-Agent: Mozilla/5.0 (Linux; Android 7.0; TCLGalaG60(9108A) Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.85 Mobile Safari/537.36

- [x] Brand: Tecno
Model: Phantom 6 Plus
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; Phantom6-Plus Build/NMF26O) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

- [x] Brand: Top House
Model: Coto W418
User-Agent: Mozilla/5.0 (Linux; Android 5.1; Coto W418 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

- [x] Brand: Uhappy
Model: UP320
User-Agent: Mozilla/5.0 (Linux; Android 4.4.4; UHAPPY UP320 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36

- [x] Brand: Unonu
Model: UM405 Lite
User-Agent: Mozilla/5.0 (Linux; Android 5.1; UNONU UM405 LITE Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

- [x] Brand: Vestel
Model: Venus V5
User-Agent: Mozilla/5.0 (Linux; Android 7.1.2; Venus V5 Build/VTE1180) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

- [x] Brand: Wiko
Model: Robby
User-Agent: Mozilla/5.0 (Linux; Android 6.0; ROBBY Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Mobile Safari/537.36

- [x] Brand: Zonda
Model: ZA409
User-Agent: Mozilla/5.0 (Linux; Android 5.1; ZA409 Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.76 Mobile Safari/537.36

- [x] Brand: Zuum
Model: Zen I
User-Agent: Mozilla/5.0 (Linux; Android 5.0; ZUUM_ZEN_I Build/LRX21M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36

- [x] Brand: ZTE
Model: Overture 3
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; Z851M Build/NMF26V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Crosswalk/11.45.2454.20170525 Mobile Safari/537.36

- [x] Brand: ZTE
Model: Avid 4
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; Z855 Build/NMF26V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36

- [x] Brand: ZTE
Model: Maven 3
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; Z835 Build/NMF26V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Mobile Safari/537.36

- [x] Brand: ZTE
Model: Blade X Max
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; Z983 Build/NMF26F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Crosswalk/11.45.2454.20170222 Mobile Safari/537.36

- [x] Brand: ZTE
Model: Blade Z Max
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; Z982 Build/NMF26V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36

- [x] Brand: ZTE
Model: MAX Blue LTE
User-Agent: Mozilla/5.0 (Linux; Android 7.1.1; Z986DL Build/NMF26V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/45.0.2454.95 Mobile Safari/537.36

Tablets

- [ ] Brand: Ampe
Model: A96
User-Agent: Mozilla/5.0 (Linux; Android 5.1; A96 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36

- [x] Brand: Tech Pad
Model: XTAB 781+
User-Agent: Mozilla/5.0 (Linux; Android 4.2.1; XTAB 781+ Build/JOP40D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36

**Comment by Findus23** [comment]
Added icons for all new brands apart from Zuum.
But wow, some of these are really obscure and hard to google.

**Comment by sgiehl** [comment]
All useragents that are unambiguously should now be added. Those unchecked can't be clearly matched to a brand, as more than one brand has a device with that name.
