### ISSUE TITLE
My top user agents from logs

### ISSUE THREAD

**Issue by lord-alfred** [matomo-org/device-detector#5803]
Perhaps these data will help improve the definition of bots. 
All data is collected from a proxy web server that redirects visits (such as bitly).

[top-user-agents.txt](https://github.com/matomo-org/device-detector/files/2368309/top-user-agents.txt)

**Comment by lord-alfred** [comment]
New portion of the past tense.
The original log size is 2GB.

[top-user-agents.txt](https://github.com/matomo-org/device-detector/files/2452117/top-user-agents.txt)

**Comment by mimmi20** [comment]
@lord-alfred The list would be easier to handle if you would not add counters in it, just the useragents.

**Comment by jaydiablo** [comment]
Here's a copy with the counters removed:

[top-user-agents(1).txt](https://github.com/matomo-org/device-detector/files/2452374/top-user-agents.1.txt)

**Comment by lord-alfred** [comment]
> @lord-alfred The list would be easier to handle if you would not add counters in it, just the useragents.

Sorry, friend, I just used the command from the Readme: https://github.com/matomo-org/device-detector#listing-all-user-agents-from-your-logs

**Comment by mimmi20** [comment]
@lord-alfred 
Sorry about ma comment. I did not see that.

**Comment by sanchezzzhak** [comment]
my list (22mb)  for last year that failed to identify brand + model  
https://drive.google.com/file/d/1Q63d3Pz5VhUYh-0wCVBug1kHyg9awF6y/view?usp=sharing
the list is grouped by uniqueness + sorted

**Comment by lord-alfred** [comment]
@sanchezzzhak, "pretty" report for your useragents here: https://github.com/matomo-org/device-detector/issues/5824#issuecomment-427919568

**Comment by sgiehl** [comment]
Will close this issue. I'm currently collecting all useragents from several older issues in order to check them and create a new issue with all undetected ones.
