### ISSUE TITLE
Javascript/Node.js port of device-detector

### ISSUE THREAD

**Issue by etienne-martin** [matomo-org/device-detector#5814]
I wanted to use device-detector in a Node.js project but I couldn't find any port of this lib that I could rely on. The only two ports that I found were these guys:
https://github.com/sanchezzzhak/node-device-detector 
https://www.npmjs.com/package/device-detector-node

The thing is, they are both poorly tested and unmaintained. I don't want to take the gamble of running these libs in production.

So, I decided to write my own port of device-detector using typescript. It uses this repo as a dependency so it can easily be updated whenever we add new regexes or tests to this repo. It passes the ~6300 tests from this repo and it's also pretty fast. I gave it the original name of device-detector-js:
https://www.npmjs.com/package/device-detector-js

If you guys agree I will create a PR to update the README.md with this new port.

**Comment by sgiehl** [comment]
awesome. feel free to update the README :+1: 
Btw. you maybe could mention in your readme that missing/incorrect detections should be reported here instead of in your project

**Comment by etienne-martin** [comment]
I just created a Github issue template to tell people where to report issues about missing/incorrect detections: https://github.com/etienne-martin/device-detector-js/issues/new

**Comment by etienne-martin** [comment]
Thanks to @alexbeauchemin, we updated the library so that it now works in the browser too.
