### ISSUE TITLE
Is it able to detect jdownloader!

### ISSUE THREAD

**Issue by RonyDam** [matomo-org/device-detector#5815]
As the title says ?

**Comment by sgiehl** [comment]
can you provide a sample useragent of jdownloader

**Comment by RonyDam** [comment]
Jdownloader == http://jdownloader.org. Is likely a download manager don't know if it has any useragent

**Comment by sgiehl** [comment]
The library only parses useragents, so without a useragent it can't be detected.

**Comment by RonyDam** [comment]
Well they use custom useragent like browser so probably it would not work. Thanks anyway
