### ISSUE TITLE
Add/Detect Snapchat UA as a bot

### ISSUE THREAD

**Issue by jLynx** [matomo-org/device-detector#5820]
Hi team
Can we include Snapchats user agent header as a bot as it is used to fetch metadata about the link:
`AppEngine-Google; (+http://code.google.com/appengine; appid: s~snapchat-proxy)`

Thanks

**Comment by adampatterson** [comment]
I am in the process of discovery.

I have a lot of requests from `AppEngine-Google; (+http://code.google.com/appengine; appid: s~snapchat-proxy)` and would really like to know if it's someone using a Google service or if it is in fact Snapchat.

if it is Snapchat why would they be crawling my site?

**Comment by jLynx** [comment]
Someone would have linked to your site in a snapchat message @adampatterson

**Comment by adampatterson** [comment]
@jLynx I discovered that its a proxy that people use to spoof Geo Walls in Snapchat.

So it was someone using a Google service running a VPN

**Comment by adampatterson** [comment]
@jLynx my main reasoning for thinking it's not Snapchat is that It was nearly 250k requests to invalid URLs in a month.

**Comment by jLynx** [comment]
Oh yeah. That makes sense too 😂
