### ISSUE TITLE
A huge portion of useragents for verification/tests and a script for generating a report from top-user-agents.txt

### ISSUE THREAD

**Issue by lord-alfred** [matomo-org/device-detector#5824]
I have already [shown my user agents](https://github.com/matomo-org/device-detector/issues/5803) from the logs, but they are there in unreadable form.
So I made a [small script](https://github.com/lord-alfred/top-useragents-report-generator) that would show how device-detector defines them.

Report in the attached file (archived)
[0c58f370ad26984e5a1b741d1748fa2d.html.zip](https://github.com/matomo-org/device-detector/files/2452991/0c58f370ad26984e5a1b741d1748fa2d.html.zip)
.

**Comment by lord-alfred** [comment]
Generated a report on 178k lines user agents from here: https://github.com/matomo-org/device-detector/issues/5803#issuecomment-427905639

[31a93d3f4e246e8af6bbf90203026b30.html.zip](https://github.com/matomo-org/device-detector/files/2457013/31a93d3f4e246e8af6bbf90203026b30.html.zip)

**Comment by sanchezzzhak** [comment]
Such large files are very hard to open.
https://clusterize.js.org/ 
+ add filters

**Comment by lord-alfred** [comment]
@sanchezzzhak great advice! 
I'll try to add it tomorrow :)

**Comment by sgiehl** [comment]
Will close this issue. I'm currently collecting all useragents from several older issues in order to check them and create a new issue with all undetected ones.
