### ISSUE TITLE
What type of device and in what file to add car tablets?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#5827]
```
Mozilla/5.0 Linux; U; Android 4.1.1; ru-ru; KZCAR Build/JRO03C AppleWebKit/534.30 KHTML, like Gecko Version/4.0 Safari/534.30
```
Model:
http://incar-intro.ru/shtatnye-magnitoli/ssangyong/incar-ahr-7789sy.html

**Comment by sgiehl** [comment]
Even if the name might not include everything, you should use `Car Browser`:
https://github.com/matomo-org/device-detector/blob/master/regexes/device/car_browsers.yml

**Comment by sanchezzzhak** [comment]
It is worth adding as usual tablet, so as browser, can be any.

**Comment by sgiehl** [comment]
The device type `Car Browser` is a bit misleading. We maybe should change that to `Car`. And as long as those "car tablets" are devices that are (a fixed) part of a car, we should add it to the `car` type
