### ISSUE TITLE
Xiaomi mobile devices have bracket at the end of model name, when the client is Chrome mobile

### ISSUE THREAD

**Issue by ffurbo** [matomo-org/device-detector#5853]
Eg. 
(
  [type] => smartphone
  [brand] => XI
  [model] => Redmi 4A)
)

**Comment by Findus23** [comment]
Hi,

It would be really great if you could post the exact user agent here.

**Comment by ffurbo** [comment]
Sure, user agent for this example is: 
Mozilla/5.0 (Linux; Android 6.0.1; Redmi 4A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.64 Mobile Safari/537.36
