### ISSUE TITLE
Generic model matching vs detailed model matching

### ISSUE THREAD

**Issue by GregOriol** [matomo-org/device-detector#5858]
Hi,

Quick question on the matching regexes: in the current regexs, there are both very generic model matchings (ie. "Galaxy ([a-z0-9]+)") and also very specific model matchings (ie. "SM-G935[AFLPSTV]").

I was wondering which one should we prefer when possible? For example, the second one could be written as just "SM-G935" and will match all variants for this model. This would loose the specifics, and precise, model matching, but would likely increase the long term use of the matching as there will be no need to add all possible variants when they appear.

What do you think?

**Comment by sgiehl** [comment]
Guess that can be improved at some places. If there are no devices matching a similar regex there is no need to match the letters at the end.

**Comment by sanchezzzhak** [comment]
This question has long been not discussed the topic is closed.
