### ISSUE TITLE
iPhone 7 displays as "iPhone"

### ISSUE THREAD

**Issue by davidenco** [matomo-org/device-detector#5860]
When I call `$dd->getModel()` for my iPhone 7, the result is "iPhone".

How do I displays the actual model?

**Comment by sgiehl** [comment]
would you please share the useragent of your device

**Comment by davidenco** [comment]
So it looks like the iOS Facebook app is sending more information about the device compared to the native Safari browser! That's useful!

**Comment by neohuruyi** [comment]
the same, if i use iphone in  wechat browser,  only get deivcename Iphone,not a details.
