### ISSUE TITLE
Redmi 5A shows up as Redmi 5A)

### ISSUE THREAD

**Issue by mattab** [matomo-org/device-detector#5873]
See how Redmi 5A shows up as Redmi 5A): 

![device model - incorrect](https://user-images.githubusercontent.com/466765/49058194-d55d1280-f267-11e8-8cb3-954c5345b834.jpg)

If possible, may be worth creating a test to check returned models/etc. don't include `()`?

**Comment by sgiehl** [comment]
Are you able to look up the useragent?

**Comment by GregOriol** [comment]
@sgiehl This issue is not closed by my commit: I just added a test on a user-agent related to this device, one that is working. I did not find one that produces the extra ")", nor did I apply and change or fix for the issue.

**Comment by sgiehl** [comment]
sure. but that one is imho a duplicate of #5853
