### ISSUE TITLE
Honor 10

### ISSUE THREAD

**Issue by spyjo** [matomo-org/device-detector#5874]
Hello,

Here is a new Android smartphone to add: Honor 10 (Huawei)
User agent on Chrome:
Mozilla/5.0 (Linux; Android 8.1.0; COL-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Mobile Safari/537.36

COL-L29 is the internal model name. COL-AL10 is also known to be Honor 10.

Thanks

**Comment by sgiehl** [comment]
fixed in #5875
