### ISSUE TITLE
Edge browser detects wrong version

### ISSUE THREAD

**Issue by tb-mtg** [matomo-org/device-detector#5880]
I tried your [demo](http://devicedetector.net/) site with Edge browser and it returned user agent

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763`

but incorrectly says version is 18, but it actually is 44.17763.1.0 as show below from the app settings:

![image](https://user-images.githubusercontent.com/12589600/49564178-be5ca580-f976-11e8-966c-0e7bf7b98c11.png)

Can you fix so that is show the correct version?

**Comment by sgiehl** [comment]
No. we can't. It seems to hide it's real version from the useragent. Unless there is an exact mapping from EdgeHTML version to Edge version, there is no way to do this.
