### ISSUE TITLE
New Browsers

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/device-detector#5885]
extracted from #5808

**New Browsers**

Here, are a few BBS (Bulletin board system) browsers, all for the Japanese market.

- [x] Browser Name: 2chMate
User-Agent: Monazilla/1.00 2chMate/0.8.10.10 Dalvik/2.1.0 (Linux; U; Android 5.0.2; LGT01 Build/LRX22G)
Link: https://play.google.com/store/apps/details?id=jp.co.airfront.android.a2chMate&hl=en

- [x] Browser Name: 2tch
User-Agent: Monazilla/1.00 2tch/6.6.3 iOS11.40 iPhone7,2

- [x] Browser Name: Ciisaa
User-Agent: Monazilla/1.00 Ciisaa/1.55 Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 7)
Link: https://play.google.com/store/apps/details?id=com.gmail.aosoan.ciisaa&hl=en

- [x] Browser Name: BB2C
User-Agent: Monazilla/1.00 (BB2C 1.3.83; iOS 11.4.1 iPhone10,1)
Link: https://itunes.apple.com/us/app/bb2c/id298820042?mt=8

- [x] Browser Name: twinkle
User-Agent: Monazilla/1.0 (twinkle/8.0; iOS11.4.1; iPhone10,1)
Link: https://itunes.apple.com/app/twinkle/id463142843

- [x] Browser Name: JaneStyle
User-Agent: Monazilla/1.00 JaneStyle_iOS/1.6.2.3 iOS11.4.1 iPhone,9,1
Link: https://jbbs.shitaraba.net/internet/8173/

- [x] Browser Name: Live5ch
User-Agent: Monazilla/1.00 Live5ch/1.52 Windows/10.0.17134

- [x] Browser Name: BathyScaphe
User-Agent: Monazilla/1.00 BathyScaphe/1057 Mac OS X/10.11.6
Link: https://osdn.net/projects/bathyscaphe/

- [x] Browser Name: JaneView
User-Agent: Monazilla/1.00 (JaneView/1501150412)

**Comment by kitekkitek** [comment]
Plus Microsoft Edge for macOs:
https://www.microsoftedgeinsider.com/en-us/?form=MO12FS&OCID=MO12FS

**Comment by Findus23** [comment]
@kitekkitek Can you please provide a useragent for Edge on macOS?

**Comment by kitekkitek** [comment]
Sorry:

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3794.0 Safari/537.36 Edg/76.0.161.0

**Comment by Findus23** [comment]
@kitekkitek It seems like without explicit support DeviceDetector already supports this correctly:
https://devicedetector.lw1.at/Mozilla%2F5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_14_4)%20AppleWebKit%2F537.36%20(KHTML,%20like%20Gecko)%20Chrome%2F76.0.3794.0%20Safari%2F537.36%20Edg%2F76.0.161.0
```json
{
  "isBot": false,
  "clientInfo": {
    "type": "browser",
    "name": "Microsoft Edge",
    "short_name": "PS",
    "version": "76.0.161.0",
    "engine": "Blink",
    "engine_version": ""
  },
  "osInfo": {
    "name": "Mac",
    "short_name": "MAC",
    "version": "10.14.4",
    "platform": ""
  },
  "device": 0,
  "deviceName": "desktop",
  "deviceBrand": "Apple",
  "model": "",
  "icons": {
    "browser": "/icons/browsers/PS.png",
    "os": "/icons/os/MAC.png",
    "device": "/icons/devices/desktop.png",
    "brand": "/icons/brand/Apple.png"
  }
}
```
Or is there anything that can be detected more precisely?

**Comment by kitekkitek** [comment]
I have 3.11.6 and it parses it as:
```
>>> $user_agent->getClient()
=> [
     "type" => "browser",
     "name" => "Chrome",
     "short_name" => "CH",
     "version" => "76.0",
     "engine" => "Blink",
     "engine_version" => "",
   ]
```

Checked dev-master and it parses like you said. It looks I need to wait for stable version.
