### ISSUE TITLE
Cannot detect models and brands of Huawei

### ISSUE THREAD

**Issue by khoivm** [matomo-org/device-detector#5888]
Hey, 

Thanks for maintaining this great project.

I found out an issue of detection for Huawei smartphone. 
I tested with these UAs:
```
Mozilla/5.0 (Linux; Android 8.0.0; ANE-LX1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 8.0.0; WAS-L03T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36
```

Even though in `regexes/device/mobiles.yml` has already defined the pattern:
```
regex: 'ANE-LX[123]'
model: 'P20 Lite'

regex: 'WAS-L(?:X1|X1A|X2|X2J|X3|03T)'
model: 'P10 Lite'
```
But it returns `null` for both brand and model. Seems like the regex is not working.

**Comment by GregOriol** [comment]
@khoivm Did you try with the latest from master? They seem to work now

**Comment by sgiehl** [comment]
Both useragents are detected correctly with latest release.
