### ISSUE TITLE
Some Brand Model not get Detected

### ISSUE THREAD

**Issue by brightq** [matomo-org/device-detector#5889]
Hi, 

There are some Device Model can not get detected, please see bellow for your reference. 

`Mozilla/5.0 (Linux; Android 8.0.0; LM-G710) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36`
Brand: LG
Model: G7 ThinQ

Mozilla/5.0 (Linux; Android 6.0; DIG-L01) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36
Brand: Huawei 
Model: Nova Smart

`Mozilla/5.0 (Linux; Android 8.0.0; ATU-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36`
Brand: Huawei (already detected)
Model: Y6-2018

`Mozilla/5.0 (Linux; Android 7.1.2; Action-X3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36`
Brand: Crosscall
Model: Action-X3

**Comment by sgiehl** [comment]
thanks for the report. Will add those detections...
