### ISSUE TITLE
Future enhancements and lots of updating

### ISSUE THREAD

**Issue by etetlow** [matomo-org/device-detector#5896]
Hi. I have a project where I need to parse user agents and after doing some testing with 5 different user agent parsers, I'd really like to use this one. I have forked the repo and will send regular pulls of updates, mostly on devices and operating systems. But there are a couple of things that I'd like to know are possible to change as I believe that changing them will make future expansion of categories easier.

At present there are 13 functions: 
getClient with name, version, type, short_name, engine and engine_version.
getOs with name, version, platform and short_name.
getBrandName.
getDeviceName.
getModel.

My suggestion is to put getBrandName, getDeviceName and getModel into getDevice with type, maker, brand and model. I think the addition of the maker or manufacturer is important as many people would be surprised who makes some of these phones and also in cases like the Nexus range.

On a not so important note, separating engine from client into a getEngine function with name and version will yet again help with future expansion.

I plan to do a weekly pull as I've just acquired over 1 million user agent strings and am going to work through them filling any gaps as they come along and by the end this should be the most accurate and consistent device detector out there.

Thanks.

**Comment by sgiehl** [comment]
Hi @etetlow 
It would be awesome if you would help to improve the detections of DeviceDetector.

Regarding the addition of marker/manufacturer. Personally I wouldn't want to start maintaining this information as it strongly device dependent. Currently there are a lot "general" detection like
```
Kogan:
  regex: 'Kogan'
  device: 'smartphone'
  models:
    - regex: 'Kogan[ _-]([^;/]+) Build'
      model: '$1'
    - regex: 'Kogan[ _-]([a-z0-9_-]+)'
      model: '$1'
```
This won't be possible if we need to maintain device specific information and would blow up the list of detections maybe.

If there are any methods that you think would be good to add, feel free to create PRs for it. But we should try not to change any existing methods in a way that break backwards compatibility.

Looking forwards for your improvements :-)

**Comment by etetlow** [comment]
Hey @sgiehl 

You are right, it will blow up the list of device detections, and I have seen some of the general detection regex. It is useful when the vendor uses the same model number as their product name, but this, unfortunately, is rarely the case. I am aiming for accuracy throughout and when product names are being used I don't see any other way than to have each model listed. Of course you can group the model numbers for each model, but there's no doubt that the list is going to grow substantially.

You could limit to how far back the list goes. I expect somewhere online there's a list of what phone models are actually still in use because to cover to, say when the first iPhone came out, that would be 12 years worth of phones. Another way of keeping the process quick, even if the list was massive, would be to split them so each manufacturer would have its own file. At the moment, looking at companies like HTC or Huawei, their model lists are 1000 odd lines.

These are things for you and whoever else is involved to decide. I'm just going to plug my way through the data which unfortunately, if you want a good, competitive device detector, is the only option available and with regular updating too. Have found [this site](https://www.devicespecifications.com/en) a god send! ; )
