### ISSUE TITLE
Issue with Samsung regexes

### ISSUE THREAD

**Issue by liviuconcioiu** [matomo-org/device-detector#5900]
The current regexp doesn't match the exact model. This could lead to erroneous detection for future models.

For example:

`Mozilla/5.0 (Linux; Android 8.0.0; SM-G965F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36`

gives Samsung GALAXY S9+, which is good, but if this one is checked

`Mozilla/5.0 (Linux; Android 8.0.0; SM-G965FXXX Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36`

will output Samsung GALAXY S9+, which is wrong, as right now Samsung GALAXY S9+ has only 4 variants defined `SM-G965[FUW0]`, and G965FXXX is matched wrong.

**Comment by sgiehl** [comment]
I did not yet recognize any model fragments that are just a bit longer, but represent a completely different device. Nevertheless I got your point.
If that is the case somewhere it's useful to add something like `[);/ ]` in the end to ensure the model fragment ends here. But I think in many cases it's on purpose to have the regex a bit less restrictive.
