### ISSUE TITLE
Brand Model Detection Suggestions

### ISSUE THREAD

**Issue by brightq** [matomo-org/device-detector#5910]
Hi 
We have discovered some new brand/model that not yet included in Matomo

````
  "user_agents": [
    {
      "ua": "Mozilla/5.0 (Linux; Android 9; Pixel 3 Build/PQ1A.190105.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Google",
        "model": "Pixel 3 XL" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 6.0.1; U673C Build/U673C_01.01.08; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Unimax",
        "model": "U673C" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 7.1.1; UL40 Build/UL40_01.01.05; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "ANS",
        "model": "UL40"
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 8.1.0; 5041C Build/OPM1.171019.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Alcatel",
        "model": "Tetra" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 8.1.0; LM-V405 Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "LG",
        "model": "V40 ThinQ" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 7.0; C8 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Tecno",
        "model": "Tecno Camon C8"
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 8.1.0; LM-Q710.FGN Build/OPM1.171019.019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "LG",
        "model": "LG Q Stylus Plus" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 8.1.0; LM-Q710.FG Build/OPM1.171019.019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "LG",
        "model": "LG Q7" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 8.1.0; LM-X410.FGN Build/OPM1.171019.019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "LG",
        "model": "LM-X410.FGN" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 5.1; Tmovi YeahLIVE Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Tmovi",
        "model": "Yeah Live" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 6.0; Origins Pro Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "STF",
        "model": "Origins Pro"
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 6.0; Joy Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Zen",
        "model": "Admire Joy"
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 6.0; Joy Pro Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "X-TIGI",
        "model": "Joy"
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 6.0; S6000 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Lenovo",
        "model": "Lenovo Idea Tab" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 6.0; Advance 4.0M Build/A090; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "BLU",
        "model": "Advance 4.0 M" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 6.0; Miracle 6.0 S Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "CellAllure",
        "model": "Miracle 6.0 S"
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 5.1; P5025A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Polaroid",
        "model": "L5s" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 8.1.0; DRA-LX3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Huawei",
        "model": "Y5 2018" ✔
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 6.0; POLYTRON R2508 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36 (Mobile; afma-sdk-a-v14799017.14799017.0)",
      "deviceInfo": {
        "brand": "Polytron",
        "model": "Rocket",
        "deviceType": "smartphone"
      }
    },
    {
      "ua": "Mozilla/5.0 (Linux; Android 6.0; Ilium X510) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36",
      "deviceInfo": {
        "brand": "Lanix",
        "model": "Ilium X510" ✔
      }
    }
  ]
````

**Comment by brightq** [comment]
Here are some more device detection we have found that currently not included in matomo

UserAgent | Brand | Model
-- | -- | --
Mozilla/5.0 (Linux; Android 6.0; P10 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.78 Mobile Safari/537.36 | Teclast | P10
Mozilla/5.0 (Linux; Android 5.1; SMART MAX 4.0 PLUS Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 | True | Smart Max 4.0 Plus
Mozilla/5.0 (Linux; Android 6.0; SMART 4G Speedy 5.0 Plus Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36 | True | Smart 4G Speedy 5.0 Plus
Mozilla/5.0 (Linux; Android 6.0; T702 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36 | Fondi | T702
Mozilla/5.0 (Linux; Android 5.1; P9 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 | Forme | Forme Discovery P9
Mozilla/5.0 (Linux; Android 8.1.0; LM-X410(FG) Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36 | LG | LM-X410 (FG)
Mozilla/5.0 (Linux; Android 5.1; SSB-500 Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36 | Maze | SSB-500
Mozilla/5.0 (Linux; Android 7.0; SUPER Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 | UMI | SUPER
Mozilla/5.0 (Linux; Android 4.4.4; Z970 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 | ZTE | ZTE ZMAX Z970
Mozilla/5.0 (Linux; Android 7.1.2; E6810 Build/5.572VZ.13.c; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36 | Kyocera | Kyocera DuraForce Pro LTE
Mozilla/5.0 (Linux; Android 8.1.0; LML212VL Build/OPM1.171019.019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36 | LG | LML212VL
Mozilla/5.0 (Linux; Android 7.0; PCD509 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36 | PCD | 509
Mozilla/5.0 (Linux; Android 7.0; VS501 Build/NRD90U; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36 | LG | LG K20

**Comment by tbregovic** [comment]
✔|UserAgent|Brand|Model
-|-|-|-
-|Mozilla/5.0 (Linux; Android 7.0; TRIO F40LT Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36|FiGO|TRIO F40LT
-|Mozilla/5.0 (Linux; Android 5.1; gxq6580_weg_l Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36|Alps|gxq6580_weg_l
-|Mozilla/5.0 (Linux; Android 6.0; 5041 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36|Advan|5041
-|Mozilla/5.0 (Linux; Android 6.0; 5059 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36|Advan|5059
-|Mozilla/5.0 (Linux; Android 5.1; S5E_NXT Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.76 Mobile Safari/537.36|Advan|S5E NXT
-|Mozilla/5.0 (Linux; Android 7.0; 5058 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36|BQ|5058
-|Mozilla/5.0 (Linux; Android 7.0; 5062 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36|Alcatel|5062
-|Mozilla/5.0 (Linux; Android 6.0; i5K Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36|Advan|I5K
-|Mozilla/5.0 (Linux; Android 5.1; i5E Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/49.0.2623.105 Mobile Safari/537.36|Advan|I5E
-|Mozilla/5.0 (Linux; Android 6.0; S4Z Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36|Advan|S4Z
-|Mozilla/5.0 (Linux; Android 7.0; S7D Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36|Advan|S7D
-|Mozilla/5.0 (Linux; Android 5.1; A75 Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36|Dapeng|A75
-|Mozilla/5.0 (Linux; Android 7.0; i4U Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36|Advan|I4U
-|Mozilla/5.0 (Linux; Android 7.0; i55D Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36|Advan|I55D
-|Mozilla/5.0 (Linux; Android 6.0; HM-G552-FL Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36|Haier|HM-G552-FL
-|Mozilla/5.0 (Linux; Android 7.0; i55K Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.84 Mobile Safari/537.36|Advan|I55K
-|Mozilla/5.0 (Linux; Android 5.1; A75A* Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36|Evercoss|A75A Star
-|Mozilla/5.0 (Linux; Android 6.0; I7D Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36|Advan|I7D
-|Mozilla/5.0 (Linux; Android 7.0; S50H Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.91 Mobile Safari/537.36|Advan|S50H
-|Mozilla/5.0 (Linux; Android 7.0; 5061 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36|Advan|5061
-|Mozilla/5.0 (Linux; Android 7.0; IF9007 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36|InFocus|IF9007
-|Mozilla/5.0 (Linux; Android 7.0; i7U Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.111 Mobile Safari/537.36|Advan|I Lite i7U
-|Mozilla/5.0 (Linux; Android 6.0; S45E Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36|Advan|S45E

**Comment by brightq** [comment]
Created updated  new issue #5974 to replace this issue
