### ISSUE TITLE
No engine data when mobile app is used.

### ISSUE THREAD

**Issue by etetlow** [matomo-org/device-detector#5923]
I know that the engine and engine version are set within client in this application but is it dependant on the client being a browser because it seems as though whenever a mobile app is being used within the user agent the engine and engine version return as unknown. Of course the engine and engine version are both there in the user agent so this information should be obtainable. Perhaps having engine as a separate entity may solve the issue.

Here are a couple of examples to show what I've explained.

`Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77 [FBAN/FBIOS;FBAV/190.0.0.67.93;FBBV/125048840;FBDV/iPhone8,2;FBMD/iPhone;FBSN/iOS;FBSV/11.4.1;FBSS/3;FBCR/Bluegrass;FBID/phone;FBLC/en_US;FBOP/5;FBRV/125768202]`

`Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Mobile/15D60 Instagram 33.0.0.11.96 (iPhone10,1; iOS 11_2_5; en_US; en-US; scale=2.00; gamut=wide; 750x1334)`

**Comment by etetlow** [comment]
Just to make it clear, you may think the second user agent that I gave to you works just fine, but when you correct the fact that it comes up with Safari and add Instagram to the mobile app regex, it too fails to provide an engine.

**Comment by sanchezzzhak** [comment]
we don't plan to return the engine rendering type for mobile apps.

For IOS mobile, it's always Safari
For Android this is Webview(WebKit)
