### ISSUE TITLE
Illegal string offset 'regex'

### ISSUE THREAD

**Issue by blue-eyed-devil** [matomo-org/device-detector#5937]
getting Illegal string offset 'regex' error in following files:
vendor/piwik/device-detector/Parser/ParserAbstract.php on line 260
vendor/piwik/device-detector/Parser/OperatingSystem.php on line 169
vendor/piwik/device-detector/Parser/Device/DeviceParserAbstract.php on line 575
vendor/piwik/device-detector/Parser/Client/Browser.php on line 274

installed via composer
PHP: 7.3

**Comment by sgiehl** [comment]
I've enabled tests for PHP 7.3 on travis right now. Let's see if that passes.
How does the code you are using device detector in looks like?

**Comment by blue-eyed-devil** [comment]
I think i know what is the problem, just reinstalling dependencies and will let you know.
I am using visavi/cleanup to clean useless files from packages (.txt, .md, ...) before uploading to server and seems it don't like .yml files too. It did the same before with google cloud settings stored in json :)

**Comment by blue-eyed-devil** [comment]
I reinstalled and all working perfect. Thanks
