### ISSUE TITLE
Amazon Echo Devices are not identified

### ISSUE THREAD

**Issue by mayurbhole** [matomo-org/device-detector#5939]
Amazon Echo devices are not identified. They have common regex pattern like "AEO[A-Z]{2,3}"
Examples:
Mozilla/5.0 (Linux; Android 5.1.1; AEOKN Build/LVY48F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Safari/537.36
Dalvik/2.1.0 (Linux; U; Android 5.1.1; AEOBC Build/LVY48F)

**Comment by mayurbhole** [comment]
Hi...Is this issue resolved?

**Comment by GregOriol** [comment]
Hi @mayurbhole, couldn't find any test on user-agents containing AEOBC or AEOKN in the code base.

Also, couldn't find any reference on the internet about those user-agents. Where did you get them from? Could you provide more information on what they are? Are there any other variants/versions?

Maybe you could make a PR to add these?

**Comment by sanchezzzhak** [comment]
Intelligent speaker https://www.amazon.com/all-new-amazon-echo-speaker-with-wifi-alexa-dark-charcoal/dp/B06XCM9LJ4

I can do PR if you tell me which type device to use in yml?

**Comment by adityasravya** [comment]
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 299

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetBinaryState xmlns:u="urn:Belkin:service:basicevent:1"><BinaryState>1</BinaryState></u:GetBinaryState></s:Body></s:Envelope>
DEBUG:root:POST /upnp/control/basicevent1 HTTP/1.1
SOAPACTION: "urn:Belkin:service:basicevent:1#GetBinaryState"
Content-Type: text/xml; charset="utf-8"
Accept: 
User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1.1; AEOBC Build/LVY48F)
Host: 192.168.0.11:50023
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 299

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetBinaryState xmlns:u="urn:Belkin:service:basicevent:1"><BinaryState>1</BinaryState></u:GetBinaryState></s:Body></s:Envelope>

**Comment by adityasravya** [comment]
Echo dot is not responding..

**Comment by sgiehl** [comment]
@sanchezzzhak we now have the device type smart speaker, where Amazon Echos can be added.

**Comment by sanchezzzhak** [comment]
Hi I'll add)

**Comment by mimmi20** [comment]
It may call an API or load Streams.

**Comment by sgiehl** [comment]
Amazon Echos should meanwhile be detected correctly...
