### ISSUE TITLE
Update the DeviceDetector.net demo instance

### ISSUE THREAD

**Issue by da2x** [matomo-org/device-detector#5947]
The demo instance on http://devicedetector.net/ was last updated on 2017-12-04. A lot have happen since then.

Please update the demo instance. Maybe new instances could be auto-deployed for new releases?

**Comment by sgiehl** [comment]
No. The detections have been updated recently. The readme shown there is only quite old. Currently don't have much time to recreate that page completely, so it updates automatically.

**Comment by Findus23** [comment]
@sgiehl If you are interested, I'd like to maintain a new website for devicedetector.net
I can't promise that I'd get to it soon, but at the latest in summer I should be able to do it.

**Comment by sgiehl** [comment]
@Findus23 sure. Let me know if you need anything
