### ISSUE TITLE
Unify empty responses

### ISSUE THREAD

**Issue by Findus23** [matomo-org/device-detector#5951]
Changing this would probably break backwards compatibility, so I'm not sure if this could be changed, but I want to document this nevertheless:

The output of the different methods return different values if nothing can be detected (null, empty array and "").

Example script:
```php
<?php
require_once 'vendor/autoload.php';
use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\DeviceParserAbstract;

$userAgent = "thisissomeunknownuseragent";
$dd = new DeviceDetector($userAgent);
$dd->parse();

$botInfo = $dd->getBot();
$clientInfo = $dd->getClient();
$osInfo = $dd->getOs();
$device = $dd->getDeviceName();
$brand = $dd->getBrandName();
$model = $dd->getModel();

var_dump($botInfo);
var_dump($clientInfo);
var_dump($osInfo);
var_dump($device);
var_dump($brand);
var_dump($model);
```
Output:
```
NULL
NULL
array(0) {
}
string(0) ""
string(0) ""
string(0) ""
```

**Comment by sgiehl** [comment]
feel free to create a PR for that. we can include that in a new major release

**Comment by Findus23** [comment]
Now the question is what the proper return value would be.

**Comment by sanchezzzhak** [comment]
In my opinion, it is better to return `NULL`
