### ISSUE TITLE
New bots

### ISSUE THREAD

**Issue by lord-alfred** [matomo-org/device-detector#5953]
- [x] Mozilla/5.0 (compatible; Embedly/0.2; +http://support.embed.ly/)
- [x] Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/55.0 BrandVerity/1.0 (http://www.brandverity.com/why-is-brandverity-visiting-me)
- [x] Apache-HttpClient/4.5.3-SNAPSHOT (Java/1.8.0_152)
- [ ] Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US) AppEngine-Google; (+http://code.google.com/appengine; appid: s~virustotalcloud)
- [x] curl/7.54.0
- [x] Sprinklr 2.0
- [x] PostmanRuntime/7.6.0
- [x] Wget/1.12 (linux-gnu)
- [x] python-requests/2.21.0
- [x] Lynx/2.8.6rel.4 libwww-FM/2.14 SSL-MM/1.4.1 OpenSSL/0.9.8g

`Mozilla/5.0 (compatible; Embedly/0.2; +http://support.embed.ly/)` visit my sites every day more than 1000 times...

**Comment by Findus23** [comment]
Hi, Lynx is not a bot, but a text based browser (as [correctly detected by DeviceDetector](https://devicedetector.lw1.at/%20Lynx%2F2.8.6rel.4%20libwww-FM%2F2.14%20SSL-MM%2F1.4.1%20OpenSSL%2F0.9.8g))

Apache-HttpClient, curl, wget, python-requests are also not bots, but libraries for HTTP requests as correctly detected by DeviceDetector.

**Comment by lord-alfred** [comment]
@Findus23 , Okay, I agree. 5 unknowns bot left

**Comment by viktorix** [comment]
Any update on this? We see a lot of spam bot traffic trying to submit forms using python-requests.

**Comment by lord-alfred** [comment]
@viktorix , I went around this as follows: https://gist.github.com/lord-alfred/e45ff2e9e3e50c46588b7cf69db4e73d

**Comment by sanchezzzhak** [comment]
PostmanRuntime/7.6.0  this is both an app and a library  (repository https://github.com/postmanlabs/postman-runtime) 
<img src="https://www.postman.com/assets/api-monitor/postman-api-monitoring.gif">
