### ISSUE TITLE
Some informations

### ISSUE THREAD

**Issue by LorenzoVET** [matomo-org/device-detector#5958]
Hi all.

This is not exactly to report an issue but instead to know something about this PHP package that I would to use in a project (I am unable to find useful information in other places).

Some question:
1) How I can detect if IE is running in compatibility view mode? Is there a property o a method to grab this information? Or I must only perform some check (through the existent informations) in order to verify the situation?
2) If I don't have understand bad, this PHP package use some regular expressions to verify the browser. How often are they update? In case of a new devices, what can I modify?

Thanks for these information.

**Comment by sgiehl** [comment]
There is currently no flag to check for compatibility mode of IE. 
We try to update the detection rules regularly and try to release new versions at least every 2 months.
If you see any incorrectly detected devices, feel free to create issues for it or even pull requests for adding them.

**Comment by LorenzoVET** [comment]
Hi sgiehl.

Thanks for these information.

Regards.
