### ISSUE TITLE
Add lightweight version of device-detector or options

### ISSUE THREAD

**Issue by gibigate** [matomo-org/device-detector#5964]
Without brand or models, configurable.

In our server the library works ±0.6s, it's too long

**Comment by sgiehl** [comment]
What information are you trying to achieve? Parsing for bots can be done without any other parsing. Same applies for OS or Browser, but if you want to get the device type the parsing for models and brands is required.

**Comment by gibigate** [comment]
We try to get browser & os & type of device (smartphone or any). The best results is from this library. So i need ability to off detecting brands & models.
Is it possible or not?

**Comment by Findus23** [comment]
Hi @gibigate,

On https://devicedetector.lw1.at/ I am able to get the full response from DeviceDetector in about 60ms, which includes the overhead of making a HTTP request, making a TLS handshake and also detecting the correct icons for the brands, etc. all on my small vServer.
So with proper setup of caching it should be possible to get DeviceDetector to be pretty fast. I am using Redis caching, but I'm pretty sure this is overkill and you should be able to get fast results with simpler caching backends.

**Comment by gibigate** [comment]
@Findus23 thanks for your feedback
Can you send me example code of redis cache? I will try it on memcache

**Comment by Findus23** [comment]
@gibigate You can find the source [here](https://github.com/Findus23/devicedetector.net/blob/master/public/ua.php) and [here](https://github.com/Findus23/devicedetector.net/blob/master/src/CacheLoader.php)
