### ISSUE TITLE
Small type format issue in one test

### ISSUE THREAD

**Issue by andre-kornetzky** [matomo-org/device-detector#5969]
Hello. When comparing the test data, I noticed the following irregularities:

browser.yml, line 1722:
user_agent: Mozilla/5.0 (Linux; U; Android 4.3; en-us; Nexus 4 Build/JOP24G) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/37.0.0.0 Mobile Polarity/6.0.0 Safari/534.30

The version ends with an 0. Some Implementations (e.g. java) will skip trailing zeros in the test-definition (while it will parsed as a double value). 
The Device Detector returns the string "534.30", which unfortunately is not equal to the parsed double number 534.3. For a better consistency, it would be advantageous to define the (engine) version with trailing 0 as a string.

**Comment by Findus23** [comment]
So if I understand you correctly, you are proposing to change this line (and the few below) from `534.30` to `"534.30"`?

https://github.com/matomo-org/device-detector/blob/92fa41434af96b762e6c25a8d2287fa2a79567d5/Tests/Parser/Client/fixtures/browser.yml#L1729

Makes sense to me, but I am not sure how many test entries are "incorrect" like that.
Could you maybe create a PR for that?

**Comment by sgiehl** [comment]
Actually it should be enough to adjust the test sorter to do that: https://github.com/matomo-org/device-detector/blob/master/misc/sortTestFixtureFiles.php
Running it afterwards should change that in all tests automatically then

**Comment by andre-kornetzky** [comment]
Hello Findus, yes that's correct. And after my tests in Java this also seems to be the only case.

Thanks a lot!

**Comment by sgiehl** [comment]
Just had a look., And the mentioned file is one of those maintained manually... I'll update it
