### ISSUE TITLE
error: look-behind requires fixed-width pattern

### ISSUE THREAD

**Issue by gailmargolis76** [matomo-org/device-detector#5970]
I keep getting this error when i try to use this library. I installed python3-dev, python3-pip and regex but that doesn't seem to fix it! Any ideas what's wrong?

**Comment by gailmargolis76** [comment]
Just wanted to add that I'm using the Python version

**Comment by Findus23** [comment]
Hi,
I'd recommend you to report this to the developer of the python port:
https://github.com/thinkwelltwd/device_detector

But I am getting the same error on install, so maybe either some new in python invalid regex were added in the last versions or it maybe has issues with python3.

**Comment by Findus23** [comment]
You need to install `python3-regex` to fix the issue. (or run `pip install regex` depending on how you manage your dependencies)
With https://github.com/thinkwelltwd/device_detector/issues/18 this shouldn't be needed anymore.

**Comment by sgiehl** [comment]
thanks @Findus23 for looking into it. I'll close the issue for now.

**Comment by gailmargolis76** [comment]
i tried pip install regex, it still didn't work! For context, I'm on a Mac OS X

**Comment by spiderpug** [comment]
Hi @sgiehl ,

we are maintaining a ruby version of the device detector at https://github.com/podigee/device_detector and noticed that one regular expression is not available in Ruby: there is no support for non-fixed-width look-behinds, see https://github.com/kkos/oniguruma/blob/master/doc/RE#L283-L290 for details.

For now we got rid of this violation and removed some test ( https://github.com/podigee/device_detector/commit/e87bad008c265affe17192255e80b81b1637dd1c ). Do you see a way to rewrite this Regex?

**Comment by sgiehl** [comment]
But https://github.com/kkos/oniguruma/blob/master/doc/RE#L283-L290 says 
```
          Subexp of look-behind must be fixed-width.
          But top-level alternatives can be of various lengths.
          ex. (?<=a|bc) is OK. (?<=aaa(?:b|cd)) is not allowed.
```
So i don't understand why
`(?<!ZTE BLADE |ImSmart |ERGO |X-Style Tab )a(?:101|110|2[10]0|211|50[10]|51[10]|70[10])[);/ ]` 
shouldn't be valid. Or doesn't that apply for negativ look-behinds?

**Comment by spiderpug** [comment]
Thanks for the response. I apologise for the trouble but I was mislead by the error message. The regex is actually not the problem. 

This seems to be a bug in ruby https://bugs.ruby-lang.org/issues/13671 / or library Onigmo, see https://github.com/k-takata/Onigmo/issues/92 . 

It occurs in combination with `/.../i` (ignore case) and if the user agent contains non-latin characters, like specified in the tests, e.g.:

```
Versão/4.0
eZeeâ€™Tab
Build/Xperia Ultimate HDâ„¢ 3.0.2
Ramos X10 PROæ—¶å°šç‰ˆ
```

I think there is nothing to be done on your side. 👍

**Comment by sgiehl** [comment]
ok. Thanks for the feedback. Let me know if anything else needs to be adjusted...
