### ISSUE TITLE
Missing Client Short Name => Client Family

### ISSUE THREAD

**Issue by AdamWiley46** [matomo-org/device-detector#5976]
User Agent:-
Mozilla/5.0 (Linux; Android 8.0.0; SAMSUNG SM-G930F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Mobile Safari/537.36

Identifys as 
"Samsung Browser" with short name "SB" but comes up blank as Client Family

**Comment by Findus23** [comment]
Seems like it is missing in this list:
https://github.com/matomo-org/device-detector/blob/8bfdbafc07ef6ba1c3cfff3bbb0554a860828a39/Parser/Client/Browser.php#L209

And also here:
https://github.com/matomo-org/device-detector/blob/8bfdbafc07ef6ba1c3cfff3bbb0554a860828a39/Parser/Client/Browser.php#L226-L228
