### ISSUE TITLE
document getBrowserFamily and getOsFamily

### ISSUE THREAD

**Issue by Findus23** [matomo-org/device-detector#5977]
Thanks to #5976, I noticed that those were missing on my devicedetector website.
It seems like they are never mentioned apart from here:
https://github.com/matomo-org/device-detector/blob/92fa41434af96b762e6c25a8d2287fa2a79567d5/DeviceDetector.php#L816-L817

Is there any reason for that?
Otherwise they should probably be mentioned in the readme and maybe also get their own `$dd->getOsFamily()`

**Comment by sgiehl** [comment]
Guess it won't hurt to make those methods callable through DD directly and document them.

**Comment by Findus23** [comment]
The same is also true for `isMobileOnlyBrowser`

**Comment by Findus23** [comment]
@sgiehl I guess v4 would be a good time to add the new methods.
