### ISSUE TITLE
Might have a problem with Safari on Apple's new iPadOS 13

### ISSUE THREAD

**Issue by GregOriol** [matomo-org/device-detector#5978]
On Apple's new iPadOS 13, Safari has a new setting "request desktop website on all website" that is enabled **by default**. This makes Safari send a user agent as macOS 10.15 Safari `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15` on all request to all website by default. There doesn't seem to be any way to know it is an iPad with such a user agent, and that will break the detection...

Any ideas on how to handle this?

**Comment by sanchezzzhak** [comment]
We will also detect device type by agent, except when the user has switched to the full desktop version site.

**Comment by Findus23** [comment]
I have now updated to iOS 13 and can confirm this.

By default a website only get's the macOS useragent
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
```
https://devicedetector.lw1.at/Mozilla%2F5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15)%20AppleWebKit%2F605.1.15%20(KHTML,%20like%20Gecko)%20Version%2F13.0%20Safari%2F605.1.15

Only when one selects "request mobile website", the iOS user agent is sent.

```
Mozilla/5.0 (iPad; CPU OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1
```

https://devicedetector.lw1.at/Mozilla%2F5.0%20(iPad;%20CPU%20OS%2013_1%20like%20Mac%20OS%20X)%20AppleWebKit%2F605.1.15%20(KHTML,%20like%20Gecko)%20Version%2F13.0%20Mobile%2F15E148%20Safari%2F604.1

I doubt that anything can be done here as this is done intentionally by Apple.

**Comment by sgiehl** [comment]
@Findus23 are you able to check if the device sends any other additional headers that might make it possible to identify it?

**Comment by Findus23** [comment]
@sgiehl I checked the HTTP headers and there is nothing out of the ordinary.

Honestly I would be surprised as Apple did a lot of changes recently to make devices non-fingerprintable.
According to https://stackoverflow.com/questions/56578799/tell-ipados-from-macos-on-the-web the user agent is identical to safari on MacOS

**Comment by GregOriol** [comment]
I can confirm there doesn't seem to be any headers or other information that could help identify...

The only way I saw used on some other projects is in javascript to check for touch and screen size.... and it only helps to detect those cases, not to identify which iOS version it is.

**Comment by AgileFlexAgency** [comment]
We're confirming the issue with the .NET ported version  [https://github.com/AgileFlexAgency/MatomoDeviceDetector.NET] 

iPad + Safari + iOS 13.0 -> Mozilla/5.0 (iPad; CPU OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Mobile/15E148 Safari/604.1

Hopefully it will be fixed somehow without needing to add additional JS code into our projects.

**Comment by AgileFlexAgency** [comment]
Testing the .NET version [https://github.com/AgileFlexAgency/MatomoDeviceDetector.NET](url) on iPad + Safari + iOS 13.0 - works as expected if  "request desktop version on all websites" settings is diabled on iPad.

@GregOriol @Findus23 @sanchezzzhak @sgiehl - This issue can be closed as the implementation works as expected. Cheers.

**Comment by sgiehl** [comment]
Closing this one. As there is nothing we could do 🤷‍♂
