### ISSUE TITLE
HMD Global (Nokia)

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#5986]
Should we refer these devices to the Nokia brand?

HMD Global` `Nokia 5.1
* [x] Mozilla/5.0 (Linux; Android 8.0.0; Nokia 5.1 Build/O00623) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

HMD Global Nokia 6.1 Plus
* [x] Mozilla/5.0 (Linux; Android 8.1.0; Nokia 6.1 Plus Build/OPR1.170623.026) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

HMD Global Nokia 6
* [x] Mozilla/5.0 (Linux; Android 7.1.1; TA-1021 Build/NMF26F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/64.0.3282.137 Mobile Safari/537.36

Nokia 5 Dual sim
* [x] Mozilla/5.0 (Linux; Android 8.1.0; TA-1053 Build/OPR1.170623.026) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.126 Mobile Safari/537.36

Nokia X71
* [x] Mozilla/5.0 (Linux; Android 9; Nokia X71) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36

Nokia 8.1
* [x] Dalvik/2.1.0 (Linux; U; Android 9; Nokia 8.1 Build/PPR1.180610.011)

Nokia 8 Sirocco
* [x] Mozilla/5.0 (Linux; Android 9; Nokia 8 Sirocco Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.157 Mobile Safari/537.36

Nokia 9
* [x] Mozilla/5.0 (Linux; Android 8.0.0; TA-1004 Build/OPR6.170623.013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.111 Mobile Safari/537.36

Nokia 9 PureView  (Possible UserAgent)
* [x] Mozilla/5.0 (Linux; Android 8.1.0; Nokia 9 Pureview Build/OPM1.171019.026) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36

**Comment by sgiehl** [comment]
I would say we can simply refer them to the Nokia brand.
