### ISSUE TITLE
SHUTTLE PNT-7045  what type of devices does this apply to?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6002]
GPS Navigator
Brand SHUTTLE, model  PNT-7045
`
Mozilla/5.0 Linux; Android 8.1.0; PNT-7045 Build/O11019 AppleWebKit/537.36 KHTML, like Gecko Chrome/75.0.3770.89 Mobile Safari/537.36
`
Should we create a new type or used type `tablet` ?

**Comment by sgiehl** [comment]
good question. are there many similar devices of that type? If not I don't think it makes much sense to create a new device type :man_shrugging:

**Comment by Findus23** [comment]
Essentially it is just an android tablet with a navigation app preinstalled, so for simplicity I would categorize it as a tablet.
