### ISSUE TITLE
[Question] How to add test cases?

### ISSUE THREAD

**Issue by mimmi20** [matomo-org/device-detector#6006]
Do you have a document which describes how to generate test cases or a script which does it?

**Comment by sgiehl** [comment]
not directly. But I'm planning to make that a lot easier for V4. Before you can use the script https://github.com/matomo-org/device-detector/blob/master/misc/test.php, which prints a yml that can be pasted into one of the fixture files

**Comment by mimmi20** [comment]
Thanks
