### ISSUE TITLE
[Question] new script in misc folder

### ISSUE THREAD

**Issue by mimmi20** [matomo-org/device-detector#6016]
While changing/adding some browsers, I was missing a script to rewrite the test fixtures. Shall I create this script based on v4 or can I create this script based on the actual master?

**Comment by sgiehl** [comment]
sortTestFixtureFiles.php should actually do that for the big files when you pass `-f` on command line

**Comment by mimmi20** [comment]
That file actually only rewrites the files in the `Tests/fixtures` directory only, but not in the `Tests/Parser/(Client|Devices)/fixtures` or the `Tests/Parser/fixtures/ Folders. Additionally to that, that script writes the full result and not just the part tested in the other fixtures files, and that script sorts the results, what you complained in another PR.

If you add a new browser/app the other fixtures files may need a rewrite too.

I want to add a script that just take a fixture file, maybe redetect the uaseragent and write the result in the same format as it was before.
