### ISSUE TITLE
Xperia 10 Plus illegal detection

### ISSUE THREAD

**Issue by mchubar** [matomo-org/device-detector#6034]
Mozilla/5.0 (Linux; arm_64; Android 9; I4213) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 YaBrowser/19.7.5.90.00 Mobile Safari/537.36 is not detected

**Comment by mchubar** [comment]
Mozilla/5.0 (Linux; arm_64; Android 9; I4213) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 YaBrowser/19.7.5.90.00 Mobile Safari/537.36 is not detected(

**Comment by Findus23** [comment]
Hi,

It would be great if you could expand on what is not detected correctly. It looks fine to me:
https://devicedetector.lw1.at/Mozilla%2F5.0%20(Linux;%20arm_64;%20Android%209;%20I4213)%20AppleWebKit%2F537.36%20(KHTML,%20like%20Gecko)%20Chrome%2F75.0.3770.143%20YaBrowser%2F19.7.5.90.00%20Mobile%20Safari%2F537.36%20is%20not%20detected
```json
{
  "isBot": false,
  "clientInfo": {
    "type": "browser",
    "name": "Yandex Browser",
    "short_name": "YA",
    "version": "19.7.5.90.00",
    "engine": "Blink",
    "engine_version": ""
  },
  "browserFamily": false,
  "isMobileOnlyBrowser": false,
  "osInfo": {
    "name": "Android",
    "short_name": "AND",
    "version": "9",
    "platform": "ARM"
  },
  "osFamily": "Android",
  "device": 1,
  "deviceName": "smartphone",
  "deviceBrand": "Sony",
  "model": "Xperia 10 Plus",
  "icons": {
    "browser": "/icons/browsers/YA.png",
    "os": "/icons/os/AND.png",
    "device": "/icons/devices/smartphone.png",
    "brand": "/icons/brand/Sony.png"
  }
}
```

**Comment by mchubar** [comment]
sorry, updated via composer, looks good)

**Comment by mchubar** [comment]
no, actually from last version

Mozilla/5.0 (Linux; arm_64; Android 9; I4213) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 YaBrowser/19.7.5.90.00 Mobile Safari/537.36

device not detected

Mozilla/5.0 (Linux; arm_64; Android 9; H4213) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 YaBrowser/19.7.5.90.00 Mobile Safari/537.36

device detected as smartphone

idk what version uses your online service?

**Comment by Findus23** [comment]
As you can see in the footer it is using 1d44a3cc6a3539912a58dc0312765168924a1bd0 (so the latest commit on the master branch).
It's possible that the fix has been added since the last release.

**Comment by mchubar** [comment]
Thank you! Figured it now
