### ISSUE TITLE
Mistake in Dell Venue identified as tablet?

### ISSUE THREAD

**Issue by GregOriol** [matomo-org/device-detector#6058]
There is a user-agent we currently have in the tests as "Mozilla/5.0 (Linux; U; Android 2.2; fr-fr; Dell Venue Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1" that is identified as Dell Venue, and as a tablet.

However, from my memories, the "Dell Venue" from those Android 2.2 times was a phone. Does anyone else has information to verify this?

**Comment by sanchezzzhak** [comment]
https://www.youtube.com/watch?v=P6s4VNaw9x8
looks like a smartphone
