### ISSUE TITLE
Device type not detected

### ISSUE THREAD

**Issue by liviuconcioiu** [matomo-org/device-detector#6067]
Device type is not detected for those particular user agents. It should be seen as smartphone.

- [x] Mozilla/5.0 (Linux; U; Android 8.1.0; ASTRO Build/OPM2.171019.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/65.0.3325.109 Mobile Safari/537.36 OPR/35.0.2254.127759
- [x] Mozilla/5.0 (Linux; U; Android 7.0; en-US; E3 Dual Build/NRD90M) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/12.9.7.1153 (SpeedMode) U4/1.0 UCWEB/2.0 Mobile Safari/534.30
- [x] Mozilla/5.0 (Linux; Android 8.1.0; Hind 5.1 Build/OPM2.171019.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.73 Mobile Safari/537.36
- [x] Mozilla/5.0 (Linux; Android 6.0; ZL80 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.92 Mobile Safari/537.36
- [x] Mozilla/5.0 (Linux; U; Android 7.0; Mobicel_R1 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/59.0.3071.125 Mobile Safari/537.36 OPR/26.0.2254.117551

**Comment by angelofan** [comment]
Mozilla/5.0 (iPhone; CPU iPhone OS 14_0_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1

Now device type is null

**Comment by Findus23** [comment]
@angelofan 
I also don't see any part of that user agent that says anything about which device this could be (apart from an iPhone).

**Comment by angelofan** [comment]
Open https://lx3rzx16x9.codesandbox.io/ on my phone, the device type is `null`

I copied the user agent on the phone to the computer, the device type is `smartphone`

**Comment by angelofan** [comment]
@Findus23 
At least "Mobile" is included in the user agent. Doesn't it mean that it is a smartphone?

**Comment by angelofan** [comment]
in phone:
```
"device":{
  "type":"",
  "brand":"Apple",
  "model":"",
}
```

in pc:
```
"device":{
  "type":"smartphone",
  "brand":"Apple",
  "model":"iPhone",
}
```

Why are they different?

**Comment by Findus23** [comment]
Hi,

https://lx3rzx16x9.codesandbox.io/ uses https://github.com/etienne-martin/device-detector-js which is an implementation in JS that only shares the rules list.

The PHP version detects a "deviceName" of "smartphone":

https://devicedetector.lw1.at/Mozilla%2F5.0%20(iPhone;%20CPU%20iPhone%20OS%2014_0_1%20like%20Mac%20OS%20X)%20AppleWebKit%2F605.1.15%20(KHTML,%20like%20Gecko)%20Version%2F14.0%20Mobile%2F15E148%20Safari%2F604.1

In case this is a bug with the JS implementation, I'd recommend you to open an issue there.

**Comment by etienne-martin** [comment]
Thank you @Findus23, the inconsistency is due to Safari not supporting the lookbehind syntax for regexes as mentioned here in the readme: https://github.com/etienne-martin/device-detector-js#%EF%B8%8F-browser-environment

**Comment by angelofan** [comment]
It seems I have to integrate the device-detector into my server.

**Comment by sanchezzzhak** [comment]
do you have any ideas about what brand the ZL80 smartphone has?

**Comment by liviuconcioiu** [comment]
I think is a car tablet made by Alps (Alps Alpine [https://www.alpsalpine.com/e/](https://www.alpsalpine.com/e/)), but also BDF sells the exact same model under their brand. If you go to [http://specdevice.com/showspec.php?id=6ae3-d410-0406-6a000033c587](http://specdevice.com/showspec.php?id=6ae3-d410-0406-6a000033c587) and click on OS details, you will see `FINGERPRINT: alps/full_flycom6580_we_m/flycom6580_we_m:6.0/MRA58K/1553934260:user/test-keys`
