### ISSUE TITLE
What brand of device is "Roadrover ChangAn S"  Subaru or ChangAn?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6074]
`
Mozilla/5.0 (Linux; U; Android 4.1.1; ru-ru; Roadrover ChangAn S Build/JRO03C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
`
Looks like a tablet

Brand ??? Subaru or ChangeAn
Model: Roadrover ChangAn S

**Comment by liviuconcioiu** [comment]
Manufacturer: Roadrover
Model: ChangAn S

Is a Android headunit.

**Comment by mattab** [comment]
The issue was fixed in your fork but not in our project maybe?
