### ISSUE TITLE
Liebao browser not found in $availableBrowsers

### ISSUE THREAD

**Issue by clickervolt** [matomo-org/device-detector#6077]
Hello,

With the latest version I have this error popping up for some user agents:

`Detected browser name "Liebao" was not found in $availableBrowsers.`

Looks like an entry is missing in that array.

**Comment by clickervolt** [comment]
![image](https://user-images.githubusercontent.com/49594001/67667841-31ed1400-f988-11e9-9f53-791007327572.png)

**Comment by sgiehl** [comment]
Thanks for the report. will check that immediately.

**Comment by sgiehl** [comment]
No. The browsername Liebao shouldn't be detected at all. Maybe your files do not all have the latest version. Would you mind checking your useragent at https://devicedetector.lw1.at

**Comment by clickervolt** [comment]
It's not my own user agent, rather a user reported this to me. But here it is:

`Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; LBBROWSER)`

**Comment by sgiehl** [comment]
Works as expected on my machine with latest release. Also works here: https://devicedetector.lw1.at/Mozilla%2F4.0%20(compatible;%20MSIE%208.0;%20Windows%20NT%205.1;%20WOW64;%20Trident%2F4.0;%20SLCC2;%20.NET%20CLR%202.0.50727;%20LBBROWSER)

**Comment by clickervolt** [comment]
Thanks for checking, I will see with the user if he has really updated to the latest version.

**Comment by clickervolt** [comment]
Closing this one, issue was fixed after user updated. Thanks!
