### ISSUE TITLE
New device types

### ISSUE THREAD

**Issue by liviuconcioiu** [matomo-org/device-detector#6089]
I'm looking to add a few more device types, but before I do this I want to know if the new types are okay.

`DEVICE_TYPE_WEARABLE` will include watches and headsets, or should I make different device types?
`DEVICE_TYPE_APPLIANCE` will include refrigerators (I have 1 user agent so far)
`DEVICE_TYPE_PRINTER` will include printers
`DEVICE_TYPE_SIGNAGE` will include signages

**Comment by Findus23** [comment]
Hi,

I think the first three should be pretty straightforward to convey to people with just a word and an icon. But I'm not so sure about Signage. Do you have an example device?

**Comment by liviuconcioiu** [comment]
```
BrightSign/4.6.46 (XD230) Mozilla/5.0 (compatible; Linux mips) AppleWebKit/537.4 (KHTML, like Gecko) Chromium/18.0.1025.168 Chrome/18.0.1025.168 Safari/537.4
BrightSign/5.1.52 (SV-4K-ROW) Mozilla/5.0 (compatible; Linux mips) AppleWebKit/537.4 (KHTML, like Gecko) Chromium/18.0.1025.168 Chrome/18.0.1025.168 Safari/537.4
```

**Comment by sgiehl** [comment]
@liviuconcioiu  I think those useragents are from products from https://www.brightsign.biz
Seem to be some media players, video decoders and stuff like that.

**Comment by liviuconcioiu** [comment]
There are media players, specially designed for digital signs
[https://web.archive.org/web/20140225051220/http://www.brightsign.biz/files/9613/4761/4892/HD2000PressRelease.pdf
](url) and [https://github.com/smart-ecommerce/prestashop/blob/master/creditagricolepaymentgateway/vendor/whichbrowser/parser/tests/data/signage/other.yaml](url)

So how should we classify them? Media players?

**Comment by sanchezzzhak** [comment]
is this issue still relevant?

**Comment by sgiehl** [comment]
Guess we can close it. If we need new device types again, we can discuss that in a new issue or PR at any time.
