### ISSUE TITLE
AIS should be listed in the deviceBrands array

### ISSUE THREAD

**Issue by sleptor** [matomo-org/device-detector#6091]
Recently it's started appearing in my logs.

Error:
The brand with name 'AIS' should be listed in the deviceBrands array.

User-agent sample:
```
Mozilla/5.0 (Linux; Android 4.4.2; iris708 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36
```

**Comment by Findus23** [comment]
I can reproduce this.

Seems like adding it has been forgotten in https://github.com/matomo-org/device-detector/pull/6065

Seems like there is also no test for this.
