### ISSUE TITLE
'AIS' regex exists, but no vendor

### ISSUE THREAD

**Issue by mchubar** [matomo-org/device-detector#6099]
The brand with name 'AIS' should be listed in the deviceBrands array. Tried to parse user agent: Mozilla/5.0 (Linux; Android 4.4.2; iris708 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36

**Comment by Findus23** [comment]
Hi,

This sounds a lot like https://github.com/matomo-org/device-detector/issues/6091

**Comment by mchubar** [comment]
Yes! Any chance it will be released soon?
