### ISSUE TITLE
Devices are not detected

### ISSUE THREAD

**Issue by loganfan** [matomo-org/device-detector#6100]
Hi
here are the device/http_agent can't be detected:
Apache-HttpClient/4.3.1 (java 1.5)

HTTPClient/1.0 (2.8.0, ruby 2.0.0 (2014-05-08))

Java/1.8.0_152 :heavy_check_mark: 

Java/1.8.0_181-b13  :heavy_check_mark: 

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.0 Chrome/67.0.3396.87 Safari/537.36 :heavy_check_mark: 

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Safari/537.36 :heavy_check_mark: 

SalesforceMobileSDK/6.2.0 android mobile/8.1.0 (9027W) Salesforce1/18.2(18020200) Native uid_f80397e758d797e9 ftr_AI.GS.PN.UA.US Cordova/7.0.0 XBranding/1.0 SalesforceTouchContainer/2.0 SalesforceMobileSDK/6.2.0 android mobile/8.1.0 (9027W) Salesforce1/18 

SalesforceMobileSDK/6.2.0 android mobile/8.1.0 (REVVL 2) Salesforce1/18.1(18010000) Native uid_112629018cb13217 ftr_AI.GS.PN.UA.US Cordova/7.0.0 XBranding/1.0 SalesforceTouchContainer/2.0 SalesforceMobileSDK/6.2.0 android mobile/8.1.0 (REVVL 2) Salesforce   :heavy_check_mark: 

SalesforceMobileSDK/6.2.0 android mobile/9 (Pixel) Salesforce1/18.2(18020200) Native uid_a38c809e1236c0d4 ftr_AI.GS.PN.UA.US Cordova/7.0.0 XBranding/1.0 SalesforceTouchContainer/2.0 SalesforceMobileSDK/6.2.0 android mobile/9 (Pixel) Salesforce1/18.2(18020  :heavy_check_mark: 

SalesforceMobileSDK/7.0.0 android mobile/7.1.2 (LM-X210VPP) Salesforce1/220.3(220030100) Native uid_2c1d2536f9ff066f ftr_AI.GS.PN.UA.US Cordova/7.1.2 Hybrid SalesforceMobileSDK/7.0.0 android mobile/7.1.2 (LM-X210VPP) Salesforce1/220.3(220030100) Native ui  :heavy_check_mark:

**Comment by sanchezzzhak** [comment]
`SalesforceMobileSDK/6.2.0 android mobile/8.1.0 (9027W) Salesforce1/18.2(18020200) Native uid_f80397e758d797e9 ftr_AI.GS.PN.UA.US Cordova/7.0.0 XBranding/1.0 SalesforceTouchContainer/2.0 SalesforceMobileSDK/6.2.0 android mobile/8.1.0 (9027W) Salesforce1/18
` 
or 
`Mozilla/5.0 (Linux; Android 8.1.0; 9027W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Mobile Safari/537.36`

It is difficult to determine the model of this device. I think it's **ALCATEL**  **3T 8 9027W** T-MOBILE (tablet)

Other devices are defined or do not contain information to detect;

**Comment by sgiehl** [comment]
As @sanchezzzhak mentioned: `9027W`  is hard to determine. All others should be detected correctly meanwhile...
