### ISSUE TITLE
Can't detect mobile safari browser version

### ISSUE THREAD

**Issue by tshahmuratov** [matomo-org/device-detector#6140]
Incoming UA

Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G36 [FBAN/FBIOS;FBDV/iPad2,4;FBMD/iPad;FBSN/iPhone OS;FBSV/9.3.5;FBSS/1;FBID/tablet;FBLC/pt_PT;FBOP/5;FBCR/]

Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone6,2;FBMD/iPhone;FBSN/iOS;FBSV/12.4.3;FBSS/2;FBID/phone;FBLC/pt_PT;FBOP/5;FBCR/NOS]

Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_4 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G61 [FBAN/FBIOS;FBDV/iPhone5,1;FBMD/iPhone;FBSN/iOS;FBSV/10.3.4;FBSS/2;FBID/phone;FBLC/pt_PT;FBOP/5;FBCR/MEO]

Mozilla/5.0 (iPad; CPU OS 10_3_4 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G61 [FBAN/FBIOS;FBDV/iPad3,6;FBMD/iPad;FBSN/iOS;FBSV/10.3.4;FBSS/2;FBID/tablet;FBLC/pt_PT;FBOP/5;FBCR/MEO]

Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone8,4;FBMD/iPhone;FBSN/iOS;FBSV/13.1.3;FBSS/2;FBID/phone;FBLC/pt_PT;FBOP/5;FBCR/MEO]

Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone10,5;FBMD/iPhone;FBSN/iOS;FBSV/13.1.2;FBSS/3;FBID/phone;FBLC/pt_PT;FBOP/5;FBCR/MEO]

Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone8,4;FBMD/iPhone;FBSN/iOS;FBSV/13.2.3;FBSS/2;FBID/phone;FBLC/pt_PT;FBOP/5;FBCR/vodafone P]

Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G36 [FBAN/FBIOS;FBDV/iPad3,1;FBMD/iPad;FBSN/iPhone OS;FBSV/9.3.5;FBSS/2;FBID/tablet;FBLC/pt_PT;FBOP/5;FBCR/]

I think we should take version from AppleWebKit/605.1.15

**Comment by sgiehl** [comment]
Actually I guess all of them are actually not a browser. All seem to be useragents from the Facebook App on iOS
