### ISSUE TITLE
Abandoned projects in composer.json

### ISSUE THREAD

**Issue by ShinJii89** [matomo-org/device-detector#6151]
> Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
> Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

**Comment by sgiehl** [comment]
Those packages are used for tests only and their usage will be removed with the next major release. See https://github.com/matomo-org/device-detector/pull/6014
