### ISSUE TITLE
Breaking changes between 3.11.8 and 3.12.2

### ISSUE THREAD

**Issue by webmake** [matomo-org/device-detector#6152]
Hello,

I wanted to update package [from 3.11.8 up to 3.12.2](https://github.com/matomo-org/device-detector/compare/3.11.8..3.12.2) but noticed by already parsed UA database, 570 missmatches, and for example
`Mozilla/5.0 (Linux; Android 6.0.1) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Web Explorer/2.6.1 Chrome/74.0.3729.157 Mobile Safari/537.36`
on 3.11.8 `getDeviceName()` was `smartphone`
now on 3.12.2 `getDeviceName()` gives `""`

another sample:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Safari/537.36` 
on 3.11.8 `getDeviceName()` was  `desktop`
now on 3.12.2 `getDeviceName()` gives `""`

`Mozilla/5.0 (Linux; Android 8.1.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/72.0.3626.76 Mobile Safari/537.36`
on 3.11.8 `getDeviceName()` was  `smartphone`
now on 3.12.2 `getDeviceName()` gives `""`

This is pairs how changed:
```
-'smartphone' (old)
+'phablet' (new)

-'' (old)
+'smartphone' (new)

-'smartphone' (old)
+'tablet' (new)

-'tablet' (old)
+'phablet' (new)

-'tablet' (old)
+'' (new)

-'smartphone' (old)
+'' (new)

-'tablet' (old)
+'smartphone' (new)

-'phablet' (old)
+'smartphone' (new)

-'desktop' (old)
+'' (new)

-'' (old)
+'desktop' (new)

-'' (old)
+'console' (new)
```
I dont't worry about `smartphone` ->`tablet` and similar conversions, neither about empty which will be filled after upgrade, but worried about resets such as
`'tablet' (old) -> '' (new)`
`'smartphone' (old) ->'' (new)`
`'desktop' (old) -> '' (new)`

If you need additional samples, I can attach

**Comment by sgiehl** [comment]
I assume all changed device actually don't have a detected device, right?
I think that's caused by the new browser detections that were added. I'll prepare a PR to improve that.
Maybe you can check if that fixes your issues...

**Comment by webmake** [comment]
Hello,
from first sight it looks better, out of these total 570 failed now it left only 375,
it was 217 empty devices, now it left 22. I provide unique cases which left:

`Mozilla/5.0 (Linux; Android 7.0; iQS300 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.92 Mobile Safari/537.36 Instagram 111.1.0.25.152 Android (24/7.0; 272dpi; 720x1198; MLS; iQS300; iQS300; mt6735; el_GR; 173238729)`
`smartphone` -> `''`
`Mozilla/5.0 (Linux; Android 7.0; Young Y56 Build/LMY47I) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36 Instagram 104.0.0.21.118 Android (22/7.0; 240dpi; 480x854; Young Y56/v.mobile; V10-Y; l3_tm_v2_648_b1b8_v10_fwvga; mt6580; es_ES; 165030894)`
`smartphone` -> `''`
`Mozilla/5.0 (Linux; Android 8.1.0; 5052Y Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.93 Mobile Safari/537.36 Instagram 123.0.0.21.114 Android (27/8.1.0; 320dpi; 720x1352; TCL; 5052Y; A3A; mt6739; es_ES; 188791643)`
`smartphone` -> `''`
`Mozilla/5.0 (Linux; Android 8.1.0; S60Lite Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36 Instagram 121.0.0.29.119 Android (27/8.1.0; 480dpi; 1080x1776; DOOGEE; S60Lite; S60Lite; mt6755; fr_FR; 185203705)`
`smartphone` -> `''`
`Mozilla/5.0 (Linux; Android 8.1.0; W_C200SN Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36 Instagram 121.0.0.29.119 Android (27/8.1.0; 240dpi; 480x888; WIKO; W_C200SN; W_C200SN; mt6739; fr_FR; 185203686)`
`smartphone` -> `''`
`Mozilla/5.0 (Linux; Android 9; Phone 2 Build/P-MR2-RC001-RZR-190914; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.92 Mobile Safari/537.36 Instagram 112.0.0.29.121 Android (28/9; 480dpi; 1440x2416; Razer/razer; Phone 2; aura; qcom; de_DE; 174081672)`
`smartphone` -> `''`
`Mozilla/5.0 (Linux; Android 9; W-V720-EEA Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36 Instagram 122.0.0.16.238 Android (28/9; 320dpi; 720x1344; WIKO; W-V720-EEA; W-V720; v720; es_US; 187029244)`
`smartphone` -> `''`
`Mozilla/5.0 (Linux; diordnA 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/8.0.15 Chrome/76.0.3809.111 eliboM Safari/537.36`
`desktop` -> `''`
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 DuckDuckGo/7`
`desktop` -> `''`
`Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/75.0.3770.101 Safari/537.36 DuckDuckGo/5`
`desktop` -> `''`
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/10.1 Chrome/71.0.3578.99 Safari/537.36`
`desktop` -> `''`

**Comment by sgiehl** [comment]
Those including `DuckDuckGo` and `SamsungBrowser` should be correct, as those browsers are afaik only available for iOS/Anroid

> Mozilla/5.0 (Linux; diordnA 9) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Focus/8.0.15 Chrome/76.0.3809.111 eliboM Safari/537.36

That one is correct too. Wondering why `Android` and `Mobile` are written reverse here 🤔 

And for the first ones including `Instagram`, the fix doesn't work. Need to think about a solution for them....

**Comment by webmake** [comment]
https://github.com/delight-im/Android-AdvancedWebView/blob/221256a25cc72ebb57ee7a08e8c138df988ee03d/Source/library/src/main/java/im/delight/android/webview/AdvancedWebView.java#L406
maybe due this could explain, that it is mobile with desktop version

What do you mean by
> Those including DuckDuckGo and SamsungBrowser should be correct, as those browsers are afaik only available for iOS/Anroid
This gives empty :/ not smartphone

**Comment by sgiehl** [comment]
Well `desktop` was incorrect. And it can't be detected which device type it actually is (might be smartphone, phablet, tablet,...). But `isMobile` should return `true` for them
