### ISSUE TITLE
Missing double quote in one of the yaml test file

### ISSUE THREAD

**Issue by etienne-martin** [matomo-org/device-detector#6161]
Since version 3.12.3, we're no longer able to update the [javascript version of device-detector](https://github.com/etienne-martin/device-detector-js) because a typo was introduced in one of the test file.

The culprit is [line 1067](https://github.com/matomo-org/device-detector/blob/22257883bd2c7c21d68112a907cdad7de4a2ba31/Tests/Parser/fixtures/oss.yml#L1067) of `/Tests/Parser/fixtures/oss.yml`.

There's a missing double quote and the yaml parser we're using is choking on it.

Here's the related issue: https://github.com/etienne-martin/device-detector-js/issues/74

**Comment by whimsicaldreamer** [comment]
Will any patch version be released so that we can update our javascript version to to 3.12.3?

**Comment by etienne-martin** [comment]
@whimsicaldreamer No need for a patch, we'll fix it on our side in the meantime.
