### ISSUE TITLE
Tesla Car Browser detected incorrectly

### ISSUE THREAD

**Issue by rickbassham** [matomo-org/device-detector#6164]
User-Agent: `Mozilla/5.0 (X11; GNU/Linux) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/75.0.3770.100 Chrome/75.0.3770.100 Safari/537.36 Tesla/2019.40.50.7-ad132c7b057e`

Currently it is detected as a ComTrade Tesla `mobile`, but should be a Tesla `car browser`.

**Comment by Findus23** [comment]
Seems like the regex for Tesla cars looks for a QtCarBrowser and not for Chrome.

https://github.com/matomo-org/device-detector/blob/7adf89bf23914a80098ee08da6f68e76bd5f79b9/regexes/device/car_browsers.yml

**Comment by rickbassham** [comment]
The Tesla firmware 2019.12, released in April 2019 changed the browser from QtCarBrowser to a Chromium based browser.
