### ISSUE TITLE
How to detect same model name but different brands in mobile 

### ISSUE THREAD

**Issue by Wickky** [matomo-org/device-detector#6166]
First of all! This is such a great repo!
I am using python version of device-detector.
I would like to get all brands (multiple case) which has same model name.  
It is written for the first match case in the python version.
Can anyone help me to do this?
Thank you so much in advance!

**Comment by sgiehl** [comment]
I'm not sure what exactly you mean. If a model can't be detected as the model name is used by multiple brands it would be better not to detect it at all.
Do you have an example?

**Comment by Wickky** [comment]
sure! For example, if I want to detect the following mesage, 
**text = 'Note 7'**
I want outputs like this. 
**output_brands = 'SM galaxy Note 7', 'Xiaomi Note 7'.** 
Both Samsung and Xiaomi has the same model name: Note 7.
I want to extract all possible brand names from it's model name.

**Comment by Findus23** [comment]
Hi,

I think you might be quicker if you just parse the `regexes/device/mobiles.yml` yourself in your favourite programming language.

And the data you want isn't even in devicedetector as for example Device Detector doesn't know about a Xiaomi Note 7.

It just takes the number that occurs in the user agent. So if you parse this user agent
`Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0 Xiaomi Note 3.1415926535`

it will detect it as a [` Xiaomi Note 3.1415926535 `](https://devicedetector.lw1.at/Mozilla%2F5.0%20(X11;%20Linux%20x86_64;%20rv:72.0)%20Gecko%2F20100101%20Firefox%2F72.0%20Xiaomi%20Note%203.1415926535) without knowing which phones really exist.

**Comment by Wickky** [comment]
> Hi,
> 
> I think you might be quicker if you just parse the `regexes/device/mobiles.yml` yourself in your favourite programming language.
> 
> And the data you want isn't even in devicedetector as for example Device Detector doesn't know about a Xiaomi Note 7.
> 
> It just takes the number that occurs in the user agent. So if you parse this user agent
> `Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0 Xiaomi Note 3.1415926535`
> 
> it will detect it as a [`Xiaomi Note 3.1415926535`](https://devicedetector.lw1.at/Mozilla%2F5.0%20(X11;%20Linux%20x86_64;%20rv:72.0)%20Gecko%2F20100101%20Firefox%2F72.0%20Xiaomi%20Note%203.1415926535) without knowing which phones really exist.

Yeah actually, I have already edited the yaml file. For example,
# Xiaomi
Xiaomi:
  regex: 'mi|xiaomi|note\s*7'
  device: 'phone'
  models: 
    - regex: 'note\s*7'
      model: 'Mi Note 7'

# Samsung
Samsung:
  regex: 'sm|samsung|note\s*7'
  device: 'phone'
  models:
    - regex: 'note\s*7'
      model: 'Galaxy Note 7'

# vivo
Vivo:
  regex: 'vivo'
  device: 'phone'
  models:
    - regex: 'vivo f11'
      model: 'vivo F11 pro'
 
By using this yaml file, I would like to extract 'Note 7' as both 'Galaxy Note 7' and 'Mi Note 7'.

**Comment by mimmi20** [comment]
> By using this yaml file, I would like to extract 'Note 7' as both 'Galaxy Note 7' and 'Mi Note 7'.

Do you an useragent for this?

**Comment by Wickky** [comment]
> > By using this yaml file, I would like to extract 'Note 7' as both 'Galaxy Note 7' and 'Mi Note 7'.
> 
> Do you an useragent for this?

yeah The user agent might be sth like 'Note 7' only.

**Comment by sgiehl** [comment]
In that case it should not be detected at all as it would be ambiguous
