### ISSUE TITLE
Google-HTTP-Java-Client is detected as a bot - correctly?

### ISSUE THREAD

**Issue by andre-kornetzky** [matomo-org/device-detector#6169]
I have discovered that the following test user agent is recognized as a bot:

`Google-HTTP-Java-Client/1.17.0-rc (gzip)`
/Tests/Parser/Client/fixtures/library.yml, line 105

This is due to the following regular expression:

`Googlebot(-Mobile|-Image|-Video|-News)?|Feedfetcher-Google|Google Web Preview|AdsBot-Google(-Mobile)?|APIs-Google|Mediapartners-Google|Google.*/\+/web/snippet|GoogleProducer|Google[ -]Publisher[ -]Plugin|Google-(AMPHTML|Test|Site-Verification|Shopping-Quality|Adwords-DisplayAds|Assess|AdWords-Express|Adwords-Instant|speakr|Read-Aloud|Youtube-Links|HotelAdsVerifier)?`
/regexes/bots.yml, line 628

Especially the last part of the query: (...|**Google-**(...)**?**)

But if I understand it correctly, it is a public Java library provided by Google.

Thank you for your great job.
André Kornetzky

**Comment by andre-kornetzky** [comment]
Perhaps it makes sense to check that all non-BOT useragents are not recognized as BOT?

A major problem is the early "return" in line 589 in the main "parse" method when the bot was recognized.

**Comment by sgiehl** [comment]
thanks for the report. Will check how that can be improved.

**Comment by andre-kornetzky** [comment]
I think this line will solve the issue:

`- regex: 'AdsBot-Google(-Mobile)?|Adwords-(DisplayAds|Express|Instant)|Google Web Preview|Google[ -]Publisher[ -]Plugin|Google-(Adwords|AMPHTML|Assess|HotelAdsVerifier|Read-Aloud|Shopping-Quality|Site-Verification|speakr|Test|Youtube-Links)|(APIs|DuplexWeb|Feedfetcher|Mediapartners)-Google|Googlebot(-Mobile|-Image|-Video|-News)?|GoogleProducer|Google.*/\+/web/snippet'`

**Comment by sgiehl** [comment]
cheers @andre-kornetzky. Will try that
