### ISSUE TITLE
Problem detecting Twitter App on iOS

### ISSUE THREAD

**Issue by mwebber92** [matomo-org/device-detector#6170]
Hi
I recently started integrating this device detector and noticed that its not detecting twitter app for iOS.

here is user agents with which i tested:
https://developers.whatismybrowser.com/useragents/explore/software_name/twitter-app/11

Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 Twitter for iPhone

Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.2.10 (KHTML, like Gecko) Mobile/15A372 Twitter for iPhone/7.52

None of them are detected as twitter app, and are returned only as safari browser without version.

is there a way to fix this?

**Comment by sanchezzzhak** [comment]
close this issue
