### ISSUE TITLE
Brand Vinga what type does this apply to "portable media player" or "smart tv" or new type?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6172]
official site https://vinga.ua/mediapleery.html
review model VMP-041-162  https://ru.gecid.com/mmedia/vinga_041/

they position themselves as an android player
https://ru.gecid.com/data/mmedia/201708220800-49346/img/11_vinga_041.jpg

useragents 
```
Mozilla/5.0 (Linux; arm; Android 6.0.1; VMP-041-162) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 YaBrowser/19.7.2.90.01 Safari/537.36
Mozilla/5.0 (Linux; Android 6.0.1; VMP-021-82) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.136 Safari/537.36
Mozilla/5.0 (Linux; Android 5.1.1; VMP-011-81) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Safari/537.36
```

**Comment by sgiehl** [comment]
Guess those are kind of a set top boxes, that are useless without a tv (or another display), so I would suggest to count them as tv

**Comment by sanchezzzhak** [comment]
thanks
