### ISSUE TITLE
In-App browser useragents have empty engine field

### ISSUE THREAD

**Issue by Cestis** [matomo-org/device-detector#6177]
A few examples:
`Mozilla/5.0 (Linux; Android 9; LM-V405 Build/PKQ1.190202.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.136 Mobile Safari/537.36 JsSdk/2 NewsArticle/4.4.3 NetType/4G`

`Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.87 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/256.0.0.39.117;]`

`Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/93.2.294114169 Mobile/15E148 Safari/604.1`

Will you fix this? Or do you know how can I define the engine of these user agents?

**Comment by sgiehl** [comment]
The engine is actually only detected for browsers. So when a mobile app is detected, it skips the engine detection. For most apps that might not even make much sense...

**Comment by Cestis** [comment]
But why? Could you provide me an example of mobile app engine detection not making sense?

For example, for iOS, every in-app browser is just a safari instance = WebKit engine.
For Android, most of the time, it will be the system built in browser, which depending on Android version has WebKit/Blink engine.

**Comment by RikudouSage** [comment]
Just to add, it doesn't have to be just WebKit/Blink, I have Firefox as the rendering engine.

**Comment by sanchezzzhak** [comment]
The answer was given above. We are not planning to add an engine for applications yet. issue close.
