### ISSUE TITLE
Hbbtv class improvements

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6180]
I suggest adding a General regular rule for device type tv
```php 
 $regex = '(HbbTV/([1-9]{1}(?:\.[0-9]{1}){1,2})|AndroidTV|Android[ _-]TV|TV[ _-](?:BOX|SMART)|SMART[ _-]TV)[/;) ]';
```
Also clear the main mobile.yml from TV, from those rules that match the General template above.

**Comment by sgiehl** [comment]
Guess that makes sense. Could you create a PR for that?

**Comment by sanchezzzhak** [comment]
okey
