### ISSUE TITLE
iPhone OS 12_4 is not browser

### ISSUE THREAD

**Issue by Falseclock** [matomo-org/device-detector#6182]
```php
    /**
     * Current version number of DeviceDetector
     */
    const VERSION = '3.12.2';
```

`Mozilla/5.0 (iPhone; CPU iPhone OS 12_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) GSA/95.0.296015020 Mobile/15E148 Safari/605.1`

library is recognize it is mobile but not browser

**Comment by sgiehl** [comment]
correct. the `GSA` indicates the usage of the Google Search App and so it's detected as `mobile app`
