### ISSUE TITLE
Car tablet CarPad

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6185]
* [x] Mozilla/5.0 (Linux; Android 4.4.2; CarPad-II-P Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36
* [x] Mozilla/5.0 (Linux; Android 4.4.2; CarPad-III-P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Safari/537.36

<img src="https://cs6-1.4pda.to/5521678.jpg">

Brand Newsmy

To me it looks like a car type device

Why do you think?
device type car or tablet?

Official site http://www.newsmy-car.com/

Model range:
NM5002-H-HO, NM3002-H-HO  -----
Newsmy Carpad 4 NM 7101 - adaptive for Volkswagen Passat B7
Newsmy Carpad 4 NM 7111 - adaptive for Skoda Octavia A7
Newsmy Carpad 4 NM 9038 - adaptive for Volkswagen Polo
Newsmy Carpad 4 NM 9040 - adaptive for Volkswagen Tiguan 2011+
Newsmy Carpad 4 NM 9051 - adaptive for HYUNDAI SOLARIS
Newsmy Carpad 4 NM 9053 - adaptive for KIA RIO
Newsmy Carpad 4 NM 9054 - adaptive for KIA-Cerato

**Comment by Findus23** [comment]
I'd go with car, but it's pretty subjective.

**Comment by sgiehl** [comment]
I'd go with car as well, as it seems to be a permanently installed device and not a "mobile" device that can be taken away...
