### ISSUE TITLE
Panasonic Lumix DMC-CM1

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6186]
What type of device is this ?

user agents
-
* [x] Mozilla/5.0 (Linux; Android 5.0.2; DMC-CM1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Mobile Safari/537.36
* [x] Mozilla/5.0 (Linux; Android 5.0.2; DMC-CM1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36

device preview
-
![image](https://user-images.githubusercontent.com/1337066/76221768-9c616b00-622a-11ea-9b67-c48f4b5bb50b.png)

**Comment by Findus23** [comment]
I'd argue it is a camera:
https://github.com/matomo-org/device-detector/blob/master/regexes/device/cameras.yml

**Comment by sanchezzzhak** [comment]
I didn't even notice it.)) Thx
