### ISSUE TITLE
No site monitors recognition?

### ISSUE THREAD

**Issue by Cestis** [matomo-org/device-detector#6187]
Here's the list of site monitors:
https://developers.whatismybrowser.com/useragents/explore/software_type_specific/site-monitor/

Why aren't they marked as bots or some kind of separated device type?

In addition, some of them are detected as legit devices (this is marked as iPhone!)
```Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.1 RuxitSynthetic/1.0 v299304995 t7997095409838125115```

**Comment by sgiehl** [comment]
Some of those should be detected as bots. See https://github.com/matomo-org/device-detector/blob/master/regexes/bots.yml for a full list.
If you are missing any feel free to create specific issues or maybe even a PR to add it.
