### ISSUE TITLE
Support on Internet Explorer

### ISSUE THREAD

**Issue by huynhkhai6678** [matomo-org/device-detector#6204]
Currently we face "Syntax error" on IE11.
The problem maybe cause by arrow function (ES6 feature) is not support on IE.
Note :
Demo link : https://lx3rzx16x9.codesandbox.io/ is also crack on IE 11

**Comment by Findus23** [comment]
Hi,

This is the repository of the PHP device detector. You probably wanted to report this here: https://github.com/etienne-martin/device-detector-js
