### ISSUE TITLE
this is the first time I get a cash register user agent, so what type of devices is it?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6213]
What type of device to use in motamo?

* [x] Mozilla/5.0 (Linux; Android 7.0; SHTRIH-SMARTPOS-F2 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.91 Mobile Safari/537.36

<details>
  <summary>Preview</summary>
 
![image](https://user-images.githubusercontent.com/1337066/78004606-00b3ae00-7343-11ea-8508-1f79fad8452b.png)

</details>

**Comment by sgiehl** [comment]
Good question. At some point it might maybe be good to add a new type `Other devices` maybe?
Guess there will be other devices coming up like refrigerators, microwaves, hoovers and stuff like that. Or should we add new device types for each of them? 🤔

**Comment by sanchezzzhak** [comment]
The type of refrigerator is a sacred thing :D

**Comment by sanchezzzhak** [comment]
Can `DEVICE_TYPE_PERIPHERAL` ? 
this will include the following types of devices: printer/copier/scanner, cash register

**Comment by sgiehl** [comment]
Yes. Guess `DEVICE_TYPE_PERIPHERAL` would be fine for those devices.

**Comment by liviuconcioiu** [comment]
I think printers should be excluded from DEVICE_TYPE_PERIPHERAL. @sanchezzzhak check #6089

**Comment by sanchezzzhak** [comment]
There is another strange device mobile projector

* [ ] Mozilla/5.0 (Linux; Android 5.1.1; XGIMI TV Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.92 Safari/537.36

Site: https://www.xgimi.com/
Model: CC Aurora
<details>
  <summary>Preview</summary>

![image](https://user-images.githubusercontent.com/1337066/78083555-7c067580-73be-11ea-8ab2-3bee4b84746c.png)

</details>

**Comment by liviuconcioiu** [comment]
I think that now is okay to add printers to DEVICE_TYPE_PERIPHERAL, the same applies to mobile projectors. Basically printers, projectors, scanners, point of sale devices can be added here. The word might be misleading, if you read this page [https://en.wikipedia.org/wiki/Peripheral](https://en.wikipedia.org/wiki/Peripheral) but I think is fine.
