### ISSUE TITLE
What type of device to use in motamo? if the device is a smartwatch

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6215]
Do I need to add a new type and which one?

* [x] Mozilla/5.0 (Linux; Android 8.0; LEO-BX9 Build/OWDD.180926.001.A1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Cr4 Mobile Safari/537.36
* Huawei Smart Watch 2
![image](https://user-images.githubusercontent.com/1337066/78014767-162fd480-7351-11ea-81f9-95661550f2ff.png)

**Comment by sgiehl** [comment]
Guess that needs a new type `smart watch` 🤷‍♂ 
Guess we could add detection for the Apple Watch as well, if there are useragents anywhere...

**Comment by sanchezzzhak** [comment]
Apple Iwatch cannot be detected via php.
Apple Iwatch sends the same user agent of the device to which it is connected.

I don't know if this is really a user agent.
Apple Watch Series 5
`atc/1.0 watchOS/6.1 model/Watch5,2 hwp/t8006 build/17S84 (6; dt:201)`
I add what I have on the server.

I even came across the smart gate  x_X

**Comment by liviuconcioiu** [comment]
DEVICE_TYPE_WEARABLE
