### ISSUE TITLE
Tests run failed for another lib matthiasmullie\scrapbook\src\Adapters\MemoryStore

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6235]
error 
 `implode(): Passing glue string after array is deprecated. Swap the parameters`

```
 C:\home\server\nginx\www\detector\device-detector\vendor\matthiasmullie\scrapbook\src\Adapters\MemoryStore.php:384
 C:\home\server\nginx\www\detector\device-detector\vendor\matthiasmullie\scrapbook\src\Adapters\MemoryStore.php:47
 C:\home\server\nginx\www\detector\device-detector\Tests\Cache\PSR6CacheTest.php:23
 ```

the same error occurs in tests
PSR6CacheTest
PSR16CacheTest

OS Win10
PHP 7.4.2 (cli) (built: Jan 21 2020 17:52:24) ( NTS Visual C++ 2017 x64 )

**Comment by Findus23** [comment]
Hi,

This has been reported in https://github.com/matthiasmullie/scrapbook/issues/41 and fixed in https://github.com/matthiasmullie/scrapbook/pull/42.

The latest release (1.4.7) has been made afterwards, so you should just need to update your composer dependencies.

**Comment by sanchezzzhak** [comment]
`composer update --ignore-platform-reqs`
thank you, it helped
