### ISSUE TITLE
is this a fake useragents or a valid one?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6262]
`Mozilla/5.0 (Linux; U; Android 9; ru-ru; NX569J Build/PQ3A.190605.003) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/Mint Browser/2.4.0`

`Mozilla/5.0 (Linux; U; Android 7.0; ru-ru; Lion_Dual Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/Mint Browser/3.3.1`

`Mozilla/5.0 (Linux; U; Android 7.0; ru-ru; localhost Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/Mint Browser/3.1.4`

`Mozilla/5.0 (Linux; U; Android 7.0; ru-ru; Impress_Wolf Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.128 Mobile Safari/537.36 XiaoMi/Mint Browser/3.3.1`

Upd 1
https://play.google.com/store/apps/details?id=com.mi.globalbrowser.mini&hl=en
It seems we can no longer rely on Xiaomi's definition since this browser can install any device

**Comment by sgiehl** [comment]
Guess we need to be sure `XiaoMi` is not followed by `/Mint`, as that indicates the Mint Browser and not a Xiaomi device
