### ISSUE TITLE
Apple Email client is not detecting on v3.12.5

### ISSUE THREAD

**Issue by amytymail** [matomo-org/device-detector#6289]
Hi team,
Below is the user string which I am trying to parse and the client info is showing null.
UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko).

Please check.

Thanks

**Comment by sgiehl** [comment]
Hi @amytymail. Thanks for creating the issue. Unfortunately I don't see any possibility to detect a client for that useragent. There are no fragments included that point to any client.
