### ISSUE TITLE
Gecko layout engine version is not parsing 

### ISSUE THREAD

**Issue by amytymail** [matomo-org/device-detector#6290]
Hi Team,

When I am parsing the Gecko engine based browsers then I am getting empty engine version instead of the version which is available in the UA string.

Example UA string:
Mozilla/5.0 (Macintosh; Intel Mac OS X; U; en; rv:1.8.0) Gecko/20060728 Firefox/1.5.0 Opera 9.27

As mentioned in the UA string the gecko version is 20060728, but still it shows empty version.

Please check.

Thanks

**Comment by sgiehl** [comment]
Thanks for creating the issue. Guess that's caused by this regex
https://github.com/matomo-org/device-detector/blob/e8bee8ac311995daa078670e487239e3216cc9a7/Parser/Client/Browser/Engine/Version.php#L46

Might be something we could change...

**Comment by amytymail** [comment]
Yes exactly,

When I tried changing this value \d{1,7} to \d{1,8} it works fine and I am able to get the version string properly.

Please check at your end.

Thanks

**Comment by mimmi20** [comment]
> Mozilla/5.0 (Macintosh; Intel Mac OS X; U; en; rv:1.8.0) Gecko/20060728 Firefox/1.5.0 Opera 9.27

This UA should be an Opera.

**Comment by mimmi20** [comment]
> Mozilla/5.0 (Macintosh; Intel Mac OS X; U; en; rv:1.8.0) Gecko/20060728 Firefox/1.5.0 Opera 9.27

If this is a Firefox, the Gecko version is 1.8.0. See also https://de.wikipedia.org/wiki/Versionsgeschichte_von_Mozilla_Firefox (I did not find this overview on the english site)

**Comment by amytymail** [comment]
Hi, 
Well thats another point of discussion if it is Opera or Firefox but first it should show the version.

**Comment by mimmi20** [comment]
> Well thats another point of discussion if it is Opera or Firefox but first it should show the version

If the Browser is an Opera, then the Engine is Presto and their version is not visible in the UA.
