### ISSUE TITLE
MatomoDeviceDetector.NET is cloned project from totpero/DeviceDetector.NET

### ISSUE THREAD

**Issue by totpero** [matomo-org/device-detector#6293]
The: https://github.com/AgileFlexAgency/MatomoDeviceDetector.NET is cloned from https://github.com/totpero/DeviceDetector.NET and not forked without any specification of this and nothing original.
See: https://github.com/AgileFlexAgency/MatomoDeviceDetector.NET/issues/3

**Comment by Findus23** [comment]
@totpero 
I wrote a longer summary in the issue. I'd recommend you to contact the author directly per E-Mail and ask them to fix the issues as they might not read the Github issue. In case he doesn't respond, you can still report the package on NuGet. (but I definitly would try asking friendly first)

**Comment by totpero** [comment]
The problem was solved, you can remove the link from : https://github.com/matomo-org/device-detector#device-detector-for-other-languages
@Findus23  Thank forhelp with the detalied explanation. 👍
