### ISSUE TITLE
Profiling.... its fine!

### ISSUE THREAD

**Issue by 6562680** [matomo-org/device-detector#6298]
Maaaaan... you have 5 millions of cloning the library.

WHY YOUR LIBRARY RUN SPENT 100 MS TO DETECT DEVICE???

Once i see Carbon library (laravel included as internal) - that causes 30ms to SetLocale() method... but Carbon provides 200+ useful methods. Even then i removed carbon from auto-discover, wrap with own provider, and looked up that 5 same methods with same regexes called same function without saving the result in the property. Even then i removed carbon from constructors and do it using ServiceLocator - when i need date - i should wait until it loads.

Your library provides 5 methods. How its possible to spent 100ms to parse the device??

Man, WHOLE laravel loads in 100ms. It is with Route regex finder. Not just library.
Please, do it. For the peace.

I want to give you this two functions. You should call it in code like this:
tick('hello');
tick();
tick();
var_dump(prof());

```
<?php
// tick
if (! function_exists('tick')) {
	function tick($arg = null) : void
	{
		global $prof;

		if (! is_string($arg)) {
			if (is_null($arg)) {
				$t = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 1);
				$arg = $t[ 0 ][ 'file' ] . ':' . $t[ 0 ][ 'line' ];

			} elseif (is_object($arg) && is_a($arg, Closure::class)) {
				/** @var Closure $arg */

				try {
					$rf = new ReflectionFunction($arg);
					$arg = $rf->getFileName() . ':' . $rf->getStartLine();
				}
				catch ( ReflectionException $e ) {
					throw new RuntimeException('Invalid closure');
				}
			} else {
				$arg = is_object($arg)
					? get_class($arg)
					: gettype($arg);

			}
		}

		$prof[] = [ microtime(true), $arg ];
	}
}

// prof
if (! function_exists('prof')) {
	function prof() : array
	{
		global $prof;

		$report = [];

		$next = null;
		$time = null;
		while ( null !== ( $i = key($prof) ) ) {
			next($prof);

			$ii = key($prof);

			$next = $prof[ $ii ][ 0 ] ?? $next;

			if (isset($time)) {
				$report[] = $time;
			}

			$report[] = $prof[ $i ][ 1 ];

			$time = $next - $prof[ $i ][ 0 ];

			if (! $ms = round($time * 1000, 2)) {
				$time = (string) round($time, 6);
			} else {
				$time = $ms;
			}
		}

		return $report;
	}
}
```

**Comment by sgiehl** [comment]
Hi there. Our detection rules are stored in yml files. Parsing them takes quite a while. But using a cache as described in README should speed that up a lot. Nevertheless going through hundreds of regexes always takes a bit...

**Comment by 6562680** [comment]
Nope, yml parsing takes maybe 10ms, regex checking takes a lot.
You have to first use strpos() to detect we should use regex here.

**Comment by Findus23** [comment]
I already explained my point in https://github.com/matomo-org/device-detector/issues/5964#issuecomment-494125734
I doubt that it takes `100 MS TO DETECT DEVICE` as on https://devicedetector.lw1.at/ one can get the output in 50s including HTTP overhead.

> About security - if you forget adding ymls to web-server 403 rules you'l see the config in browser.

And what is the issue with that? You can also visit https://github.com/matomo-org/device-detector/tree/master/regexes and see all of them.

> WHY YML? Because of "symfony is the future"

I have no idea what you mean with "symfony is the future". YAML has nothing to do with symfony and is just a simple and user-friendly format which makes contributing rules here very easy.

**Comment by johnnymast** [comment]
I am sorry this I don't want to be rude. This module can't be used with composer and is to slow. I will switch to a different package.

**Comment by mimmi20** [comment]
> This module can't be used with composer

I'm using it with composer.

**Comment by sgiehl** [comment]
Feel free to use what ever you like. I know this tool is used on various websites and in various other tools and if used with a proper cache it's quite fast. I'm trying to have a look at the performance from time to time and try to improve it if possible. So I will close this issue now.

**Comment by 6562680** [comment]
Look at the "symfony" inflector that pluralizes the words.
Its very hard operation to parse all posible form using regexes. First on collect the regexes, second is the process this 50 regexes batch on each word.

Since this reason guys rewrote inflector and use low-level strpos functions to detect what group or pluralization rules should be called.

I think you have maybe thousand of regexes to detect... Maybe, just maybe, its the reason.
