### ISSUE TITLE
should we separate the Oppo and Real me brands?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6302]
Realme 5i
https://www.realme.com/global/realme-5i
* [x] Mozilla/5.0 (Linux; Android 9; RMX2030) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Mobile Safari/537.36

Realme X
* [x] Mozilla/5.0 (Linux; U; Android 9; en-US; RMX1903 Build/PKQ1.190101.001) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.108 UCBrowser/12.13.5.1209 Mobile Safari/537.36

> Realme first appeared in China in 2010 (as Oppo Real) as a sub brand of Oppo, a subsidiary of BBK Electronics[1] and was incorporated in 2018.[2][3]
> 
> On July 30, 2018, Sky Li announced his intention to establish realme as an independent brand on the Chinese microblogging website Weibo. He said that in the future, the realme brand will focus on providing mobile phones that integrate strong performance and stylish design, bringing young people a joyful life featuring affordable "technology" and "beauty".

I suggest moving all models after 2018 to a new brand `Realme`

```
Realme 1
Realme 2
Realme 2 Pro
Realme C1
Realme C2
Realme U1
Realme 3
Realme 3 Pro
Realme X
Realme X Master Edition
Realme 3i
Realme 5
Realme 5 Pro
Realme XT
Realme X2 Pro
Realme X2 Pro Master Edition
Realme 5i
Realme C3
Realme X50 Pro 5G
```
https://en.wikipedia.org/wiki/Realme

this situation is similar to Sony ericsson only in reverse

**Comment by sgiehl** [comment]
Guess would make sense to move them to their own brand then. But we should remove `Realme` from the model name then I guess...
