### ISSUE TITLE
FAQ find HUAWEI device model name

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6306]
I want to share where to find the device model name from Huawei

You can find the name of the device on the support page
You only need to take into account the country that the device is intended for
I mostly search on a Chinese portal

https://consumer.huawei.com/cn/support/sparepart-price/
https://consumer.huawei.com/ru/support/sparepart-price/

you need to enter the device ID, example `JEF-AN00` full useragent `Mozilla/5.0 (Linux; Android 10; JEF-AN00 Build/XXXXX JEF-AN00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/76.0.3809.89 Mobile Safari/537.36`

It is a pity that there is no similar service from OPPO, VIVO, Realme, one plus, although they are part of the same company BBK

**Comment by sgiehl** [comment]
moved to https://github.com/matomo-org/device-detector/wiki/FAQ
