### ISSUE TITLE
Missed MS Edge MacOS

### ISSUE THREAD

**Issue by WuglyakBolgoink** [matomo-org/device-detector#6311]
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36 Edg/83.0.478.54

![image](https://user-images.githubusercontent.com/2271337/85077490-b3690f00-b1c2-11ea-909a-8e5b14e4ca96.png)

But on mobile device it was correct detected:

> Mozilla/5.0 (Linux; Android 9; CLT-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/45.04.4.4995

![image](https://user-images.githubusercontent.com/2271337/85077713-368a6500-b1c3-11ea-8fb2-4327c87525b5.png)

I use now:
> `const isMSEdge = _.includes(userAgent, 'edg/') || _.includes(userAgent, 'edga/') || _.includes(userAgent, 'edge/');`

**Comment by Findus23** [comment]
I think the devicedetector version this site uses is a bit outdated.

Can you check if https://devicedetector.lw1.at/ gives the right results? (it looks good to me)

**Comment by WuglyakBolgoink** [comment]
Hallo @Findus23 ,

yes. A new site give me a right answer!
