### ISSUE TITLE
ipad

### ISSUE THREAD

**Issue by osben** [matomo-org/device-detector#6313]
user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

**Comment by sgiehl** [comment]
@osben Thanks for creating the issue.
We actually can't detect that as an iPad, as it does not included any details that are iPad specific.

**Comment by osben** [comment]
But what about "Mobile" + "Macintosh" and does not contain "Safari"

**Comment by sgiehl** [comment]
Does that safely indicate an iPad? Might it not be the same if a iPhone requests a desktop website?

**Comment by Findus23** [comment]
For me the user agent on an iPad in Safari is 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15
```
I think the Mobile part is added by the app that sends the request, so one can't rely on it.

**Comment by sgiehl** [comment]
Btw @Findus23  is the `request desktop version` option still enabled by default on iPad? guess that might be the reason why there is no iPad identifier in it...

**Comment by Findus23** [comment]
@sgiehl Yes, by default the desktop page is always requested (causing the Mac OS user agent)

When one requests the mobile page, the user agent becomes:
```
Mozilla/5.0 (iPad; CPU OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1
```

It seems like one can change this default to the other way round in the settings
