### ISSUE TITLE
Convention naming device model 

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6334]
Hi, I want to suggest a device model naming Convention

### [Devices containing the year must be written in brackets](#note-1)
* * Bad `Blade A5 2019`
* * Good `Blade A5 (2019)`
* [x] Approved

### [Devices containing a size must contain one double quotation mark after the size](#note-2)
* * Bad `GALAXY Note 8.0`
* * Good `GALAXY Note 8.0"`
* [x] Approved

### [Devices containing the abbreviations `PRO`, `MAX`, `MINI`, `LITE`, `ACTIVE`, `CORE` must be written letter case](#note-3)
* * Bad `GALAXY S4 ACTIVE`, `GALAXY S II WiMAX`
* * Good `GALAXY S4 Active`, `GALAXY S II WiMax`
* [x] Approved

**Comment by sgiehl** [comment]
@sanchezzzhak sounds good. Feel free to change the existing ones.

**Comment by sgiehl** [comment]
I've activated the WIKI and will move such stuff there... See https://github.com/matomo-org/device-detector/wiki/Convention-naming-device-models
