### ISSUE TITLE
what brand should these devices belong to Cube, Mytab, Myphone or AllDocube

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6340]
We define all mytabs as the MyPhone brand
* [x] Mozilla/5.0 (Linux; Android 4.2.2; Mytab-U55GT Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Safari/537.36 OPR/50.3.2426.136976
The models by the way are similar in design to the Cube brand.

cherry on the cake:
![image](https://user-images.githubusercontent.com/1337066/89194772-7b6e2d80-d5b0-11ea-9963-e7eba2ef7a07.png)
Manufacturer: AllDocube

**Comment by sgiehl** [comment]
HandsetDetection lists them as `MyTab`, but actually I have no preference in that case. Sound all kind of legit 🤷
