### ISSUE TITLE
New devices that are not in Matomo

### ISSUE THREAD

**Issue by arvin-trafficguard** [matomo-org/device-detector#6341]
Hey,

We detected these new devices which are not currently in Matomo. 

regex | brand | model | deviceType | sample | -
-- | -- | -- | -- | -- | --
(?:M2004J19C Build) | Xiaomi | Redmi 9 | smartphone | Mozilla/5.0 (Linux; Android 10; M2004J19C Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.105 Mobile Safari/537.36 (Mobile; afma-sdk-a-v202614037.202614037.0) | :heavy_check_mark: 
(?:RMX2002 Build) | realme | 6s | smartphone | Dalvik/2.1.0 (Linux; U; Android 10; RMX2002 Build/QP1A.190711.020) | :heavy_check_mark: 
(?:IN2017 Build) | OnePlus | 8 | smartphone | Mozilla/5.0 (Linux; Android 10; IN2017 Build/QKQ1.191222.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.111 Mobile Safari/537.36 | :heavy_check_mark: 
(?:Joy 3 Build) | Vsmart | Joy 3 | smartphone | Dalvik/2.1.0 (Linux; U; Android 9; Joy 3 Build/PKQ1.190601.001) |
(?:Active 3 Build) | Vsmart | Active 3 | smartphone | Dalvik/2.1.0 (Linux; U; Android 9; Active 3 Build/PPR1.180610.011) |
(?:QS5509A Build) | AT&T | Axia | smartphone | Mozilla/5.0 (Linux; Android 8.1.0; QS5509A Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.89 Mobile Safari/537.36 | :heavy_check_mark: 
(?:U693CL Build) | UMX | U693CL | smartphone | Mozilla/5.0 (Linux; Android 9; U693CL Build/U693CL_01.01.05; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.89 Mobile Safari/537.36 | :heavy_check_mark: 
(?:RMX2032 Build) | realme | 5i | smartphone | Dalvik/2.1.0 (Linux; U; Android 10; RMX2032 Build/QKQ1.200209.002) | :heavy_check_mark: 
(?:VIEW 1 Build) | TracFone | View 1 | smartphone | Mozilla/5.0 (Linux; Android 9; VIEW 1 Build/P00610; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.89 Mobile Safari/537.36 |
(?:HD1925 Build) | OnePlus | 7T Pro (5G) | smartphone | Mozilla/5.0 (Linux; Android 10; HD1925 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.89 Mobile Safari/537.36 | :heavy_check_mark: 
(?:RMX2021 Build) | realme | C3 | smartphone | Dalvik/2.1.0 (Linux; U; Android 10; RMX2021 Build/QP1A.190711.020) | :heavy_check_mark: 
(?:RMX1919 Build) | realme | 5 | smartphone | Dalvik/2.1.0 (Linux; U; Android 9; RMX1919 Build/PKQ1.190616.001) | :heavy_check_mark: 
(?:Star Build) | LG | star | smartphone | Dalvik/2.1.0 (Linux; U; Android 9; Star Build/PKQ1.190601.001) |
(?:PTB7R Build) | Philco | PTB7R | smartphone | Mozilla/5.0 (Linux; Android 9; PTB7R Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.89 Safari/537.36 | :heavy_check_mark: 
(?:R2 LTE Build) | BLU | R2 LTE | smartphone | Dalvik/2.1.0 (Linux; U; Android 7.0; R2 LTE Build/NRD90M) |
(?:M13 Build) | LEAGOO | M13 | smartphone | Dalvik/2.1.0 (Linux; U; Android 9; M13 Build/P00610) |
(?:IN2023 Build) | OnePlus | 8 Pro | smartphone | Dalvik/2.1.0 (Linux; U; Android 10; IN2023 Build/QKQ1.191222.002) | :heavy_check_mark: 
(?:IN2020 Build) | OnePlus | 8 Pro | smartphone | Dalvik/2.1.0 (Linux; U; Android 10; IN2020 Build/QKQ1.191222.002) | :heavy_check_mark: 
(?:U2 Build) | AnyDATA | HCL ME TABLET PC U2 | smartphone | Dalvik/2.1.0 (Linux; U; Android 5.1; U2 Build/LMY47I) |
(?:IN2013 Build) | OnePlus | 8 | smartphone | Dalvik/2.1.0 (Linux; U; Android 10; IN2013 Build/QKQ1.191222.002) | :heavy_check_mark:

**Comment by sanchezzzhak** [comment]
Hi, thank you for creating issue.

The useragent: 
* `Mozilla/5.0 (Linux; Android 9; U693CL Build/U693CL_01.01.05; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.89 Mobile Safari/537.36`
Brand Unimax model UMX

**Comment by sanchezzzhak** [comment]
Very few characters to define the model, we need at least 4

* Dalvik/2.1.0 (Linux; U; Android 5.1; U2 Build/LMY47I)
* Dalvik/2.1.0 (Linux; U; Android 9; M13 Build/P00610)

Most likely this is the Blu brand
Blu View 1 (Released 2019, November. Android 9 Pie)
* Mozilla/5.0 (Linux; Android 9; VIEW 1 Build/P00610; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/84.0.4147.89 Mobile Safari/537.36

**Comment by sanchezzzhak** [comment]
Thank you for your information.
The issue is closed, we have processed the maximum amount of information provided.
