### ISSUE TITLE
Add Vercel bot

### ISSUE THREAD

**Issue by metmarkosaric** [matomo-org/device-detector#6361]
Vercel have created a User-Agent of something like Vercelbot (+https://vercel.com) for [their bot](https://github.com/vercel/vercel/discussions/5095#discussioncomment-58705). Is it possible to add it to the list please? Thanks!

**Comment by sanchezzzhak** [comment]
Hi. This useragent is added to detection.
Definitions are available in the main branch and will appear in stable versions later.
The issue is closed.
