### ISSUE TITLE
Roblox Android App with unusual User Agent Format

### ISSUE THREAD

**Issue by nickperkins** [matomo-org/device-detector#6372]
I am in the process of adding some new user agents for the Roblox mobile app.

On Android, the system information isn't in the usual format. This is Android 10, as indicated by the "10" after the phone model.

`Mozilla/5.0 (2822MB; 720x1411; 320x319; 411x806; Samsung SM-A115F; 10) AppleWebKit/537.36 (KHTML, like Gecko)  ROBLOX Android App 2.448.411159 Phone Hybrid()  GooglePlayStore RobloxApp/2.448.411159 (GlobalDist; GooglePlayStore)`

Unfortunately, this user agent returns the Android version as 2.448.411159. The Android regex is matching 'Android App 2.448.411159'.

My understanding of the code is that once a regex matches, it will stop checking further regexes. Therefore, a workaround would be to change the current Android regex to `(?:(?:Orca-)?Android|Adr)[ /](?!App)(?:[a-z]+ )?(\d+[\.\d]*)` and add a new regex to `oss.yml` for this app. However as this is an edge case, I wanted to raise it as an issue first.

**Comment by mimmi20** [comment]
> Unfortunately, this user agent returns the Android version as

Isn't `ROBLOX Android App 2.448.411159` the App name with app version?

I think `Samsung SM-A115F; 10` is showing the device and the Android version.

**Comment by sanchezzzhak** [comment]
* Mozilla/5.0 (3794MB; 1440x2417; 554x555; 423x710; LGE LGLS992; 7.0) AppleWebKit/537.36 (KHTML, like Gecko) ROBLOX Android App 2.389.310791 Phone Hybrid() GooglePlayStore
* Mozilla/5.0 (1791MB; 1920x1128; 225x224; 1280x752; Amazon KFMAWI; 9) AppleWebKit/537.36 (KHTML, like Gecko) ROBLOX Android App 2.434.405561 Tablet Hybrid() AmazonAppStore RobloxApp/2.434.405561 (GlobalDist; AmazonAppStore)

```yml
- regex: '[ ]([\d\.]+)\) AppleWebKit.*ROBLOX Android App'
  name: 'Android'
  version: '$1'
```
Put this rule above the rule
```
- regex: '(?:(?:Orca-)?Android|Adr)[ /](?:[a-z]+ )?(\d+[\.\d]*)'
  name: 'Android'
  version: '$1'
```

**Comment by nickperkins** [comment]
Thanks. I'll continue on the updates and submit a PR in due course.
