### ISSUE TITLE
Brand Xoro model HMT390Q what type of device?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6379]
The device looks like a music speaker with a tablet

* [x] Mozilla/5.0 (Linux; Android 5.1.1; HMT390Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.62 Safari/537.36
   https://www.xoro.de/produkte/details/xoro-hmt-390q/
* [x] Mozilla/5.0 (Linux; Android 4.4.2; HMT400 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36
  https://www.xoro.de/produkte/details/xoro-hmt-400/

**Comment by mimmi20** [comment]
If the speakers are not removable, it should be a media player.

**Comment by sanchezzzhak** [comment]
thanks
