### ISSUE TITLE
Incorrect class name is used in usage example at readme.md

### ISSUE THREAD

**Issue by Elvinas** [matomo-org/device-detector#6407]
So, I just quickly wanted to analyze this library and tried following usage part:

`require_once 'vendor/autoload.php';

use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\AbstractDeviceParser;

// OPTIONAL: Set version truncation to none, so full versions will be returned
// By default only minor versions will be returned (e.g. X.Y)
// for other options see VERSION_TRUNCATION_* constants in DeviceParserAbstract class
AbstractDeviceParser::setVersionTruncation(AbstractDeviceParser::VERSION_TRUNCATION_NONE);`

And according to this example 'AbstractDeviceParser' class is used here but I got class not found type of error, I looked at the folder structure of piwik/device-detector and found that the class name is actually: 'DeviceParserAbstract' and not 'AbstractDeviceParser'. 

So probably example should be edited accordingly I guess. Btw, thanks for the wonderful library 👍

**Comment by Findus23** [comment]
Hi,

This was caused by https://github.com/matomo-org/device-detector/pull/6401 as the class name changed in the (yet unreleased) 4.x version.

As you are probably using the latest version, you should probably take a look at the readme for it:
https://github.com/matomo-org/device-detector/tree/3.13.1

**Comment by Elvinas** [comment]
Thanks :)

> Hi,
> 
> This was caused by #6401 as the class name changed in the (yet unreleased) 4.x version.
> 
> As you are probably using the latest version, you should probably take a look at the readme for it:
> https://github.com/matomo-org/device-detector/tree/3.13.1

Thanks :)

**Comment by Findus23** [comment]
Just for your information: Device Detector 4.0.0 has just been released.
