### ISSUE TITLE
Linux distributive `ROSA` Do we need to define?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6427]
`Mozilla/5.0 (X11; OS ROSA; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36`

https://en.wikipedia.org/wiki/ROSA_Linux

**Comment by sgiehl** [comment]
Sure, why not. We already have a lot other distributions defined here https://github.com/matomo-org/device-detector/blob/4e7a06af0d0f48179852cc0bec39051f0d8cb77c/regexes/oss.yml#L186-L192
