### ISSUE TITLE
Not working without composer.

### ISSUE THREAD

**Issue by vikashpanchal100** [matomo-org/device-detector#6457]
Not working without composer. The way mentioned here is not working for without composer.

**Comment by sgiehl** [comment]
Could you maybe provide some more information on what you actually tried to do and which error you ran into? Otherwise it's hard to help in any way

**Comment by liviuconcioiu** [comment]
@vikashpanchal100 have you added the Spyc class from [https://github.com/mustangostang/spyc/blob/master/Spyc.php](https://github.com/mustangostang/spyc/blob/master/Spyc.php)? This file is not included.

**Comment by vikashpanchal100** [comment]
As I downloaded and used device-detector using composer, it worked fine and detecting device info. but if i download zip file without using composer. it does not works.

**Comment by vikashpanchal100** [comment]
I used below code,
include 'libraries/mustangostang/spyc/Spyc.php';
include 'libraries/matomo/device-detector/DeviceDetector.php';
use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\AbstractDeviceParser;

AbstractDeviceParser::setVersionTruncation(AbstractDeviceParser::VERSION_TRUNCATION_NONE);
$userAgent = $_SERVER['HTTP_USER_AGENT'];
$deviceDetector = new DeviceDetector($userAgent);
$deviceDetector->parse();
print_R($deviceDetector->getClient());die;

**Comment by sgiehl** [comment]
@vikashpanchal100  What is the output of that script, or is there any error thrown in your code, any message that might point to anything?

**Comment by sanchezzzhak** [comment]
you must include motamo-device-detector via
device-detector/autoload.php
```
<?php
include 'libraries/mustangostang/spyc/Spyc.php';
include 'libraries/matomo/device-detector/autoload.php';

use DeviceDetector\DeviceDetector;
use DeviceDetector\Parser\Device\AbstractDeviceParser;

AbstractDeviceParser::setVersionTruncation(AbstractDeviceParser::VERSION_TRUNCATION_NONE);
$userAgent = $_SERVER['HTTP_USER_AGENT'];
$deviceDetector = new DeviceDetector($userAgent);
$deviceDetector->parse();
print_r($deviceDetector->getClient());die;
```

**Comment by liviuconcioiu** [comment]
@vikashpanchal100 change `include 'libraries/matomo/device-detector/DeviceDetector.php';` with `include 'libraries/matomo/device-detector/autoload.php';`

**Comment by sanchezzzhak** [comment]
@vikashpanchal100 was your issue resolved?

**Comment by vikashpanchal100** [comment]
@sanchezzzhak @liviuconcioiu @sgiehl,  thanks guys, issue resoloved by just using include 'libraries/matomo/device-detector/autoload.php'; cloasing it.
