### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by liviuconcioiu** [matomo-org/device-detector#6465]
Should tests also be run on PHP 8.0?

**Comment by sgiehl** [comment]
They currently run on `nightly`, which is `8.0.1-dev` atm. But might not hurt to add 8.0 explicitly, now that it was released

**Comment by sgiehl** [comment]
@sanchezzzhak any reason for reopening?

**Comment by sanchezzzhak** [comment]
@sgiehl matthiasmullie/scrapbook not install for php8 tests

https://github.com/matomo-org/device-detector/pull/6522/checks?check_run_id=1566011456

**Comment by sgiehl** [comment]
seems ubuntu-latest now runs with PHP 8. updated the github actions to ignore the platform reqs. should all work correctly again.
