### ISSUE TITLE
Allwinner UltraOcta-T8 is device type car or tablet?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6510]
* [x] Mozilla/5.0 (Linux; Android 7.1.2; UltraOcta-T8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.81 Safari/537.36

https://cs6-1.4pda.to/11582943.jpg
head unit mount in panel
https://www.youtube.com/watch?v=dNGiWrIkGR4

**Comment by sgiehl** [comment]
Seems to be integrated in cars, right? If so I would vote for `car`
