### ISSUE TITLE
Planet Computers Cosmo Communicator what type of device should I use? Tablet?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6511]
brand `Planet Computers` model `Cosmo Communicator`

* [x] Mozilla/5.0 (Linux; Android 9; Cosmo_Communicator) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.185 Mobile Safari/537.36

https://www.youtube.com/watch?v=LBzI1MECNq8

**Comment by sgiehl** [comment]
Yes. Let's go with tablet.
