### ISSUE TITLE
Mobile Safari, Chrome and Facebook app version not detected

### ISSUE THREAD

**Issue by liviuconcioiu** [matomo-org/device-detector#6520]
- [ ] Mozilla / 5.0 (Windows NT 6.1, WOW64) AppleWebKit / 536.5 (KHTML, comme Gecko) Chrome / 19.0.1084.52 Safari / 536.5
- [ ] Mozilla / 5.0 (iPhone; U; CPU iPhone OS 4_2_1 comme Mac OS X) AppleWebKit / 533.17.9 (KHTML comme Gecko) Version / 5.0.2 Mobile / 8C148 Safari / 6533.18.5
- [ ] Mozilla / 5.0 (iPhone; CPU iPhone OS 11_1 comme Mac OS X) AppleWebKit / 604.3.5 (KHTML comme Gecko) Mobile / 15B93 [FBAN / FBIOS; FBAV / 148.0.0.45.64; FBBV / 78032376; FBDV /iPhone10,4; FBMD / iPhone; FBSN / iOS; FBSV / 11.1; FBSS / 2; FBCR / AT & T; FBID / téléphone; FBLC / en_US; FBOP / 5; FBRV / 0]

**Comment by sanchezzzhak** [comment]
I think this is an incorrectly saved useragent, with spaces around slash
