### ISSUE TITLE
Re "Phablet" category

### ISSUE THREAD

**Issue by dev-101** [matomo-org/device-detector#6570]
I have noticed that phablet category is questionable at best. Reason being that some models are categorized as such, but others not, which creates a lot of inconsistencies, and in fact, messes up reports and everything.

e.g. "phablets" are:
```
Xiaomi Mi Note 10
Xiaomi Redmi Note 9
Xiaomi Redmi Note 9S
Xiaomi Redmi Note 8 Pro
Samsung Galaxy 10+
etc.
```

Phones are getting bigger, boundaries slimmer, and the category is now more of a maintenance and reporting burden than truly useful.

I would also consider following Samsung models below to be changed to smartphones, despite that they come with a pen:

```
Samsung Galaxy Note 9
Samsung Galaxy Note 8
Samsung Galaxy Note 5
```

Galaxy 20 Ultra is bigger in size than Note20 Ultra, for example, yet, it is classified as "smartphone". No logic, iyam.
Think about it ;)

**Comment by sanchezzzhak** [comment]
I agree that the boundaries are narrowing, phones have become larger and the phablet type loses its meaning.
We will definitely not be renaming device types for a bygone era.

Currently, `phablet` can be considered devices with sizes `6.5-6.9`
