### ISSUE TITLE
I can't find the device type from a dead brand `Connectce`

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6577]
* [x] Mozilla/5.0 (Linux; Android 6.0; CP6001A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Mobile Safari/537.36
* Mozilla/5.0 (Linux; Android 6.0; CP6001A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36

brand Connectce
model Connect_Core_6

**Comment by sgiehl** [comment]
According to DeviceAtlas it's a mobile phone. So guess we could go with `smartphone`
