### ISSUE TITLE
Client hints future

### ISSUE THREAD

**Issue by JureMalovrh** [matomo-org/device-detector#6584]
Given that the `Client hints` ([spec](https://httpwg.org/http-extensions/draft-ietf-httpbis-client-hints.html#name-advertising-server-support)) are planned for release in 2021, I am wondering are there any movement/discussions in this library regarding the future? Will this library try to support client hints parsing?

**Comment by sgiehl** [comment]
We have not yet discussed that with the team, but personally I wouldn't include that into this library. It's meant for useragent parsing.
But as Matomo at some point will need some kind of parsing of those client hints, we might need to consider building a new library for it maybe. But as long as it's not known how those client hint values will actually look like in all browsers, it's hard to say anything in detail.

**Comment by Findus23** [comment]
Hi @JureMalovrh,

See here on more details on supporting Client hints in Matomo (which I guess will also involve a library that can then be used outside of Matomo): https://github.com/matomo-org/matomo/issues/16125
But it seems to my like very little has changed on this topic in the last year

**Comment by sanchezzzhak** [comment]
Most likely, the current version can work in detecting the model and brand, but you will have to pass the data from JS yourself.
I hope the client-hints never show up.

**Comment by JureMalovrh** [comment]
Thanks for the answers and a link to a given discussion in your main project. 

I agree with @sgiehl that this should be a separate library, but at the same time, similar parsing capabilities will probably be needed. I opened this question just to see what is the current stance of Matomo organization and to maybe "warm" people that this is coming, as I think currently a lot of people are not even aware that this is coming.

And yeah I agree that this will never show up, but our odds are not in our favor :).

**Comment by sgiehl** [comment]
Closing. As we won't support client hints here (as discussed)...
