### ISSUE TITLE
Name of a signature not in quotes 

### ISSUE THREAD

**Issue by nstylepro** [matomo-org/device-detector#6602]
https://github.com/matomo-org/device-detector/blob/a56e018ddd8670aee587ebb916927f3b62bf811b/regexes/device/mobiles.yml#L18999

other instances of int in the YAML appear between quotes. is this a bug? 
fails to load at mine.

**Comment by sgiehl** [comment]
could you please check this one @sanchezzzhak

**Comment by sanchezzzhak** [comment]
it is best to do value float/int in yml in quotation
