### ISSUE TITLE
iOS/macOS apps not detected correctly

### ISSUE THREAD

**Issue by adityapatadia** [matomo-org/device-detector#6604]
We have lot of useragents like `Clovia/3.3.1 CFNetwork/1206 Darwin/20.1.0` We were expecting it to detect Clovia as client app with 3.3.1 version along with OS versions. It does not detect it well.

**Comment by sanchezzzhak** [comment]
can you send a list of useragents which have an empty result?

We don't specifically add a general rule `([\w].+)/(\d+[\d\.]+) CFNetwork` because it has unpredictable results.

**Comment by adityapatadia** [comment]
I will try to provide list but the list is going to be long. Almost all apps give user-agent in this format. We deal with lot of such apps.

**Comment by adityapatadia** [comment]
Also curious what can go wrong with General rule? It's established that Apple always puts user-agent in this format.

**Comment by sanchezzzhak** [comment]
some useragents contain nonsense that is hard to match with the actual name of the application.
```log
iCoreService (unknown version) CFNetwork/1125.2 Darwin/19.4.0 (x86_64)
%D9%85%D8%B4%D8%BA%D9%84%20%D8%A7%D9%86%D8%BA%D8%A7%D9%85%D9%8A/3 CFNetwork/976 Darwin/18.2.0  # "بانوراما فيديو/5"  or en name "Panorama Video/5"

%D8%B7%D8%B1%D8%A8/1.1 CFNetwork/758.2.8 Darwin/15.0.0   -  # "مشغل انغامي/3" or en name "Anghami Player/3"

 Client/1.2.0 CFNetwork/978.0.7 Darwin/18.5.0
 app/2020.10.0202 CFNetwork/1197 Darwin/20.0.0
 Browser/2.1 CFNetwork/758.5.3 Darwin/15.6.0
```

CFNetwork may also have browsers that should be marked as a browser, not as a mobile app. example:
```
Aloha/10 CFNetwork/978.0.7 Darwin/18.7.0
Mercury/7.4 CFNetwork/711.5.6 Darwin/14.0.0
Sleipnir%20Browser/4.5.5012 CFNetwork/673.6 Darwin/13.4.0 (x86_64) (MacBookPro9%2C2) 
SP%20Browser/3.8.2 CFNetwork/1121.2.2 Darwin/19.2.0   # https://apps.apple.com/ru/app/sp-browser/id1376568492
```
