### ISSUE TITLE
Does not work on IPad 5,3

### ISSUE THREAD

**Issue by WillFontana** [matomo-org/device-detector#6619]
⚠️ Missing/incorrect detections should be reported at https://github.com/matomo-org/device-detector/issues instead of this repo.
# Issue:
Detector does not work on IPad 5,3. Though it works fine in other IOs devices , Mac's also doesn't seems to have the same problem, so it only occurs on Ipad 5,3

# Expected behaviour:
Print the device data as shown in the example.

# Actual behaviour:
The library simply breaks the script and stop the others JS that needs to run after.

# Code example:
```bash
import DeviceDetector from "device-detector-js";

const deviceDetector = new DeviceDetector();

function printDevice(deviceData) {
  const device = deviceDetector.parse(deviceData);
  return device;
}

window.deviceData = printDevice;
```

# Outputs and Logs:
Unfortunately I have no access to any Mac's, and because of that i cannot see any debug log.

**Comment by sgiehl** [comment]
Hi @WillFontana 
Thanks for creating the issue. We actually would need the exact useragent in order to check why it might not be detected correctly.
iPad5,3 should already be detected correctly since 2019, so maybe it's some special useragent that doesn't work?

**Comment by sanchezzzhak** [comment]
This repository only works for php versions.

as for your problem in ios safari.
Ios safari not support regex negative-lookahead

**Comment by Findus23** [comment]
Hi, 
This is most likely the same issue as https://github.com/etienne-martin/device-detector-js/issues/89 and https://github.com/etienne-martin/device-detector-js/issues/31

If you could share the user agent with us, we could verify that it is correctly detected by DeviceDetector (or you could check https://devicedetector.lw1.at/)

**Comment by WillFontana** [comment]
@sgiehl and @Findus23 _ Tanks for the answer, the userAgent is:
*Mozilla/5.0 (iPad; CPU OS 10_3_4 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G61 Safari/602.1*
I don't know if there is something wrong with this one...
I'll checkout those issues too and the link you suggested me
Again thanks for answering back!

**Comment by WillFontana** [comment]
@sanchezzzhak We are using PHP, i'm importing these repo only to use it in a function later so we can send the data to our BD

**Comment by WillFontana** [comment]
## Closing the issue
I fount that @sanchezzzhak was right about the PHP repo, i was using the npm version, that was the issue with the IPad, we're rewriting the code so it works on PHP only.
The links @Findus23 pasted helped a lot.
Thanks everyone for the help!
Technically we solved, so from now on is on us!
