### ISSUE TITLE
Matomo Tracking Edge accesses as Chrome

### ISSUE THREAD

**Issue by BrunoASGoncalves** [matomo-org/device-detector#6634]
Since 2018, in the company I work, we have Matomo installed in a local server to track Intranet accesses.

**Since last quarter of 2020, Matomo is tracking most Edge accesses as Chrome.**

Please see print-screens below.

Can someone help us here?

1. Matomo BO: My real-time log - I’m accessing via Edge, but Matomo is tracking as Chrome 86.0
 ![image](https://user-images.githubusercontent.com/78732109/107212457-e46eac00-69fe-11eb-9c15-ecbf4f2d9b14.png)

2. Edge version I used in this example 
![image](https://user-images.githubusercontent.com/78732109/107212623-213aa300-69ff-11eb-9bec-f68a575ccde9.png)

3. Matomo BO: browser’s graph from january/2021 - not accurate, since there are more actual-effective access via Edge than Chrome
![image](https://user-images.githubusercontent.com/78732109/107212691-3f080800-69ff-11eb-8781-95faba95ec27.png)

**Comment by sanchezzzhak** [comment]
Hi
Version motamo? https://matomo.org/faq/how-to-update/faq_8/
version device-detector?

**Comment by BrunoASGoncalves** [comment]
Hi @sanchezzzhak,
thanks for your reply.

> Hi

> Version motamo? https://matomo.org/faq/how-to-update/faq_8/
_Matomo version: 3.9.1
MySQL version: 5.7.33-0ubuntu0.18.04.1
PHP version: 7.2.24-0ubuntu0.18.04.7_

> version device-detector?
![image](https://user-images.githubusercontent.com/78732109/107218644-c9ed0080-6a07-11eb-9749-76e79aadb5a7.png)

**Comment by sgiehl** [comment]
Hi @BrunoASGoncalves.
Matomo 3.9.1 uses a quite old version of the device detector library. To have updated detections you need to update Matomo itself, as it includes device detector
