### ISSUE TITLE
Please check these user agents

### ISSUE THREAD

**Issue by pierrocknroll** [matomo-org/device-detector#6637]
Hello,
I have a small list of user agents incorrectly parsed. They are marked as browser in client_type, but it's generally mobile apps.

- [x] Podbean/Android App 8.3.2 (http://podbean.com)
- [x] AlexaMediaPlayer/2.0.201528.0 (Linux;Android 5.1.1) ExoPlayerLib/1.5.9
- [x] TuneIn Radio Pro/25.7.3 (Linux;Android 5.0) ExoPlayerLib/2.11.8
- [x] TuneIn Radio/25.7.3 (Linux;Android 7.1.1) ExoPlayerLib/2.11.8,gzip(gfe)
- [x] TuneIn Radio Pro By Farsroid.com/25.7.3 (Linux;Android 10) ExoPlayerLib/2.11.8
- [x] com.evolve.podcast/3.18.0 (iPhone; ) (build 1901, iOS 13.3.1)
- [x] com.evolve.podcast/3.18.0 (iPad; ) (build 1901, iOS 12.4.4)
- [x] Swoot/1.76.0 (Linux;Android 10) ExoPlayerLib/2.9.6
- [x] Podimo/1.20.1 build 148/Android 29
- [x] RadioPublic/android-2.2
- [x] Podcaster/1.0.0 (Linux;Android 9) ExoPlayerLib/2.9.6

I also have these strange UA parsed as a "Coast" or "Sunrise" browsers but I think it's something else:
- [x] Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone9,3;FBMD/iPhone;FBSN/iOS;FBSV/13.3.1;FBSS/2;FBID/phone;FBLC/fr_FR;FBOP/5;FBCR/Orange Ivory Coast]
- [x] Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone10,6;FBMD/iPhone;FBSN/iOS;FBSV/13.3;FBSS/3;FBID/phone;FBLC/fr_FR;FBOP/5;FBCR/Orange Ivory Coast]
- [x] Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone10,6;FBMD/iPhone;FBSN/iOS;FBSV/13.3.1;FBSS/3;FBID/phone;FBLC/fr_FR;FBOP/5;FBCR/Sunrise]

Thanks a lot for your incredible work !

**Comment by liviuconcioiu** [comment]
> I also have these strange UA parsed as a "Coast" or "Sunrise" browsers but I think it's something else:
> 
>     * [ ]  Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone9,3;FBMD/iPhone;FBSN/iOS;FBSV/13.3.1;FBSS/2;FBID/phone;FBLC/fr_FR;FBOP/5;FBCR/Orange Ivory Coast]
> 
>     * [ ]  Mozilla/5.0 (iPhone; CPU iPhone OS 13_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone10,6;FBMD/iPhone;FBSN/iOS;FBSV/13.3;FBSS/3;FBID/phone;FBLC/fr_FR;FBOP/5;FBCR/Orange Ivory Coast]
> 
>     * [ ]  Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [FBAN/FBIOS;FBDV/iPhone10,6;FBMD/iPhone;FBSN/iOS;FBSV/13.3.1;FBSS/3;FBID/phone;FBLC/fr_FR;FBOP/5;FBCR/Sunrise]
> 
Those are correctly detected. You need to use the latest version of device-detector.

**Comment by sanchezzzhak** [comment]
Thank you for the issue you created.
I have marked the task that are completed and contained in the master branch.
The next update stable version should be released in the coming days (I hope)
