### ISSUE TITLE
Php8 support?

### ISSUE THREAD

**Issue by alfredone270895** [matomo-org/device-detector#6713]
i try to install in php8 i receive this error
Problem 1
- wyrihaximus/html-compress 1.4.0 requires php ^7.0 || ^5.6 -> your PHP version (8.0.3) does not satisfy that requirement.
- wyrihaximus/html-compress 1.4.0 requires php ^7.0 || ^5.6 -> your PHP version (8.0.3) does not satisfy that requirement.
- wyrihaximus/html-compress 1.4.0 requires php ^7.0 || ^5.6 -> your PHP version (8.0.3) does not satisfy that requirement.
- Installation request for wyrihaximus/html-compress (locked at 1.4.0) -> satisfiable by wyrihaximus/html-compress[1.4.0].

**Comment by Findus23** [comment]
Hi,

Are you sure that the issue is in this library, not in `wyrihaximus/html-compress` as the error message says?

**Comment by alfredone270895** [comment]
yes excuse me i fix it , is perfectly working . thanks
