### ISSUE TITLE
Incorrect parsing of laptop useragent string

### ISSUE THREAD

**Issue by bjhawk** [matomo-org/device-detector#6733]
A new set of useragents have appeared in my usage that are not correctly identified

```
Microsoft Office OneNote/16.0.13328.20478 (Windows/10.0; Desktop x64; en-GB; Universal app; Dell Inc./XPS 13 9370)

Microsoft Office OneNote/16.0.13328.20478 (Windows/10.0; Desktop x64; en-GB; Universal app; Dell Inc./XPS 13 9360)
```

These both come back correctly as windows, but are marked as `isSmartphone() = true` and no other `is*` value.

**Comment by sanchezzzhak** [comment]
@bjhawk thank you for creating the issue.
@sgiehl we can add a new type for desktop app?

**Comment by sgiehl** [comment]
@sanchezzzhak Not sure if we should distinguish between mobile and desktop apps.
