### ISSUE TITLE
Other Android OS forks detect?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6745]
I've had my eyes hurt by some user agents for a long time now

### Revenge Os
https://sourceforge.net/projects/revengeos/files/x2/ 
Revenge Os version 2??
* [x] Mozilla/5.0 (Linux; Android 10; revengeos_x2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Mobile Safari/537.36

### lineage Os
https://wiki.lineageos.org/devices/, https://stats.lineageos.org/
lineage Os  (at the beginning of the device name is the prefix lineage_ ??? )
* Device Brand: `Sharp` Model: `Aquos S2`
* [x] "Mozilla/5.0 (Linux; Android 11; lineage_ss2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36 OPR/62.3.3146.57763"
* Device Brand: `Motorola` model: `Moto G 2015` (osprey)
* [x] "Mozilla/5.0 (Linux; Android 7.1.2; lineage_osprey) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Mobile Safari/537.36"
* 
* [ ] "Mozilla/5.0 (Linux; Android 9; lineage_maple) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
*
* [x] Dalvik/2.1.0 (Linux; U; Android 7.1.1; lineage_A6020 Build/NMF26V)
*
* [x] "Mozilla/5.0 (Linux; Android 9; lineage_c106) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.82 Mobile Safari/537.36"

### Remix OS (https://en.wikipedia.org/wiki/Resurrection_Remix_OS)
* Device Brand `Google` Model `Pixe`
* [x] "Mozilla/5.0 (Linux; Android 10; sailfish) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.86 Safari/537.36"

### Slimroms (https://en.wikipedia.org/wiki/SlimRoms)
* https://slimroms.org/#/device/hydrogen
* [x] "Mozilla/5.0 (Linux; Android 7.1.2; hydrogen) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Mobile Safari/537.36"
* Device Brand `Xiaomi` - Model `Mi Max`
* [x] Mozilla/5.0 (Linux; Android 5.1.1; kenzo) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.96 Mobile Safari/537.36

Do I need to add such detections?

https://en.wikipedia.org/wiki/List_of_custom_Android_distributions

**Comment by Findus23** [comment]
In case it helps you:
On my phone (using lineageOS) the user agent of the default (lineageOS) browser is:
`Mozilla/5.0 (Linux; Android 11; ONEPLUS A3003 Build/RQ2A.210405.005) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36`

I doubt there are many lineageOS builds where the browser mentions lineageOS, so I'm not sure how important this is.

**Comment by sanchezzzhak** [comment]
I checked on one of the servers, this is all that was found (the list is grouped by value)


id      | useragent                                                                                                                                                                      |
--------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
11929263|Mozilla/5.0 (Linux; Android 11; lineage_j5y17lte Build/RQ2A.210305.006) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.152 Mobile Safari/537.36       |
11746345|Mozilla/5.0 (Linux; Android 11; lineage_ss2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Mobile Safari/537.36 OPR/62.3.3146.57763                          |
 7312716|Mozilla/5.0 (Linux; Android 7.1.2; lineage_FS504 Build/NJH47F; ru-ru) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36 Puffin/7.8.2.40664AP|
 6935900|Mozilla/5.0 (Linux; Android 7.1.2; lineage_FS504) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Mobile Safari/537.36                                         |
10283195|Mozilla/5.0 (Linux; Android 9; lineage_c106 Build/PQ3A.190801.002) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 OPT/2.6                |
 8676464|Mozilla/5.0 (Linux; Android 9; lineage_c106 Build/PQ3A.190801.002) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.116 Mobile Safari/537.36            |
 8505566|Mozilla/5.0 (Linux; Android 9; lineage_c106 Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.116 Mobile Safari/537.36        |
12007593|Mozilla/5.0 (Linux; Android 9; lineage_c106) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36                                              |
11894849|Mozilla/5.0 (Linux; Android 9; lineage_c106) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.82 Mobile Safari/537.36                                               |
10363527|Mozilla/5.0 (Linux; Android 9; lineage_serranoltexx) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36                                      |

**Comment by sanchezzzhak** [comment]
I dont see the place in defining others OS without unique identifier in useragent string.
Under the code device can be any OS.

This issue will be closed with the merger or rejection of PR
