### ISSUE TITLE
two identical code for 2 brands

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6747]
https://www.imei.info/phonedatabase/95455-zuum-uniq/
**Brand Zuum Model: UNIQ**

"Mozilla/5.0 (Linux; Android 6.0; UNIQ Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 6.0; UNIQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 6.0; UNIQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.93 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 6.0; UNIQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Mobile Safari/537.36"

---
https://www.imei.info/phonedatabase/107347-celkon-uniq/
**Brand Celkon Model: UniQ**
"Mozilla/5.0 (Linux; Android 7.0; UniQ Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.126 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.91 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.105 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.112 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.136 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.62 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.90 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.96 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.119 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.99 Mobile Safari/537.36"
"Mozilla/5.0 (Linux; Android 7.0; UniQ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.117 Mobile Safari/537.36"

How do we make it so that we can detect both devices?

I can see that they have different OS versions and different character cases

we can solve this problem by using
https://www.regular-expressions.info/modifiers.html
But I'm afraid we'll break the ports to other languages
JS Fail
```js
console.log(/Celkon|(?:Millennia Hero|2GBStar|2GBXpress|(?-i:UniQ))(?:[);\/ ]|$)/is.test('UNIQ'))
```
PHP Done
```php
var_dump(preg_match(`~Celkon|(?:Millennia Hero|2GBStar|2GBXpress|(?-i:UniQ))(?:[);\/ ]|$)~is`, 'UNIQ', $math));
```

**Comment by sgiehl** [comment]
@sanchezzzhak I guess we can't rely on the writing case for checking for a specific brand. Some users might use lower or uppercase useragents with device detector, which might then fail.
Maybe we use the Android version? Guess it's unlikely someone would install an older Android version than the devices was shipped with. So if it's Android 6 we detect the first one and in all other cases the other one. Might not be fully correct, but maybe a good approach.

**Comment by sanchezzzhak** [comment]
for now I'll do as you suggested, thanks
