### ISSUE TITLE
Wrong or missing Samsung Tizen TV regex

### ISSUE THREAD

**Issue by daliusberdikslis** [matomo-org/device-detector#6759]
List of tizen os's official users agents:
https://developer.samsung.com/smarttv/develop/guides/fundamentals/retrieving-platform-information.html

**Comment by sanchezzzhak** [comment]
Hi, thank you for contacting us, we will check it out

Product | User Agent | Check
-- | -- | --
2020 models | Mozilla/5.0 (SMART-TV; LINUX; Tizen 5.5) AppleWebKit/537.36 (KHTML, like Gecko) 69.0.3497.106.1/5.5 TV Safari/537.36
2019 models | Mozilla/5.0 (SMART-TV; LINUX; Tizen 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/5.0 TV Safari/537.36
2018 models | Mozilla/5.0 (SMART-TV; LINUX; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 TV Safari/537.36
2017 models | Mozilla/5.0 (SMART-TV; LINUX; Tizen 3.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/3.0 TV Safari/538.1
2016 models | Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/2.4.0 TV Safari/538.1
2015 models | Mozilla/5.0 (SMART-TV; Linux; Tizen 2.2) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.0 TV Safari/538.1
TV SDK 3.0 | Mozilla/5.0 (SMART-TV; LINUX; Tizen 3.0) AppleWebKit/538.1 (KHTML, like Gecko) Version/3.0 TV Safari/538.1
TV SDK 2.4 | Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0; SAMSUNG sdk) AppleWebKit/538.1 (KHTML, like Gecko) Version/2.4.0 TV Safari/538.1
TV SDK 2.3.1 | Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0; SAMSUNG sdk) AppleWebKit/538.1 (KHTML, like Gecko) Version/2.4.0 TV Safari/538.1

**Comment by sanchezzzhak** [comment]
@daliusberdikslis can you check if everything is being determined correctly now?
