### ISSUE TITLE
Roku device detection ?

### ISSUE THREAD

**Issue by marcboy** [matomo-org/device-detector#6764]
I,  I can see a lot of useragent like this "Mozilla/5.0 (QSP; Roku; AP; 6.2.80.2752)" that end up not being detected to a specific device family.

I would think that this is either a Roku TV or a Roku Stick.

Is this a known issue ? Is there a way to actually return a device family for these user agents ?

**Comment by sanchezzzhak** [comment]
Hi, thank you for contacting us.

> Is this a known issue ?

nope

>  Is there a way to actually return a device family for these user agents ?

This UA belongs to the firmware.
Identify brand - yes
Identify model - no (does not contain a prefix model, at least there is no information)
Identify common model- yes (Digital Video Player)
