### ISSUE TITLE
Wrong identification of MacBook Pro and iPad Pro

### ISSUE THREAD

**Issue by CoderGeek82** [matomo-org/device-detector#6767]
- A MacBook Pro Late 2013 with OS as **macOS Big Sur version 11.4** is shown as **Mac 10.15** which is basically Catalina.
- iPad Pro (12.9 inch) (3rd generation) with **iPadOS version 14.4.2** is shown as **Mac 10.15** which is absolutely wrong.

There are many versions of apple products that are simply recognized as **Mac 10.15** whereas there is nothing in common with Catalina.

**Comment by sanchezzzhak** [comment]
Hi, write user agents that give an incorrect result.

**Comment by sgiehl** [comment]
@CoderGeek82 Please create a new issue if you are able to provide the full useragent that aren't parsed correctly. We are not able to do anything without it. Thanks!
