### ISSUE TITLE
Device identification table MOVE_S201

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6780]
Useragent:
* [x] Mozilla/5.0 (Linux; Android 6.0.1; MOVE_S201) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.117 Safari/537.36

the google list says this model refers to the brand  - JP Sacouto

There are suggestions that this is the myMaga brand:

https://www.amazon.de/-/en/Tablet-Mymaga-10-Move-S201-and6-0-32GB/dp/B0759PDSRJ

So what brand does this device belong to `JP Sacouto` or `Mymaga` ?

**Comment by liviuconcioiu** [comment]
There are one and the same company. They have almost the same website structure / design.

`J.P.SÁ COUTO` - [https://www.jpdi.pt/](https://www.jpdi.pt/)
`Mymaga` - [https://www.jpik.com/](https://www.jpik.com/) ([https://dhb3yazwboecu.cloudfront.net/446/MoveS201-EN-brochure.pdf](https://dhb3yazwboecu.cloudfront.net/446/MoveS201-EN-brochure.pdf))

**Comment by sanchezzzhak** [comment]
Hm, I think this will help later.

@liviuconcioiu  thank you.
