### ISSUE TITLE
Matomo Harmony/Huawei OS

### ISSUE THREAD

**Issue by mahsum97** [matomo-org/device-detector#6790]
i am using Matomo for my app analytics and was curious if it is possible to show Harmony/HuaweiOS besides the currently displayed Android and iOS on the Matomo Dashboard.

If i use a Huawei phone with their own OS right now, Matomo shows it as Android 10 instead of HarmonyOS. Is there a way to do that?

**Comment by sanchezzzhak** [comment]
Hello.
`HarmonyOS` Most likely, it will be impossible to add it, if there is no identifier for the OS

a similar situation was with HiOs https://github.com/matomo-org/device-detector/pull/6756#issuecomment-851543186

**Comment by mahsum97** [comment]
Hi, 
okay and how do i know which OS have an identifier and which don't? Would be great if the Matomo dashboard could list Harmony/EMUI besides Android and iOS ^^

**Comment by sanchezzzhak** [comment]
Current Huawei useragents do not contain `EMUI or Harmony ' identifiers or another identifier

in theory, you can detect OS by using unique fonts via js.
```js
const hasAndroid = navigator.platform && navigator.platform === 'Android';
const hasHarmonyOS =  hasAndroid && document.fonts.check("12px HarmonyOS Sans");  // HarmonyOS for brand Huawai 
const hasOxygenOS =  hasAndroid && document.fonts.check("12px OnePlus Sans");          // OxygenOS for brand OnePlus
```
But this is a theory and it does not apply to the current repository.

**Comment by mahsum97** [comment]
So there is currently no way to display huawei OS on Matomo? :/

**Comment by sgiehl** [comment]
@mahsum97 Seems there is no possibility to do that by now. Will close this issue, as we can't do anything about it.
