### ISSUE TITLE
Could you explain how you differ to browscap

### ISSUE THREAD

**Issue by wernight** [matomo-org/device-detector#6820]
browscap (get_browser) is a built-in function of PHP. It seems that a lot of properties are already included in both (i.e. there is a large overlap). So it'd be useful to have a pro/con in the README. A few points to possibly highlight:

  - Major features only in one or the other
  - Features that are expected to be more accurate (or giving less false positive/negative)
  - Non-reliance on browscap.ini from https://browscap.org/ (i.e. more future proof without updating this file frequenlty)

**Comment by mimmi20** [comment]
browscap has much less accurate device detection

**Comment by sgiehl** [comment]
@wernight That depends what your are looking for. Device detector won't give you any details on browser capabilities, but a lot more details on information that can be extracted from the user agent. Like if it's a bot or a normal useragent. Details on device (including model and brand), client (like browser, mobile app, pim or other software), operating system,...
