### ISSUE TITLE
Should we move the honor models to a separate brand from huawei?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6836]
https://m.gsmarena.com/huawei_officially_announces_its_sale_of_honor_will_hold_no_share_following_the_sale-news-46302.php

What do you think about this?

**Comment by sgiehl** [comment]
Good question. Guess I would leave them for now. Moving them to a new brand would at least for Matomo mean, that with a newer version comparing device stats with older dates won't work correctly for Honor models anymore, as the brand and I guess also the model would change. For single devices that usually not such a big issue. But there are quite a few Honor devices...
