### ISSUE TITLE
Box and OnePlace tvs not detected

### ISSUE THREAD

**Issue by stevenlyons** [matomo-org/device-detector#6844]
Hi All, I wanted to see about getting these UAs added to the detection:

Dalvik/2.1.0 (Linux; U; Android 8.0.0; Telia box Build/3.2.4)
type: television
brand: Telia
model: Box

Dalvik/2.1.0 (Linux; U; Android 9; S70CDS Build/PTT1.190716.001)
type: television
brand: Canal Digital
model: OnePlace

Any additional info you need?

Thanks much, 
s.

**Comment by sanchezzzhak** [comment]
Hi. the useragent will be enough.
