### ISSUE TITLE
What is the name of the new brand to use if it is busy?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6849]
Is it normal if I set the name ' Smart GSM` as a brand? 

* "Mozilla/5.0 (Linux; Android 7.0; Coral 4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Mobile Safari/537.36"
http://smartgsmphone.com/en1/coral4.htm

https://github.com/matomo-org/device-detector/blob/fb4cbb944c6a69c7d6930bc9b5aa507ac46f45b0/regexes/device/televisions.yml#L537-L545

`Smart` brand, the site was found only in the webarchive.
http://web.archive.org/web/20110814033423/http://www.smart-electronic.de/
https://www.facebook.com/smartelectronic/

**Comment by sgiehl** [comment]
What about renaming the old one to `Smart Electronic`? If the short code stays the same, this wouldn't be an issue for Matomo.

**Comment by sanchezzzhak** [comment]
okay, I will make a separate PR for adding a brand with renaming the old Smart to Smart Electronic 
after the next PR `pr_device_133`
