### ISSUE TITLE
Brand Nubia separate from ZTE?

### ISSUE THREAD

**Issue by sanchezzzhak** [matomo-org/device-detector#6869]
> Nubia Technology is a Chinese smartphone manufacturer headquartered in Shenzhen, Guangdong. Originally started as a wholly owned subsidiary of ZTE in 2012 and it became an independent company in 2015[1] and received a significant investment from Suning Holdings Group and Suning Commerce Group in 2016.[2] ZTE reduced its stake in Nubia to 49.9% in 2017 officially meaning Nubia was no longer considered a subsidiary of the company, but an associate company.[3][4]

https://en.wikipedia.org/wiki/Nubia_Technology

I have already made changes in a separate branch, and I am ready to send a PR
https://github.com/sanchezzzhak/device-detector/commit/c4003ba91954d4717bc1596f7909d53645ad9a27

yes, this will spoil the reports in the statistics, but in the future it will be right statistics.

**Comment by sgiehl** [comment]
Guess that's fine. feel free to create the PR.
