### ISSUE TITLE
Detecting Windows 11?

### ISSUE THREAD

**Issue by Tennyleaz** [matomo-org/device-detector#6928]
Currently, the user agent strings for windows 10 and 11 are both `Windows NT 10.0`, and in oss.yml they are treated as same OS.
This is Edge 96 on windows 11 looks like on my machine:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Edg/96.0.1054.29`
Could it detect windows 11 using client hint?
[Detecting Windows 11 using User-Agent Client Hints](https://docs.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11)

**Comment by sanchezzzhak** [comment]
@sgiehl 
can we define devices by array? 

base desing 
```php
$dd = new DeviceDetector()
$dd->setHeaders($_SERVER or $array);
$dd->parse();
````

the developer himself will pass the data to the header   
Example 
```php
$isUserUquid = false;   // free findgerprint  for session clienthints
$upgradeHeader = empty($_SERVER['HTTP_SEC_CH_UA_PLATFORM']);
if ($upgradeHeader) {
    header('Accept-CH: Sec-CH-UA-Full-Version, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version, Sec-CH-UA-Model, Sec-CH-UA-Arc', true);
    $isUserUquid = true;
}

$dd = new DeviceDetector()
$dd->setHeaders($_SERVER);
$dd->parse();

$os = $dd->getOs();
```

it is also an alternative way to use the library, to create a user agent from the clienthints
```php
$isUserUquid = false;   // free findgerprint  for session clienthints
$upgradeHeader = empty($_SERVER['HTTP_SEC_CH_UA_PLATFORM']);
if ($upgradeHeader) {
    header('Accept-CH: Sec-CH-UA-Full-Version, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version, Sec-CH-UA-Model, Sec-CH-UA-Arc', true);
    $isUserUquid = true;
}
if (! ($upgradeHeader) {
  $modelCh = $_SERVER['HTTP_SEC_CH_UA_MODEL'] ?? null;
  $platformCh = $_SERVER['HTTP_SEC_CH_UA_PLATFORM'] ?? null;
  $platformVersion = $_SERVER['HTTP_SEC_CH_UA_PLATFORM_VERSION'] ?? null;
  $platformArh =  $_SERVER['HTTP_SEC_CH_UA_ARH'] ?? null;
  if( $modelCh !== null) {
      $shortUA = " $platformCh/$platformVersion $platformArh; $modelCh ;";
      $dd->setUserAgent($shortUA);
      $dd->parse():
   }
}
```

**Comment by sgiehl** [comment]
@sanchezzzhak I'm not yet sure if we should implement client hint detection into device detector. I guess in most cases we couldn't use the parsers / regexes we are currently using. So we would actually need to have `UserAgentParsers` and `ClientHintParsers`, both using different detection rules. Guess that means we would need to restructure most parts of device detector... Also it might be useful to give both (useragent & client hints) for parsing, so the base results are coming from the useragent, but are overwritten with details that could be extracted from the client hints. I'm currently a bit short in time, but I will try to have some more thoughts on that next week...

**Comment by sanchezzzhak** [comment]
> Also it might be useful to give both (useragent & client hints) for parsing, so the base results are coming from the useragent, but are overwritten with details that could be extracted from the client hints. I'm currently a bit short in time, but I will try to have some more thoughts on that next week...

:+1:

**Comment by MatomoForumNotifications** [comment]
This issue has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/windows-11-recorded-as-windows-10/45882/2

**Comment by lorimode** [comment]
Mais cela vient de quoi ? de l'agent de détection Matomo ou de Firefox ? Car le problème est uniquement avec ce navigateur...
Avec Opera, Edge, cela affiche Windows 11, donc pas de problème, mais c'est avec Firefox que sa marche pas bien...

---trad google---
Mais de quoi cela vient-il ? Agent de détection Matomo ou Firefox ? Parce que le problème vient uniquement de ce navigateur...
Avec Opera, Edge, il affiche Windows 11, donc pas de problème, mais c'est avec Firefox que ça ne marche pas bien...
