### ISSUE TITLE
Samsung A series and other device support

### ISSUE THREAD

**Issue by supreetkumar-fdv** [matomo-org/device-detector#6932]
Chrome 96.0.4664.45           - Android 11; **SM-A325F** Build/RP1A.200720.012 - Not logged(Metrics Site) - No data logged (Database)

Samsung Internet 16.0.2.19 - Android 11; **SM-A325F** Build/RP1A.200720.012 - Not logged (Metrics site) - Partial logging (Database)

Chrome 96.0.4664.45           - Android 10; **SM-A326U** 

Sometimes logging not happening for Chrome 94/95 on Windows 10

Please provide device support for the above missing ones

**Comment by sgiehl** [comment]
I have just checked the useragents with latest version. All seem to be detected correctly with device detector. If they don't show up correctly in Matomo, that can be due to using an older version of Matomo, where those detections where not yet implemented.
