### ISSUE TITLE
 chanjet  Browser user agents 

### ISSUE THREAD

**Issue by onlylhf** [matomo-org/device-detector#6934]
User Agents:

 T+Browser:

- [x]  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36 T+Browser/2.3.4.1

ChanjetCloud:
- [x]  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 ChanjetCloud/77.1588.2.2

**Comment by sanchezzzhak** [comment]
ChanjetCloud It looks like it's a regular ChromeBrowser with the T+Cloud feature. (after next version  T+Browser for XP)

@onlylhf Thanx for create issue
@liviuconcioiu  Thanx for create PR

**Comment by onlylhf** [comment]
Thank you @liviuconcioiu

ChromeBrowser and T+Browser  the two Browser


 T+Browser download : 
https://dad.chanapp.chanjet.com/tplusapp/TPlusBrowser.exe

ChromeBrowser download : 
https://dad.chanapp.chanjet.com/tplusapp/HsySetup.exe

**Comment by liviuconcioiu** [comment]
@sanchezzzhak Can you please tell me what changes should I make?

**Comment by sanchezzzhak** [comment]
@onlylhf ChanjetCloud Is it possible to navigate to other sites?

**Comment by onlylhf** [comment]
> @onlylhf ChanjetCloud Is it possible to navigate to other sites?

You can navigate to other sites

**Comment by sanchezzzhak** [comment]
@liviuconcioiu

Create  new rule `ChanjetCloud/(\d\.[\d.])` for browsers.yml
name `ChanjetCloud`
