### ISSUE TITLE
Ubuntu detected fail

### ISSUE THREAD

**Issue by nekulin** [matomo-org/device-detector#6963]
```
$dd = new DeviceDetector('Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0');

var_dump($dd->isDesktop());
var_dump($dd->isMobile());
```

Return

```
bool(false)
bool(false)
```

**Comment by sanchezzzhak** [comment]
```php
$dd = new DeviceDetector('Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0');
$dd->parse();
var_dump($dd->isDesktop());
var_dump($dd->isMobile());
```
bool(true)
bool(false)

the fact is that `isMethod*` returns the pre-analyzed state, after calling the parse method

**Comment by sanchezzzhak** [comment]
@sgiehl 
https://github.com/matomo-org/device-detector/blob/15cc0ac69bced9d273f85dd7debf9d6aaea72517/DeviceDetector.php#L398-L412

can we add the code?
```php
// ...
 public function isDesktop(): bool
    {
        if (!$this->isParsed() && (string)$this->userAgent !== '') {
            $this->parse();
        }

        $osName = $this->getOsAttribute('name');

        if (empty($osName) || self::UNKNOWN === $osName) {
            return false;
        }

        // Check for browsers available for mobile devices only
        if ($this->usesMobileBrowser()) {
            return false;
        }

        return OperatingSystem::isDesktopOs($osName);
    }
``` 
then the example from the first message will work, and, accordingly,  will need to add such a check everywhere, also already the `setUserAgent' method resets state to false

do we need such an improvement?

**Comment by sgiehl** [comment]
@sanchezzzhak you basically mean something like what was suggested in #6497 ?

**Comment by sanchezzzhak** [comment]
Yes, looks like it.

**Comment by sgiehl** [comment]
I guess we could at some point consider to refactor the code, so parse is automatically called in every method that returns some results. But we should then also call reset whenever a method is called that might change the results (like `addDeviceParser`)
