### ISSUE TITLE
Duplicate brand Atvio

### ISSUE THREAD

**Issue by sgiehl** [matomo-org/device-detector#6964]
The list of brands currently contain `Atvio` and `ATVIO`. Are those brands the same or is that a possible duplicate.
It seems `Y6` was added with #6953, so if it's a duplicate we should remove that one.

**Comment by sanchezzzhak** [comment]
duplicate
`"Y6' => 'AVIO', should be deleted` "Y6' => 'AVIO', should be deleted

**Comment by sgiehl** [comment]
Can you create a fix for that? I would do another release afterwards

**Comment by sanchezzzhak** [comment]
should we create a test that checks brands for duplicates, case-insensitive?

**Comment by sgiehl** [comment]
Guess that would make sense

**Comment by sanchezzzhak** [comment]
done.
result test: duplicate brand exist
![image](https://user-images.githubusercontent.com/1337066/149387671-ebe5dc23-7e9c-4255-ba28-1a9ed7be5d9d.png)
