### ISSUE TITLE
memory leak in DeviceDetector\DeviceDetector::addClientParser()

### ISSUE THREAD

**Issue by morganus** [matomo-org/device-detector#6980]
Hi
DeviceDetector\DeviceDetector::addClientParser() method is leaking memory.
Every time  DeviceDetector\DeviceDetector object is instantiated multiple calls to addClientParser are made, and $clientTypes static property is growing indefinitely

**Comment by sanchezzzhak** [comment]
Hi, can you show a usage example full?

* latest version of device-detector?
* do you use a cache?
```php
$dd = new DeviceDetector;
$dd->setCache($adapter);
```
* php  version ?
`php -v` in console
* how much memory is allowed to the script?
`php -i | grep "memory_limit"` in console

**Comment by morganus** [comment]
I'm using "version": "5.0.2"
cache won't help because you are adding string to array directly every time DeviceDetector is instantiated

DeviceDetector
line 251: self::$clientTypes[]   = $parser->getName();
just look at the code please, you will notice it super fast

**Comment by sanchezzzhak** [comment]
in principle, this is possible with a large number of iterations in a loop in php8
```php
for($i=0; $i < 400000; $i++) {
   $dd = new DeviceDetector($useragent);
}
```

**Comment by morganus** [comment]
> in principle, this is possible with a large number of iterations in a loop in php8
> 
> ```
> for($i=0; $i < 400000; $i++) {
>    $dd = new DeviceDetector($useragent);
> }
> ```

and that's how we find it, in long running process which was constantly eating our memory, thank you @sanchezzzhak  for quick reaction

**Comment by sanchezzzhak** [comment]
I recommend using once instance, it will speed up processing.

$dd = new DeviceDetector();
```php
//loop start
$dd->setUserAgent($useragent);
$dd->parse();

$deviceType = $dd->getDeviceName();
$deviceBrand = $dd->getBrandName();
$deviceModel = $dd->getModel();
$os = $dd->getOs();
$client = $dd->getClient();
// loop end
```
