### ISSUE TITLE
Minor syntax errors in some of the regular expressions

### ISSUE THREAD

**Issue by nickcampbell18** [matomo-org/device-detector#6990]
Hi folks!

I'm using the [Ruby library](https://github.com/podigee/device_detector) which incorporates the regular expressions unchanged from this repository. The regex engine in Ruby, [Oniguruma](https://github.com/kkos/oniguruma), is detecting a couple of issues:

```
warning: regular expression has ']' without escape
warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
```

A ticket was originally raised [on the Ruby repo](https://github.com/podigee/device_detector/issues/89) but the maintainer has indicated that they would prefer this to be fixed upstream (apologies, if this ticket has already been submitted before, but I could not find it).

Since we're all using PCRE-compatible engines, I hope you would welcome a patch to update these regular expressions and benefit the wider ecosystem? @hendrixfan wrote [this PR](https://github.com/podigee/device_detector/pull/90/files) which I believe would do the trick, if they are interested in contributing here and you would welcome the change.

Secondly, assuming you are onboard with this change, would you also welcome adding a component to your GitHub actions which runs all of the configured regular expressions through some kind of validator? That would also protect us in future from a similar regression. I had a quick look but I couldn't find a PHP library which does this (perhaps this is why the issue was spotted on the Ruby repo..?). I would happily contribute such a GitHub action, if desired.

Thanks!

**Comment by sanchezzzhak** [comment]
Oniguruma was removed from PHP in 7.4 for mbstring.
from 5.1 - 7.2, this engine can be called via `mb_ereg`, but how much it corresponds to Ruby, I can't even aware

some expressions will have to be changed
from `[a-z]+` to `[a-z]{1,}`, since "*" doesn't work a bit like "+"
