### ISSUE TITLE
Using without composer v5.0.4

### ISSUE THREAD

**Issue by indramal** [matomo-org/device-detector#7009]
How to use a device detector without a composer? I need to download the zip file and use it.

Code:

`<?php
include_once 'device-detector/Yaml/Spyc.php';
include_once 'device-detector/autoload.php';
//include 'device-detector/DeviceDetector.php';
use DeviceDetector\DeviceDetector;
$dd = new DeviceDetector();
$dd->parse();
$clientInfo = $dd->getClient();
var_dump($clientInfo);
?>`

This code work up to `use DeviceDetector\DeviceDetector;` line.

**Comment by liviuconcioiu** [comment]
You need this Spyc.php file to include:
[https://github.com/mustangostang/spyc/blob/master/Spyc.php](https://github.com/mustangostang/spyc/blob/master/Spyc.php)

**Comment by sanchezzzhak** [comment]
1 download DeviceDetector and extract dir lib/spyc
2 download https://github.com/mustangostang/spyc and extract dir lib/device-detector
```php
<?php
 include_once __DIR__ . '/lib/spyc/Spyc.php'; 
 include_once __DIR__ . '/lib/device-detector/autoload.php'; 

use DeviceDetector\DeviceDetector;

$dd = new DeviceDetector;
$dd->setUserAgent($string)
$dd->parse();
var_dump($dd->getClient()); 
```

**Comment by indramal** [comment]
`$dd->parse(); `and after that not working.

Full Code
```
<?php
 include_once __DIR__ . '/lib/spyc/Spyc.php'; 
 include_once __DIR__ . '/lib/device-detector/autoload.php'; 

use DeviceDetector\DeviceDetector;

$dd = new DeviceDetector;
$string = $_SERVER['HTTP_USER_AGENT'];
$dd->setUserAgent($string);
$dd->parse();
var_dump($dd->getClient()); 
?>
```

**Comment by indramal** [comment]
I did following trick to stop location

```
<?php

 echo "aa";
 include_once __DIR__ . '/lib/spyc/Spyc.php'; 
 include_once __DIR__ . '/lib/device-detector/autoload.php'; 
echo "bb";
use DeviceDetector\DeviceDetector;
echo "cc";
$dd = new DeviceDetector;
echo "dd";
$string = $_SERVER['HTTP_USER_AGENT'];
$dd->setUserAgent($string);
echo "ee";
$dd->parse();
echo "ff";
var_dump($dd->getClient()); 
?>
```

It gives 

> aabbccddee 

output. Which mean it is stop in `$dd->parse();` line

**Comment by sanchezzzhak** [comment]
[example-without-composer.zip](https://github.com/matomo-org/device-detector/files/8104302/example-without-composer.zip)

extract archive
open console
cd example-without-composer/
php -S localhost:8001
open browser for url http://localhost:8001

if you tried running your code in the console, it won't work, since $_SERVER['HTTP_USER_AGENT'] won't be in the Cli

**Comment by indramal** [comment]
I did not get your point. Can you explain me? 

Your code is working. Thank you very much. I use it in the hosting server, not on the local server.

**Comment by sanchezzzhak** [comment]
Has issue been resolved?
