### ISSUE TITLE
how can i get the mobile model as same as regex include or same as registe in miit

### ISSUE THREAD

**Issue by yangnj1984** [matomo-org/device-detector#7013]
eg 
Mozilla/5.0 (Linux; Android 9; MHA-AL00; HMSCore 6.0.0.305; GMSCore 19.6.29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.93 HuaweiBrowser/11.1.3.300 Mobile Safari/537.36

how can i get MHA-AL00 instead Mate 9

or can a function return the match regex

**Comment by liviuconcioiu** [comment]
@yangnj1984 you can also use client hints if you want to get the model in real-time. $_SERVER['HTTP_SEC_CH_UA_MODEL'] contains the info you need.
