### ISSUE TITLE
Memcache Cache Setup?

### ISSUE THREAD

**Issue by sv3t0sl4v** [matomo-org/device-detector#7042]
How to set up? Readme does not say, except it is possible. Should be fastest, I guess RAM is always faster than any disk or array of disks.

**Comment by sgiehl** [comment]
You may need to provide a custom caching class, that is compatible with one of the bridges we provide:
https://github.com/matomo-org/device-detector/tree/master/Cache

**Comment by sanchezzzhak** [comment]
you can create your own cache, just follow the interface
example custom cache adapter for Yii2 Framework

```php

use DeviceDetector\Cache\CacheInterface;

class DeviceDetectorCache implements CacheInterface
{
    public function contains($id): bool
    {
        return Yii::$app->cache->get($id) !== false;
    }

    public function fetch($id)
    {
        return Yii::$app->cache->get($id);
    }

    public function delete($id): bool
    {
        return Yii::$app->cache->delete($id);
    }

    public function flushAll(): bool
    {
        return Yii::$app->cache->flush();
    }

    public function save($id, $data, $lifeTime = 0): bool
    {
        return Yii::$app->cache->set($id, $data, $lifeTime);
    }

} 
```
usage 
```
$dd = new DeviceDetector;
$dd->setCache( new DeviceDetectorCache);
$dd->setUserAgent($userAgentString);
$dd->parse();
```

**Comment by Findus23** [comment]
In case you mean memcached instead of memcache, you can look at the tests for an example on how to use it:
https://github.com/matomo-org/device-detector/blob/a7d5eb349c9f930944fed7ed1a7abea604ea382e/Tests/DeviceDetectorTest.php#L152-L155
