### ISSUE TITLE
Linux Version Not Returned?

### ISSUE THREAD

**Issue by sv3t0sl4v** [matomo-org/device-detector#7043]
Tried on Ubuntu 20.04. I only see Ubuntu without the "20.04" as it returns empty string. Is it even possible to detect distro version? All I guet is `Array ( [name] => Ubuntu [short_name] => UBT [version] => [platform] => x64 ) `

**Comment by liviuconcioiu** [comment]
If version is not in user agent or in client hints it cannot be detected.

**Comment by sgiehl** [comment]
@sv3t0sl4v If your useragent or client hints contain more details that are not correctly detected, feel free to comment those data here and we will reopen the issue and check that.

**Comment by sv3t0sl4v** [comment]
I was not able to try client hints. Will create a separate question about it. Then I will submit, if that fails when I mange to run it.
