### ISSUE TITLE
Version Check?

### ISSUE THREAD

**Issue by sv3t0sl4v** [matomo-org/device-detector#7048]
How do I check which version I have? When I run the composer command it says:

`Using version ^3.13 for matomo/device-detector`

What!? Right now the latest is 5.0.5, right?

**Comment by sgiehl** [comment]
You can always see that in
https://github.com/matomo-org/device-detector/blob/62afcc9e2a374c1b7f1b119d2083f2f6cf90e93a/DeviceDetector.php#L71

If you have an older version maybe your composer requirement is wrong.

**Comment by Findus23** [comment]
Which PHP version are you (or rather is composer) using?
The latest version needs at least PHP 7.2 and 3.13.1 is the last version supporting older versions. (keep in mind that if you indeed use PHP <7.2 you should update as soon as possible.

**Comment by sv3t0sl4v** [comment]
OK. Got it. I use PHP 7.1, so that's why. Will try with PHP 7.4, too.
