### ISSUE TITLE
TVs detected as smartphone

### ISSUE THREAD

**Issue by stevenlyons** [matomo-org/device-detector#7066]
The following UAs are detected as smartphone but are all TVs:

- [x] Dalvik/2.1.0 (Linux; U; Android 9; BRAVIA 4K UR3 Build/PTT1.190515.001.S104)
- [x] Dalvik/2.1.0 (Linux; U; Android 10; BRAVIA VH1 Build/QTG3.200305.006.S89)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; BRAVIA 4K UR1 Build/PTT1.190515.001.S104)
- [x] Dalvik/2.1.0 (Linux; U; Android 10; BRAVIA 4K VH2 Build/QTG3.200305.006.S118)
- [x] Dalvik/2.1.0 (Linux; U; Android 11; BRAVIA VU1 Build/RTT7.210105.001)

- [x] Dalvik/2.1.0 (Linux; U; Android 9; AQUOS-TVX19A Build/PTM5.200218.685)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; AQUOS-TVX19B Build/PTM5.200218.646)
- [x] Dalvik/2.1.0 (Linux; U; Android 10; AQUOS-TVJ21-2 Build/QTG3.200913.001)
- [x] Dalvik/2.1.0 (Linux; U; Android 10; AQUOS-TVX21A Build/QTG3.200913.001)

- [x] Dalvik/2.1.0 (Linux; U; Android 9; EKO Android TV Build/PTO2.210527.001)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; EKO Android TV 2K Build/PTO3.201213.001)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; EKO 2K Android TV Build/PTO6.200615.001)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; EKO 4K Android TV Build/PTO6.200610.001)

- [x] Dalvik/2.1.0 (Linux; U; Android 9; Kogan TV Build/PTO2.210830.001)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; Kogan SmarterTV Build/PTO3.201213.001)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; Kogan SmarterTV 2K Build/PTMW.190511.120)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; KoganTVAP Build/PTO7.200925.001)

- [x] Dalvik/2.1.0 (Linux; U; Android 9; Vodafone TV Build/PI)

- [x] Dalvik/2.1.0 (Linux; U; Android 9; MIBOX3 Build/PI)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; MIBOX4 Build/PI)

**Comment by sanchezzzhak** [comment]
All devices have been added to master branch, thank you all for participating.
