### ISSUE TITLE
Some iPads devices are not being detected

### ISSUE THREAD

**Issue by enyeli** [matomo-org/device-detector#7076]
For example: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko).

iPad 10.2 2020

The methods isTablet() and isMobile() returns false.

**Comment by sanchezzzhak** [comment]
Bonjour.

The user agent changes, if the desktop mode is used on the iPad.
There's nothing can do about. :crying_cat_face: 

useragent 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
for macbook air

**Comment by workflo** [comment]
Hi @sanchezzzhak,

we stumbled across a similar / the same problem here:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko)`
( http://devicedetector.net/?ua=Mozilla%2F5.0+%28Macintosh%3B+Intel+Mac+OS+X+10_15_6%29+AppleWebKit%2F605.1.15+%28KHTML%2C+like+Gecko%29 )
is currently resolved as

operating system: Mac 10.15
client (UNK) / UNK UNK
desktop device / Apple

Is there a reason it cannot be resolved to a meaningful client name? 

Thanks in advance,
Florian.

**Comment by sanchezzzhak** [comment]
Hi o/
The current lib device-detection based of the user agent string and also ClientHints
The fact is that when the tablet user agent emulates the work of the desktop, it looks the same as if it was a user with a macbook.

to identify the user's device type, additional JavaScript is required on the site page
one of hundreds of examples:
```
const is Ipad = navigator.platform === 'Mac Intel' && navigator.maxTouchPoints > 0
```

**Comment by workflo** [comment]
I see, so the above UAS is not unambiguous.

Thanks anyways :)
