### ISSUE TITLE
Blackview A70

### ISSUE THREAD

**Issue by chris-spencer** [matomo-org/device-detector#7113]
Hoping this is the correct place to share this

**Blackview A70** is not being detected.
Here is the UA I took from the device

Mozilla/5.0 (Linux; Android 11; A70) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.61 Mobile Safari/537.36

Do I need to provide anything else to help?

**Comment by sanchezzzhak** [comment]
Hi,  enough UserAgent

* [ ] BlackView A70 Pro
Mozilla/5.0 (Linux; Android 11; A70 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Mobile Safari/537.36

* [ ] Unknown 
Mozilla/5.0 (Linux; Android 9.1; A70 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.181 Mobile Safari/537.36

* [ ] Unknown
Mozilla/5.0 (Linux; arm_64; Android 6.0; A70) AppleWebKit/537.36 (KHTML, like Gecko)Chrome/89.0.4389.128 YaBrowser/21.3.2.144.00 SA/3 Mobile Safari/537.36

**Comment by chris-spencer** [comment]
I've found its product page - https://www.blackview.hk/products/item/a70

Both my kids have one, so can easily test anything if needed (not a bad little cheap first phone)
