### ISSUE TITLE
Version parse error

### ISSUE THREAD

**Issue by mailzwj** [matomo-org/device-detector#7196]
Version parse result incorrect, when the Minor_Version_Number is 0. Like picture below:
<img width="2225" alt="detector bug" src="https://user-images.githubusercontent.com/1563970/182825025-2d6cb9eb-1a87-48d2-b54b-40d0a4db7878.png">
Expect:
![detector bug 2](https://user-images.githubusercontent.com/1563970/182825144-886a9804-3b62-4ec7-afce-d6507325c1a6.png)

**Comment by sanchezzzhak** [comment]
Hi. This code does not belong to this repository.
Create a issue here https://github.com/etienne-martin/device-detector-js/issues
