### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Simbiat** [matomo-org/device-detector#7223]
Not an issue, but suggestion: I've bothered enough to create a collection of icons [here](https://github.com/Simbiat/DeviceDetectorIcons) based on names of OSs and apps from regex yaml files in the library. I plan to use it for an audit page so that it won't be just text.
Since it may be useful for others doing something similar, perhaps there is a point in adding link to the collection to README of the Device Detector? Or is it too niche?

**Comment by Findus23** [comment]
Just FYI, while it doesn't cover the same set of names, Matomo Icons (https://github.com/matomo-org/matomo-icons/) might be of interest for you.

**Comment by Simbiat** [comment]
It is a nice collection as well, but it may not be as convenient to use with Device Detector. I've added a sample code to readme of my repository.

**Comment by Findus23** [comment]
Indeed, but just to document it: You can use matomo-icons using the same code that Matomo uses which I simplified here:
https://github.com/Findus23/devicedetector.net/blob/master/src/IconPath.php

for use at https://devicedetector.lw1.at

**Comment by Simbiat** [comment]
Maybe then both should be mentioned in README for Device Detector?

**Comment by Simbiat** [comment]
Updated my library of icons and remembered about this thread today 😅 So, should we add links to the 2 packs to README? I can create a PR, but I certainly do not want to make it look like I am shamelessly advertising my own library
