### ISSUE TITLE
Wrong detection of iPad 9th

### ISSUE THREAD

**Issue by kuba-end** [matomo-org/device-detector#7226]
## Expected Behavior
During using browserstack with iPad 9th choosed, I wish that method isMobile() will return true.

## Current Behavior
Currently during using browserstack with iPad 9th choosed, method isMobile() returning false.

## Possible Solution
Maybe list od devices is old. iPad 9th is fresh device

## Steps to Reproduce (for Bugs)
1.use isMobile() method to detect hour device when using iPad 9th

## Your Environment

* Matomo Version: 5.0.4
* PHP Version: 7.4

**Comment by sanchezzzhak** [comment]
The definition of the device type is based on Useragent
We need a userAgent, you can use this site to get it.
https://devicedetector.lw1.at/

**Comment by kuba-end** [comment]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15

**Comment by kuba-end** [comment]
![IMG_20220829_131859165~2.jpg](https://user-images.githubusercontent.com/57114627/187189854-de1b5b1f-9e58-442b-b95e-a4a2245f16ae.jpg)

**Comment by sgiehl** [comment]
@kuba-end Are you using the desktop mode in the browser? I actually can't see any identifiers in the useragent that would point to an iPad, so I doubt we can improve anything there. Is that right @sanchezzzhak ?

**Comment by sanchezzzhak** [comment]
It's true. When using desktop mode on iPad, the user agent will always look like a desktop.
You can only define an ipad in desktop mode in JS
```js
const isIPadOs = navigator.maxTouchPoints &&
    navigator.maxTouchPoints > 2 &&
    /MacIntel/.test(navigator.platform);
```
this is beyond the scope of this repository, at the moment.
