### ISSUE TITLE
Sync Samsung Galaxy S22 device detection to etienne-martin/device-detector-js

### ISSUE THREAD

**Issue by zetti-caletti** [matomo-org/device-detector#7239]
Galaxy S22 device detection is supported in [matomo-org/device-detector](https://github.com/matomo-org/device-detector) but not in [etienne-martin/device-detector-js](https://github.com/etienne-martin/device-detector-js).

Please sync. Thank you :)

**Comment by sgiehl** [comment]
Hi @zetti-caletti 
Sorry for the delay in answering. As this is the source repository of the definitions, you may want to create such a request in [etienne-martin/device-detector-js](https://github.com/etienne-martin/device-detector-js) instead.
We can't sync anything there.

**Comment by zetti-caletti** [comment]
Sorry I misunderstood it. When creating an issue at etienne-martin/device-detector-js it says "⚠️ Missing/incorrect detections should be reported at https://github.com/matomo-org/device-detector/issues instead of this repo."
Thought that the author of the other library is someone from matomo who is able to sync or I don't know.^^

**Comment by sgiehl** [comment]
@etienne-martin there hadn't been too many false positives yet, so all good from our side.
Haven't had a look how your fork uses the definitions, but maybe it would be possible to kind of sync them using a github action or similar, so the don't fall behind? 🤔
