### ISSUE TITLE
Unable to detect Pixel 6

### ISSUE THREAD

**Issue by dsubo** [matomo-org/device-detector#7245]
The UA string is Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Mobile Safari/537.36

I came here from this project
https://github.com/etienne-martin/device-detector-js/

**Comment by sanchezzzhak** [comment]
https://iehol.sse.codesandbox.io/#Mozilla/5.0%20(Linux;%20Android%2012;%20Pixel%206)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/105.0.0.0%20Mobile%20Safari/537.36

The pixel 6 added to current repository. 
as for device-detector-js, the creator of the port must update his project himself.

you can use the node-device-detector alternative

@etienne-martin can you update your port in the near future?
