### ISSUE TITLE
Latest Version 6.0.4 in the matomo 4.13.0 missing lastest regex entry

### ISSUE THREAD

**Issue by bitsky6** [matomo-org/device-detector#7325]
I am using the matomo docker 4.13.0 with latest matomo but the device-detector mobile.yml is missing many of the regex entry's.
Version is written is 6.0.4 but here on git I can see that should include some of the latest changes.

Thanks

**Comment by sanchezzzhak** [comment]
Hi.  Matomo uses only stable [releases](https://github.com/matomo-org/device-detector/releases), the master branch is used for development for future versions.
New versions are usually released once a month or within 2-3 months, it all depends on the workload of the team.
