### ISSUE TITLE
WebKitGTK-based web browsers (on Linux) are considered to be "Safari" in Matomo reports

### ISSUE THREAD

**Issue by nekohayo** [matomo-org/device-detector#7340]
## Current Behavior

When visiting a Matomo-tracked website using [GNOME Web](https://wiki.gnome.org/Apps/Web/) (a.k.a. [Epiphany](https://en.wikipedia.org/wiki/GNOME_Web)), Matomo interprets it as being "Safari on Linux", which doesn't exist, strictly speaking:

![2023-01-25 epiphany as seen by Matomo](https://user-images.githubusercontent.com/479401/214632520-dc95a39a-e670-4251-88a6-4ab8ab2dfd82.png)

Note that Epiphany is using WebKitGTK, which is not strictly the same as WebKit vanilla.

## Expected Behavior

Ideally, Matomo should find a way to detect which webkit-based Linux browser the user is using, or at least report it as WebKit on Linux or something separate than Safari.

## Possible Solution

I know that user agent strings are an [unresolved mess of epic proportions](https://webaim.org/blog/user-agent-string-history/) in the industry, but I don't know what else to suggest; nothing else has been adopted yet, as far as I've been told.

Visiting some user agent tester website with Epiphany "technology preview" (the dev version that will become Epiphany / GNOME Web 44), I can see this being the user agent:

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15`

Essentially, I think the only differentiator is that it's on "Linux" rather than on macOS or iOS (and even then, in mobile versions it has to pretend like it's Safari on iOS...). I am told that "Adding application branding to the user agent header is not web compatible; notably, Epiphany does not do so anymore", so you probably have to do the interpretation on the Matomo side... at least, we can't really call it Safari.

## Your Environment

* Matomo Version: 4.13.1
* PHP Version: 7.4.33
* Server Operating System: CentOS Stream 8
* Additionally installed plugins: none
* Browser: GNOME Web
* Operating System: Fedora 37 (Linux)

**Comment by mcatanzaro** [comment]
We don't support client hints, but if we did, we would use them to lie. From WebKit's perspective, we don't really want to make device detection easy.

**Comment by sgiehl** [comment]
In that case, let me simply close this issue 🙈
