### ISSUE TITLE
add Morningscore Bot to the List of detected bots

### ISSUE THREAD

**Issue by rokmorningscore** [matomo-org/device-detector#7363]
Hi,

At [morningscore](https://morningscore.io), we would like to add our bot to the List of detected bots.

The user agent name is: Morningscore Bot

Thanks !

**Comment by sanchezzzhak** [comment]
Hi, thanks for contacting us.
Bot added to PR.

If you want to change something, write about it.
For example add
```
producer:
  name:
  url:
```
