### ISSUE TITLE
Fix Morningscore Bot entry

### ISSUE THREAD

**Issue by rokmorningscore** [matomo-org/device-detector#7369]
Hey, the Morning Score in the list of bot is not correct - it should be Morningscore Bot.

Could you please add a fix - i've mentioned it in the below reply:

_Originally posted by @rokmorningscore in https://github.com/matomo-org/device-detector/issues/7363#issuecomment-1451893728_

**Comment by sanchezzzhak** [comment]
Hi, sorry for my inattention.
PK for fix has been created
