### ISSUE TITLE
Incorrectly detected Android version.

### ISSUE THREAD

**Issue by meowoo11** [matomo-org/device-detector#7371]
Hi,

I would like to report on incorrectly detected operating system - my phone (Samsung Galaxy S8 with Exynos SOC) is on Android 9 (which was correctly detected on Firefox), but in Chrome it was detected as Android 10 (I don't know why in "HTTP_USER_AGENT" there is a string "Linux; Android 10; K", maybe you'll figure it out).

Below are the headers sent from browsers (but I'm deliberately omitting the "HTTP_COOKIE", "HTTP_HOST", "HTTP_ORIGIN" and "HTTP_REFERER" for my privacy's sake).

These are the headers from Firefox (Firefox Nightly 111.0a1 (Build #2015931819)):

'HTTP_AUTHORIZATION' => ''
'HTTP_USER_AGENT' => 'Mozilla/5.0 (Android 9; Mobile; rv:109.0) Gecko/111.0 Firefox/111.0'
'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'
'HTTP_ACCEPT_LANGUAGE' => 'en-US'
'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
'HTTP_CONNECTION' => 'keep-alive'
'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
'HTTP_SEC_FETCH_DEST' => 'document'
'HTTP_SEC_FETCH_MODE' => 'navigate'
'HTTP_SEC_FETCH_SITE' => 'same-origin'
'HTTP_SEC_FETCH_USER' => '?1'
'HTTP_DNT' => '1'
'HTTP_SEC_GPC' => '1'

And there are the headers from Chrome (Ungoogled Chromium 97.0.4692.71, in "About Chrome" section, is sees Android 9 correctly):

'HTTP_AUTHORIZATION' => ''
'HTTP_CONNECTION' => 'keep-alive'
'HTTP_CACHE_CONTROL' => 'max-age=0'
'HTTP_SEC_CH_UA' => '"Chromium";v="97", " Not;A Brand";v="99"'
'HTTP_SEC_CH_UA_MOBILE' => '?1'
'HTTP_SEC_CH_UA_PLATFORM' => '"Android"'
'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
'HTTP_DNT' => '1'
'HTTP_USER_AGENT' => 'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.0.0 Mobile Safari/537.36'
'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
'HTTP_SEC_FETCH_SITE' => 'same-origin'
'HTTP_SEC_FETCH_MODE' => 'navigate'
'HTTP_SEC_FETCH_USER' => '?1'
'HTTP_SEC_FETCH_DEST' => 'document'
'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br'
'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9'

All above was tested with DeviceDetector 6.1.0.

Hope it will contribute to better detection of Device Detector!

**Comment by sanchezzzhak** [comment]
Hi.
You should use СlientHints, with maximum entropy.

> "HTTP_USER_AGENT" there is a string "Linux; Android 10; K", maybe you'll figure it out).

https://www.chromium.org/updates/ua-reduction/#proposed-rollout-plan
