### ISSUE TITLE
iPhone problem detecting exact model

### ISSUE THREAD

**Issue by DegrizNet** [matomo-org/device-detector#7390]
Hello,

I encountered an issue when using the code from the example. Specifically, when attempting to detect the iPhone 12 model by calling ($model = $dd->getModel();) for iPhone phones, I only get "iPhone" as the result. I have checked the mobiles.yml file and verified that the regex rules are there.

`    # specific smartphone devices
    - regex: '(?:MDCR_|ICRU_|Apple-)?iPh(?:one)?1[C,_]1'
      model: 'iPhone'
      device: 'smartphone'
    - regex: '(?:MDCR_|ICRU_|Apple-)?iPh(?:one)?1[C,_]2'
      model: 'iPhone 3G'
      device: 'smartphone'
...
    - regex: '(?:MDCR_|ICRU_|Apple-)?iPh(?:one)?13[C,_]2| 12\)$'
      model: 'iPhone 12'
      device: 'phablet'
    - regex: '(?:MDCR_|ICRU_|Apple-)?iPh(?:one)?13[C,_]3| 12PRO\)$'
      model: 'iPhone 12 Pro'
      device: 'phablet'`

What could be a problem? Am I doing something wrong?

**Comment by mimmi20** [comment]
@DegrizNet Please add the useragent your device is using.

**Comment by sanchezzzhak** [comment]
By default, the Iphone does not send what this particular model is in its browsers.
therefore, you will always receive the model of the Iphone device.

as for the rules, some rules are made for specific applications where there are device model identifiers.

for example: facebook, instagram

**Comment by DegrizNet** [comment]
> By default, the Iphone does not send what this particular model is in its browsers. therefore, you will always receive the model of the Iphone device.
> 
> as for the rules, some rules are made for specific applications where there are device model identifiers.
> 
> for example: facebook, instagram

So there is no way to detect it correctly? Or is there a workaround?

**Comment by sanchezzzhak** [comment]
via User Agent string no.
this is possible via JS, but you will need to make a size map and GPU models, this is not possible within this project

**Comment by sanchezzzhak** [comment]
@DegrizNet you can take a look at this solution
(I've started experimenting, share the data with me if you have an Iphone)
https://github.com/sanchezzzhak/node-device-detector/blob/pr_device_info94/client.js

From the ready-made on the market, what I found:
https://github.com/51Degrees/Renderer/blob/master/renderer.js
https://51degrees.com/blog/upgrade-apple-device-detection  (algoritm for canvas matrix4 hash)

there are also 2-3 solutions that I didn't like and work on a similar principle:
DeviceAtlas -
https://deviceatlas.com/products/deviceassure
https://cdn.devicevalidation.io/latest/dv.min.js (algoritm for image hash 2d)

https://theapicompany.com/device-detection-api/
https://theapicompany.com/wp-content/litespeed/cssjs/bcd54.js?94b81 - (algoritm for canvas matrix4 hash)

https://www.scientiamobile.com/terms-of-service-wurfl-js-lite/
(an unusual solution for calculating the hash using hashing operations.)

51degrees.com - 
my favorite, they have a very good blog to understand why it's done this way.
They also criticize Apple, which is also right, I share their point of view.
