### ISSUE TITLE
Add Wiko K-KOOL

### ISSUE THREAD

**Issue by atom-box** [matomo-org/device-detector#7429]
A user has reported a device that Google Analytics detects but Matomo does not: 

> I have noticed one difference. 
> Matomo displays Device brand = Unknown (3,880 visits), such information isn't shown in GA, but the brand Wiko K-KOOL is at the very top there. 

In the actual data table (redacted here), we see the following

**Google** detects these top 4 devices
1. Wiko K-KOOL
2. Apple iPhone
3. Samsung
4. Samsung

**Matomo** detects these top 4 devices

1. Unknown
2. Apple iPhone
3. Samsung
5. Samsung

ute to "Wiko K-KOOL"

**Comment by sanchezzzhak** [comment]
Hi, 
well, it's clear about Google, there is a detailed investigation here
https://medium.com/@gustavo_oshiro_3/device-wiko-k-kool-appearing-on-google-analytics-ua-5ab6b4673773

To identify the device, you need a User Agent and client-hints

this is data from my custom analytics
```json
{
  "event_type": 1,
  "headers": {
    "HTTP_SEC_CH_UA": "\"Not.A\/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\"",
    "HTTP_SEC_CH_UA_ARCH": "\"\"",
    "HTTP_SEC_CH_UA_BITNESS": "\"\"",
    "HTTP_SEC_CH_UA_FULL_VERSION": "\"114.0.5735.196\"",
    "HTTP_SEC_CH_UA_FULL_VERSION_LIST": "\"Not.A\/Brand\";v=\"8.0.0.0\", \"Chromium\";v=\"114.0.5735.196\", \"Google Chrome\";v=\"114.0.5735.196\"",
    "HTTP_SEC_CH_UA_MOBILE": "?1",
    "HTTP_SEC_CH_UA_MODEL": "\"Mi 9 SE\"",
    "HTTP_SEC_CH_UA_PLATFORM": "\"Android\"",
    "HTTP_SEC_CH_UA_PLATFORM_VERSION": "\"10.0.0\"",
    "HTTP_SEC_CH_UA_WOW64": "?0"
  },
  "user_agent": "Mozilla\/5.0 (Linux; Android 10; K) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/114.0.0.0 Mobile Safari\/537.36",
}
```
In the current implementation, Device Detector will not return the brand name
I have a thought, we can replace the "K)" with the device code from the client-hints

By the way, the Wiko K-KOOL device
Has User Agent
```
Mozilla/5.0 (Linux; Android 6.0; K-KOOL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36
```
Updating the browser on OS < 6 is very problematic.
