### ISSUE TITLE
Detect User Agend Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0) Image size by Siteimprove.com as bot

### ISSUE THREAD

**Issue by satzlinger** [matomo-org/device-detector#7434]
Please add detection support for the Siteimprove Image size tracker with the user agent

`Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0) Image size by Siteimprove.com`

as stated on

https://help.siteimprove.com/support/solutions/articles/80000448553-what-ip-addresses-and-user-agents-are-used-by-siteimprove-
so the bot gets ignored by matomo.
Many Thanks

**Comment by sgiehl** [comment]
@sanchezzzhak Do you have some time to add that one?

**Comment by sanchezzzhak** [comment]
Yes I'll add it now

**Comment by satzlinger** [comment]
Thank you for this really quick implementation :tada:
