### ISSUE TITLE
Add Google-InspectionTool

### ISSUE THREAD

**Issue by metmarkosaric** [matomo-org/device-detector#7449]
Is it possible to add Google-InspectionTool to the bot list please?

This is the bot they use in Google Search Console > URL Inspection > Live URL Test. It is supposed to identify itself with: 

`Mozilla/5.0 (compatible; Google-InspectionTool/1.0;)`

Thanks!

**Comment by sgiehl** [comment]
fixed with #7450

**Comment by metmarkosaric** [comment]
thank you @sgiehl!
