### ISSUE TITLE
Unable to detect device type

### ISSUE THREAD

**Issue by cool51** [matomo-org/device-detector#7455]
For Exo Player it is unable to detect device type for  user agent
(Linux; U; Android 9; SMART TV Build/PPR2.180905.006.A1)
but can detect for 
(Linux; U; Android 10; BRAVIA VH1 Build/QTG3.200305.006.S313) as smartphone

**Comment by sgiehl** [comment]
Hi @cool51 
device detector can only detect details that are provided in the useragent. Both useragent you provided are correctly detected as TV, while the latter one is also containing a specific model. Can't see any problems there.

**Comment by sanchezzzhak** [comment]
![IMG_20230617_014349](https://github.com/matomo-org/device-detector/assets/1337066/c5087e2d-31c9-468b-b102-e500aa4835b2)

Useragent for tv brand kiwi
