### ISSUE TITLE
Improve Sony Bravia TV detection

### ISSUE THREAD

**Issue by stevenlyons** [matomo-org/device-detector#7458]
The following UAs are TVs but currently detected as smartphone
Dalvik/2.1.0 (Linux; U; Android 11; BRAVIA VU31 Build/RTK2.220814.001)
Dalvik/2.1.0 (Linux; U; Android 11; BRAVIA VU2 Build/RTT7.210923.001)

Rather then detect each VU version (version VU1 is correct, based on an earlier submission), could "BRAVIA VU" be detected more generally as TV?

**Comment by sgiehl** [comment]
should be fixed with https://github.com/matomo-org/device-detector/pull/7459
