### ISSUE TITLE
Lemco Devices not detected

### ISSUE THREAD

**Issue by alexmougios** [matomo-org/device-detector#7474]
Mozilla/5.0 (Lemco FBX-3566; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36
 
Mozilla/5.0 (Lemco FBX-3566W; Linux aarch64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36

**Comment by sanchezzzhak** [comment]
Hello, a very specific device, do you have any information about what kind of devices they might be?

**Comment by alexmougios** [comment]
more info here https://lemco.gr
