### ISSUE TITLE
Sometime wrong result and need support to identify GPTBot

### ISSUE THREAD

**Issue by cpatel22** [matomo-org/device-detector#7476]
Sometime wrong result : may be thread issue or internal exception 
Also need support to identify GPTBot

https://platform.openai.com/docs/gptbot

**Comment by sgiehl** [comment]
Hi @cpatel22 
Sorry, but you issue is a bit unspecific to help in any way.
GPTBot should already be detected. See https://github.com/matomo-org/device-detector/blob/master/regexes/bots.yml#L3414-L3420
Not sure if that was already included in the last release, but it for sure will be in the next if not.

**Comment by cpatel22** [comment]
![image](https://github.com/matomo-org/device-detector/assets/7018966/718cfdc3-c9e8-46cc-9eff-89e11b4b237f)

Check this.

**Comment by sgiehl** [comment]
This is the result of the current checkout:
https://devicedetector.lw1.at/Mozilla%2F5.0%20AppleWebKit%2F537.36%20(KHTML,%20like%20Gecko;%20compatible;%20GPTBot%2F1.0;%20+https:%2F%2Fopenai.com%2Fgptbot)

Maybe it's not included in the version you are using. But we will release a new version shortly.
