### ISSUE TITLE
Opera Mini detected as Opera Mobile

### ISSUE THREAD

**Issue by koekaverna** [matomo-org/device-detector#7484]
I tried this user agent: `Opera/9.80 (Android; Opera Mini/36.2.2254/119.132; U; id) Presto/2.12.423 Version/12.16)`
And it's detected as `Opera Mobile`, not `Opera Mini`

```
  "type" => "browser"
  "name" => "Opera Mobile"
  "short_name" => "OM"
  "version" => "10.54"
  "engine" => "Presto"
  "engine_version" => "2.5.25"
  "family" => "Opera"
```

**Comment by liviuconcioiu** [comment]
@koekaverna probably you are using an older version. `Opera Mini` is detected successfully https://devicedetector.lw1.at/Opera%2F9.80%20(Android;%20Opera%20Mini%2F36.2.2254%2F119.132;%20U;%20id)%20Presto%2F2.12.423%20Version%2F12.16)

**Comment by koekaverna** [comment]
@liviuconcioiu yes this one is okay. I tried `Opera/9.80 (J2ME/MIDP; Opera Mini/9.80 (S60; SymbOS; Opera Mobi/23.348; U; en) Presto/2.5.25 Version/10.54` and it's detect as opera mobile, I made a mistake in first message.

https://devicedetector.lw1.at/Opera%2F9.80%20(J2ME%2FMIDP;%20Opera%20Mini%2F9.80%20(S60;%20SymbOS;%20Opera%20Mobi%2F23.348;%20U;%20en)%20Presto%2F2.5.25%20Version%2F10.54

**Comment by sgiehl** [comment]
That basically happens as the string contains the fragment for opera mobile and opera mini.
Our detections currently first run detection for mobile and then mini. 
@koekaverna Can you confirm that this useragent is for sure coming from an Opera Mini?

**Comment by koekaverna** [comment]
@sgiehl I'm not hundred percent sure.
I got this strings from
https://www.useragentstring.com/pages/Opera%20Mini/
But it seems legit

**Comment by sanchezzzhak** [comment]
there are no other opera for J2ME, only Opera Mini, and such a user agent may exist for compatibility with sites
