### ISSUE TITLE
Arcelik Group Identification

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7503]
Arcelik Group is a Turkish manufacturer that has brands like Grundig, Beko, Arçelik, and Altus and also manufactures products for brands like Hitachi, Sharp, and Philco.

Since the most well-known brand of Arcelik Group is Grundig, the device detector gives Grundig output as the brand information for the televisions manufactured by Arcelik Group.

**Correct Example**:
* [x] Mozilla/5.0 (Linux armv9; U; en;) AppleWebKit/537.36 (Grundig;visionos;NX;03.024.00;) CE-HTML/1.0 NETRANGEMMH HbbTV/2.0 (SRAF;Arcelik_Gen3;RC_V2;Arcelik;NX;NXGRMR.-.-.-.-.V03.024.00;tr-TR;Wireless;prod;)
Brand: Grundig

Incorrect Examples:
* [x] Mozilla/5.0 (Linux armv9; U; en;) AppleWebKit/537.36 (Arcelik;visionos;NX;03.024.00;) CE-HTML/1.0 NETRANGEMMH HbbTV/2.0 (SRAF;Arcelik_Gen3;RC_V2;Arcelik;NX;NXGRMR.-.-.-.-.V03.024.00;tr-TR;Wireless;prod;)
Brand: Arcelik

* [x] Mozilla/5.0 (Linux armv9; U; en;) AppleWebKit/537.36 (Beko;visionos;NX;03.024.00;) CE-HTML/1.0 NETRANGEMMH HbbTV/2.0 (SRAF;Arcelik_Gen3;RC_V2;Arcelik;NX;NXGRMR.-.-.-.-.V03.024.00;tr-TR;Wireless;prod;)
Brand: BEKO

* [x] Mozilla/5.0 (Linux armv9; U; en;) AppleWebKit/537.36 (Altus;visionos;NX;03.024.00;) CE-HTML/1.0 NETRANGEMMH HbbTV/2.0 (SRAF;Arcelik_Gen3;RC_V2;Arcelik;NX;NXGRMR.-.-.-.-.V03.024.00;tr-TR;Wireless;prod;)
Brand: Altus

* [x] Mozilla/5.0 (QtEmbedded; Linux) AppleWebKit/537.4 (KHTML, like Gecko) MWB/1.0 Safari/537.4 HbbTV/1.2.1 (+PVR+DRM; Arcelik; MWB;;;)
Brand: Arcelik

* [x] Mozilla/5.0 (Linux;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 SRAF/4.0 (; SERAPHIC; SERAPHIC; v4.0; v1.0; ); CE-HTML/1.0 hbbtv PHILCO/PH60D16DSGWN4K DeviceID/60748d863766 NETRANGEMMH Arcelik Grundig SMART-TV
Brand: PHILCO

* [x] Mozilla/5.0 (Linux;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 SRAF/4.0 (; UMC-Sharp; FVP6486X; v3.5; v1.0; ); CE-HTML/1.0 hbbtv PHILCO/PH60D16DSGWN4K DeviceID/c08acd74aa34 Arcelik Grundig FXM-U2FsdGVkX18CGxdgOulmEAW9kIUa31zv9O4jhWxhPiBWfOaZ6OLXqy19vdG3rVlJ-END
Brand: PHILCO or Sharp (not sure)

* [x] Mozilla/5.0 (Linux armv9; U; ar;) AppleWebKit/537.17 (Beko;quicksmart;O2;02.034.00;) CE-HTML/1.0 ARCELIKAS HbbTV/1.2.1 (MWB;Arcelik_Gen3;RC_V2;Arcelik;O2;O2GRMR.-.-.-.-.V02.034.00;ar-TR;Wireless;prod;)
Brand: Beko

Missing Information:
* [x] Kodi/20.2 (Linux; Android 11.0; Arcelik Android UHD TV Build/RTM6.230109.219) Android TV/11.0.0 Sys_CPU/armv7l App_Bitness/32 Version/20.2-(20.2.0)-Git:20230629-5f418d0b13
Brand: Arcelik

* [x] Mozilla/5.0 (Linux; Android 11; Arcelik Android TV Build/RTM6.230109.094; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36
Brand: Arcelik

**Comment by sanchezzzhak** [comment]
New definitions device and brands added to the master branch. Thx all.
