### ISSUE TITLE
Missing Brand Information for VESTEL TVs

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7504]
Vestel exists as a brand in the device detector. However, for some user agents, this information can not be parsed well.

Examples:
Opera/9.80 (Linux mips; U; ; en) Presto/2.10.287 Version/12.00 UID(00:09:DF:3D:64:E3/MB91/VESTEL/3.2.9.r)+CE-HTML;MEM:HIGH

Opera/9.80 (Linux mips; ) Presto/2.12.407 Version/12.51 MB98/0.45.14.5 (VESTEL, Mxl66155_V, wireless) VSTVB_MB97 UID(00:09:DF:D7:F2:BB/MB98/VESTEL/0.45.14.5)+CE-HTML;MEM:HIGH SmartTvA/3.0.0

**Comment by EfekanPekel** [comment]
Other user agents of some televisions manufactured by Vestel and has missing information:


Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.164 Model/Vestel-MB230 VSTVB MB200 HbbTV/1.5.1 (+DRM; DIKOM; MB230; 0.51.51.0; ; _TV_NT72671_2019;) SmartTvA/3.0.0
Brand: DIKOM

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.168 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; NEXT; MB180; 1.61.1.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: NEXT

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.179 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; CLAYTON; MB180; 1.64.1.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: CLAYTON

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.179 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; DAEWOO; MB180; 1.64.1.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: DAEWOO

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.180 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; NORMANDE; MB180; 1.65.0.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: NORMANDE

**Comment by sanchezzzhak** [comment]
New definitions device and brands added to the master branch. Thx all.
