### ISSUE TITLE
Hisense Identifications / Addition of VIDAA OS

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7505]
Some user agents have Hisense info but do not return it in the output of the device detector. 

New Hisense TVs have VIDAA OS as the operating system which is not recognized by Device Detector.
https://www.vidaa.com/vidaa-os/

VIDAA OS Examples:

* [x] Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Odin/88.4324.2.10 Safari/537.36 Model/Hisense-NT72671D VIDAA/6.0(Hisense;SmartTV;85A66GAVT;NT72671/V0000.06.12N.N0622;UHD;86A6GA;)

* [x] Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Odin/88.4324.2.10 Safari/537.36 Model/Hisense-MT9602 VIDAA/6.0(TOSHIBA;SmartTV;43C350LE;MTK9602/V0000.06.10Q.N0322;UHD;43C350LE;)

* [x] Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Odin/88.4324.2.10 Safari/537.36 Model/Hisense-MT9602 VIDAA/6.0(UGINE;SmartTV;65A53FXVT;MTK9602/V0000.06.10S.M1228;UHD;65A5FX;)

* [x] Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Odin/88.4324.2.10 Safari/537.36 Model/Hisense-MT9602 VIDAA/6.0(AWOX;SmartTV;43V35KE;MTK9602/V0000.06.12S.N0630;FHD;43V35KE;)

* [x] Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Odin/88.4324.2.10 Safari/537.36 Model/Hisense-MT9602 VIDAA/5.0(Hisense;SmartTV;58A53FXVT;MTK9602/V0000.01.00R.M0725;UHD;58A5FX;)

* [x] Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Odin/74.3729.2.10 Safari/537.36 Model/Hisense-NT72671D VIDAA/5.0(Hisense;SmartTV;85A60GAVT;NT72671/V0000.01.00N.L1022;UHD)

* [x] Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Odin/74.3729.2.10 Safari/537.36 Model/Hisense-MSD6886 VIDAA/4.0(Hisense;SmartTV;70A519FAVT;mstar6886/V0000.01.00Q.N0525;UHD)

* [x] Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.140 Safari/537.36 OPR/46.0.2207.0 OMI/4.21.4.112.Catcher4.69 Model/Hisense-MT9602 VIDAA/5.0(Hisense;SmartTV;55A52FEVS;MTK9602/V0000.01.00R.M0531;UHD;55A5FE;)

* [x] Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.140 Safari/537.36 OPR/46.0.2207.0 OMI/4.21.2.50.Honey.214 Model/Hisense-NT72671D VIDAA/6.0(Hisense;SmartTV;75A53FEVS;NT72671/V0000.01.00S.N0206;UHD;75A5FE;)

* [x] Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.3.54.Catcher2.205 Model/Hisense-MSD6886 VIDAA/4.0(Hisense;SmartTV;HE55A6803FUWTS;mstar6886/V0000.01.00K.M0518;UHD)

Other Hisense UA Examples:

Opera/9.80 (Linux armv7l; Opera TV Store/5581) Presto/2.12.362 Version/12.11 Model/Hisense-MTK5651

Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.140 Safari/537.36 OPR/46.0.2207.0 OMI/4.21.2.50.Honey.220 Model/Hisense-NT72671D TV Store/4.21

Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.3.54.Catcher2.196 Model/Hisense-MSD6886

Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.3.54.Catcher2.147 Model/Hisense-MSD6886 TV Store/4.20

* [x] Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.Martell-2.312 Model/Hisense-MT5658-SDK4-9 MT5658 (;Hisense;SmartTV;V0000.01.00a.J0211;HE43A6500UWTS) FXM-U2FsdGVkX18/+ceY1oqH8mnezkZ/ZlbriwD7ixl/Ho5dsOsPG6/PhIre4h8t42z4-END

**Comment by sanchezzzhak** [comment]
New definitions device and brands added to the master branch. Thx all.
