### ISSUE TITLE
TiVo Detection Improvement

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7509]
TiVO as an Operating System:
https://business.tivo.com/products-solutions/tivo-os

https://www.lightreading.com/business-management/launch-of-first-tivo-based-tvs-delayed-to-second-half-of-2023

Example User-Agents:
Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.128 Safari/537.36 OPR/46.0.2207.0 OMI/4.23.2.96.LIMA2.89 Model/Vestel-MB180 VSTVB MB100 FVC/8.0 (OEM; MB180; ) HbbTV/1.6.1 (+DRM; OEM; MB180; 0.32.0.0; ; _TV_G31_2023;) TiVoOS/1.0.0 (Vestel MB180 OEM) SmartTvA/3.0.0

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.128 Safari/537.36 OPR/46.0.2207.0 OMI/4.23.2.96.LIMA2.85 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.6.1 (+DRM; JVC; MB180; 0.29.0.0; ; _TV_G31_2023;) TiVoOS/1.0.0 (Vestel MB180 JVC) SmartTvA/3.0.0

TiVO as a brand:

Example User-Agents:
Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36 OPR/36.0.2128.0 OMI/4.8.0.129.JFK.651 TV Store/4.8 Model/TiVo-Cogeco-TCDD16000

Mozilla/5.0 (Linux mips) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36 OPR/36.0.2128.0 OMI/4.8.0.129.JFK.655 TV Store/4.8 Model/TiVo-Armstrong-TCDD12000

**Comment by sanchezzzhak** [comment]
Added TiVo OS and some apps. Thx All
