### ISSUE TITLE
Smart TV Detection Improvements

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7515]
- Mozilla/5.0 (Linux; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 SRAF/3.5 HbbTV/1.2.1 (; Profilo; 43PA305E; 20180627_134111; v1.0; ); CE-HTML/1.0 FXM-U2FsdGVkX19ys6IybgGi16R1VZSFl3p8oRO8Ojht1qTyF8r58pFyW+mmo3uQOuMi-END
Model: 43PA305E
https://www.profilo.com/urun-listesi/43PA305E#/Togglebox=manuals/

- Mozilla/5.0 (Linux; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 SRAF/3.5 HbbTV/1.2.1 (; TCL; 55C1; V8-MS88ACO-LF1V001; 40-6488LA-MAC2HG; 2015); CE-HTML/1.0 FXM-U2FsdGVkX1+0bw4qhlAuhlT5t1CBNvyRZSXxNky+FgPj/e6inJgf6mfLYouTPhGa-END
Model: 55C1
https://www.appliancesonline.com.au/product/tcl-55c1us-55-inch-138-7cm-uhd-smart-tv

- Opera/9.80 NETTV/4.5.0 Mozilla/5.0 (Linux armv7i; CE-HTML/1.0; U; en) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Tbrowser/2.0 _TV_/V8-S586T02-LF1V408 (TCL,55P65US,wired)
Model: 55P65US, Type: TV
https://www.amazon.in/TCL-138-71-Inches-Smart-55P65US/dp/B07FYT8MH8

- Opera/9.80 Zeasn/2.0 NETTV/4.5.0 Mozilla/5.0 (Linux armv7i;CE-HTML/1.0;U;en), Chrome/42.0.2311.152 Safari/537.36 AppleWebKit 537.36 (KHTML, like Gecko) Tbrowser/2.0, _TV_NT563/V8-N563T01-LF1V080 (TCL,39S62,wired)
Model: 39S62, Type: TV
https://www.amazon.sa/-/en/TCL-Inch-Smart-LED-Black/dp/B07V37SL54

- Opera/9.80 NETTV/4.5.0 Mozilla/5.0 (Linux armv7i; CE-HTML/1.0; U; en) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Tbrowser/2.0 _TV_/V8-NT563LA-LF1V248 (PANASONIC,TH-55FS430M,wireless)
Model: TH-55FS430M
https://www.panasonic.com/mea/en/support/product-archive/tv/th-55fs430m.html

- RokuBrowser/84.42.14 (TV-G000X-12.5.0.4176) Chrome/84.0.4147.38 HbbTV/1.6.1 (+DRM; TCL; 43RP630; 12.5.0.4176-84.42.14; ; com.roku.G000X; )
Model: 43RP630
https://www.tcl.com/uk/en/tvs/rp620k

**Comment by EfekanPekel** [comment]
- Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.4.54.Elm.33 Model/ELM-NT72563C(TCL72563C;V8-NT63CLA-LF1V628;T000.000.000.266_DM910.0.21_U1.0.114.71_A0.3.1 [2022-01-28 13:56:48];_TV_NT72563_Tbrowser_2k20) SignOn/2.0 WhaleTV/2.0 NETTV_4.6.0.1 en
Brand: TCL

- Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 HbbTV/1.6.1 (+DRM; LGE/SILICONPLAYER/DIJITSU; 50DW9900; WEBOS22 03.34.35; W22_K8LP; DTV_C22P;)
Brand: Dijitsu
http://dijitsu.com.tr/tv/50-dw-9900-webos-tv/

**Comment by EfekanPekel** [comment]
- Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 HbbTV/1.6.1 (+DRM; LGE/WALTON/SIMFER; 50SFSW6M; WEBOS22 03.34.35; W22_K8LP; DTV_C22P;) FVC/7.0 (LGE/WALTON/SIMFER; WEBOS22;)
Brand: SIMFER
https://www.simfer.com.tr/simfer-50sfsw6m-127-ekran-webos-led-4k-uhd-tv

**Comment by EfekanPekel** [comment]
Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 HbbTV/1.6.1 (+DRM; LGE/WALTON/SIMFER; 50SFSW6M; WEBOS22 03.34.35; W22_K8LP; DTV_C22P;) FVC/7.0 (LGE/WALTON/SIMFER; WEBOS22;)
Brand: SIMFER
https://www.simfer.com.tr/simfer-50sfsw6m-127-ekran-webos-led-4k-uhd-tv

**Comment by EfekanPekel** [comment]
- RokuBrowser/84.42.14 (TV-G000X-12.5.0.4176) Chrome/84.0.4147.38 HbbTV/1.6.1 (+DRM; SHARP; 50FJ2E; 12.5.0.4176-84.42.14; ; com.roku.G000X; )
OS: Roku OS 12.5
https://www.sharpconsumer.de/tv/55fj2e/

- RokuBrowser/84.42.14 (TV-G000X-12.5.0.4176) Chrome/84.0.4147.38 HbbTV/1.6.1 (+DRM; TCL; 55RP630; 12.5.0.4176-84.42.14; ; com.roku.G000X; )
OS: Roku OS 12.5 Model: 55RP630
https://www.tcl.com/au/en/tvs/55rp630

**Comment by sanchezzzhak** [comment]
Added to master branch. Thank you all.
