### ISSUE TITLE
TV Detection Improvements

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7527]
- [x] com.tcl.browser/660067 (Linux; U; Android 12; tr_TR; Chromecast HD; Build/STTK.230808.004; Cronet/114.0.5735.33)
- [x] com.tcl.browser/660067 (Linux; U; Android 12; tr_TR; Chromecast; Build/STTK.230808.004; Cronet/114.0.5735.33)
Brand: Google Chromecast, device: tv (https://store.google.com/us/product/chromecast_google_tv?hl=en-US&pli=1)

- [x] com.tcl.browser/660067 (Linux; U; Android 9; tr_TR; HKC 4K AI Smart TV; Build/PTO5.220304.001; Cronet/114.0.5735.33)
- [x] Dalvik/2.1.0 (Linux; U; Android 9; HKC 4K AI Smart TV Build/PTO5.220304.001)
Brand: HKC (https://www.hkc-eu.com/en/products/tv/)

- [x] Dalvik/2.1.0 (Linux; U; Android 10; DREAMSTAR Build/QP1A.191105.004)
- [x] Mozilla/5.0 (Linux; Android 10; DREAMSTAR) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Mobile Safari/537.36
Brand: Dreamstar, device: tv  (https://www.dreamstar.com.tr/Default.aspx)

- [x] Dalvik/2.1.0 (Linux; U; Android 11; Fobem 4K SMART TV Build/RTM6.230109.076)
Brand: Fobem (https://fobem.com.tr/)

- [x] Dalvik/2.1.0 (Linux; U; Android 11; ONVO SMART TV Build/RP1A.200720.011)
- [x] Dalvik/2.1.0 (Linux; U; Android 13; ONVO_32OV6000H Build/TP1A.220905.004.A2)
- [x] Mozilla/5.0 (Linux; Android 11; ONVO SMART TV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Safari/537.36
- [x] Mozilla/5.0 (Linux; Android 13; ONVO_42OV6000F Build/TP1A.220905.004.A2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Safari/537.36
- [x] Mozilla/5.0 (Linux; Android 13; ONVO_55OV6000U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Safari/537.36
Brand: ONVO, device: tv (https://onvo.com.tr/en/urunler/televizyonlar/onvo-32ov6000h-32-hd-ready-android-13-smart-led/)

- [x] Dalvik/2.1.0 (Linux; U; Android 13; NORDMENDE_43NM6000F Build/TP1A.220905.004.A2)
Brand: NORDMENDE, device: tv (https://onvo.com.tr/en/urunler/televizyonlar/nordmende-43nm6000f-43-full-hd-android-13-smart-led/)

- [x] Mozilla/5.0 (Linux; Android 11; SABA SMART TV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.90 Safari/537.36
Brand: SABA (https://onvo.com.tr/urunler/televizyonlar/saba-sb42250-42-full-hd-android-smart-led/)

- [x] Kodi/20.2 (Linux; Android 9.0; Hiremco Build/Hiremco) Android/9.0.0 Sys_CPU/armv7l App_Bitness/32 Version/20.2-(20.2.0)-Git:20230629-5f418d0b13
- [x] Mozilla/5.0 (Linux; Android 10; Matador Pro Air) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Mobile Safari/537.36
- [x] Mozilla/5.0 (Linux; Android 9; Hiremco Build/Hiremco; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Safari/537.36/8.5.0 (Linux;Android 9) ExoPlayerLib/2.6.1
Brand: HIREMCO, device: tv (https://www.hiremco.com.tr/kategori/android-box) (https://www.hiremco.com.tr/urun/matador-pro-air)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.256 Model/Vestel-MB130 VSTVB MB100 HbbTV/1.2.1 (; EAS_ELECTRIC; MB130; 5.35.4.0; _TV_G10_2017;) SmartTvA/3.0.0
Brand: EAS Electric (https://easelectric.es/)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.258 Model/Vestel-MB211 VSTVB MB200 HbbTV/1.2.1 (; NEXON; MB211; 3.33.17.4; _TV_NT72563_2017;) SmartTvA/3.0.0
- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.179 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; NEXON; MB180; 1.64.1.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: NEXON

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.179 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; EDENWOOD; MB180; 1.64.1.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: EDENWOOD (https://www.electrodepot.fr/tv-image-son/television.html)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.183 Model/Vestel-MB181 VSTVB MB100 HbbTV/1.5.1 (+DRM; KYDOS; MB181; 1.89.7.0; ; _TV_G36_2020;) SmartTvA/3.0.0
Brand: KYDOS (https://www.skroutz.gr/c/12/television/m/10507/Kydos.html)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.179 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; AYA; MB180; 1.64.1.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: AYA (https://www.but.fr/produits/3609130013286/Televiseur-SMART-TV-32-80-cm-AYA-A32HD0322BS.html)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.150 Model/Vestel-MB230 VSTVB MB200 HbbTV/1.5.1 (+DRM; HANSEATIC; MB230; 1.15.17.0; ; _TV_NT72671_2019;) SmartTvA/3.0.0
Brand: HANSEATIC (https://allegro.pl/kategoria/tv-i-video-telewizory-257732?string=hanseatic)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.119 Model/Vestel-MB230 VSTVB MB200 FVC/4.0 (MITCHELL_BROWN; MB230; ) SmartTvA/3.0.0
Brand: Mitchell & Brown (https://www.mitchellandbrown.co.uk/)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.164 Model/Vestel-MB181 VSTVB MB100 FVC/5.0 (DIXONS-LOGIK; MB181; ) SmartTvA/3.0.0
Brand: LOGIK (https://www.currys.co.uk/tv-and-audio/televisions/tvs/logik)

- [x] Mozilla/5.0 (Linux; Android 11; GTV-50PU744N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36
Brand: GTV (https://www.gpluselectronics.com/en/plist/118/UHD-TV)

- [x] Mozilla/5.0 (Linux; Android 7.0; SPYBOXS11 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.163 Safari/537.36/8.5.0 (Linux;Android 7.0) ExoPlayerLib/2.6.1
- [x] Mozilla/5.0 (Linux; Android 7.0; SPYBOXS11_PLUS Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.91 Safari/537.36/8.5.0 (Linux;Android 7.0) ExoPlayerLib/2.6.1
Brand: SPYBOX, device: tv (https://www.hepsiburada.com/novacom-spybox-s11-ci-4k-turbo-android-uydu-alici-pm-HB00000857L1)

- [x] Mozilla/5.0 (X11; Linux x86_64;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 SRAF/4.0 (; Arcelik; NF; v03.005.00; v1.0; ); CE-HTML/1.0 hbbtv NETRANGEMMH
Brand: Arçelik

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 HbbTV/1.5.1 (+DRM; LGE/XianYou/AWOX; B213200SW; WEBOS5.0 04.50.60; W50_K6LP; DTV_C20L;)
Brand: AWOX (https://www.awox.com.tr/en/TELEV%C4%B0ZYON)

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 HbbTV/1.5.1 (+DRM; LGE/WALTON/SKYTECH; ST-5590; WEBOS5.0 04.50.60; W50_K6LP; DTV_C20P;)
Brand: SKYTECH (https://skytech.com.tr/en/televizyonlar/)

- [ ] HbbTV/1.5.1 (+DRM;ATMACA;SmartTV2021_LICENSE:KTSU2EL_ATM;T-21KTSU2EATMDEUC-1060.2;ATMACA_LICENSE;urn:samsungtv:familyname:21_ATMACA_UHD_LIC:2021;) Tizen/6.0 (+TVPLUS+SmartHubLink) Chrome/76 LaTivu_1.0.1_2021
Brand: Atmaca Elektronik

- [x] Opera/9.80 NETTV/4.5.0 Mozilla/5.0 (Linux armv7i; CE-HTML/1.0; U; en) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Tbrowser/2.0 _TV_NT563/V8-NT563AM-LF1V033 (Nevir,32D1291,wireless)
Brand: Nevir 32D1291, device: tv (https://www.emag.ro/televizor-led-vortex-32td2070-hd-ready-clasa-f-81cm-ax32td2070/pd/D990TDMBM/)

**Comment by EfekanPekel** [comment]
### Tivo OS
- Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.128 Safari/537.36 OPR/46.0.2207.0 OMI/4.23.2.96.LIMA2.91 Model/Vestel-MB181 VSTVB MB100 TiVoOS/1.0.0 (Vestel MB181 FINLUX) SmartTvA/3.0.0
Brand: FINLUX

- Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.128 Safari/537.36 OPR/46.0.2207.0 OMI/4.23.2.96.LIMA2.94 Model/Vestel-MB180 VSTVB MB100 FVC/8.0 (HITACHI; MB180; ) TiVoOS/1.0.0 (Vestel MB180 HITACHI) SmartTvA/3.0.0
Brand: HITACHI


### BOTECH
Brand: Botech (https://botech.com.tr/urunlerimiz.aspx?CategoryId=99)
- Mozilla/5.0 (Linux; Andr0id 9; ATV R2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.31.Oak.45 HbbTV/1.5.1 (+DRM;BOTECH;ATV R2;Demo 1.0;Demonstration only;TVs;) FVC/5.0 (BOTECH;TVs;)

- Mozilla/5.0 (Linux; Andr0id 9; ATV R1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.31.Oak.45 HbbTV/1.5.1 (+DRM;BOTECH;ATV R1;Demo 1.0;Demonstration only;TVs;) FVC/5.0 (BOTECH;TVs;)


### Android
Device: tv (https://www.mynokia.com/streaming-devices/nokia-streaming-stick-800/)
- Dalvik/2.1.0 (Linux; U; Android 11; Nokia Streaming Stick 800 Build/RTT0.210618.003)

Device: tv 
- Dalvik/2.1.0 (Linux; U; Android 11; MiTV-AFKR0 Build/RTT0.211222.001)

**Comment by liviuconcioiu** [comment]
@sanchezzzhak I can't get the regex to work for `Mozilla/5.0 (X11; Linux x86_64;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 SRAF/4.0 (; Arcelik; NF; v03.005.00; v1.0; ); CE-HTML/1.0 hbbtv NETRANGEMMH`. If you could help on this one.

**Comment by sanchezzzhak** [comment]
Mozilla/5.0 (X11; Linux x86_64;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 SRAF/4.0 (; Arcelik; NF; v03.005.00; v1.0; ); CE-HTML/1.0 hbbtv NETRANGEMMH

```yml
user_agent: Mozilla/5.0 (X11; Linux x86_64;) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36 SRAF/4.0 (; Arcelik; NF; v03.005.00; v1.0; ); CE-HTML/1.0 hbbtv NETRANGEMMH
os:
  name: GNU/Linux
  version: ""
  platform: x64
client:
  type: mobile app
  name: NetRanges
  version: ""
device:
  type: tv
  brand: ""
  model: ""
os_family: GNU/Linux
browser_family: Unknown
```

modify AbstractDeviceParser::hasDesktopFragment method
```
    protected function hasDesktopFragment(): bool
    {
        return
            ($this->matchUserAgent('(?:Windows (?:NT|IoT)|X11; Linux x86_64)') && !$this->matchUserAgent('CE-HTML')) &&
            !$this->matchUserAgent(' Mozilla/|Andr[o0]id|Tablet|Mobile|iPhone|Windows Phone|ricoh|OculusBrowser') &&
            !$this->matchUserAgent('Lenovo|compatible; MSIE|Trident/|Tesla/|XBOX|FBMD/|ARM; ?([^)]+)');
    }
```
or 
```
    protected function hasDesktopFragment(): bool
    {
        return
            ($this->matchUserAgent('(?:Windows (?:NT|IoT)|X11; Linux x86_64)') && !$this->matchUserAgent('hbbtv')) &&
            !$this->matchUserAgent(' Mozilla/|Andr[o0]id|Tablet|Mobile|iPhone|Windows Phone|ricoh|OculusBrowser') &&
            !$this->matchUserAgent('Lenovo|compatible; MSIE|Trident/|Tesla/|XBOX|FBMD/|ARM; ?([^)]+)');
    }
```

**Comment by sanchezzzhak** [comment]
@liviuconcioiu  this user agent has not been processed

```yml
user_agent: HbbTV/1.5.1 (+DRM;ATMACA;SmartTV2021_LICENSE:KTSU2EL_ATM;T-21KTSU2EATMDEUC-1060.2;ATMACA_LICENSE;urn:samsungtv:familyname:21_ATMACA_UHD_LIC:2021;) Tizen/6.0 (+TVPLUS+SmartHubLink) Chrome/76 LaTivu_1.0.1_2021
os:
  name: Tizen
  version: "6.0"
  platform: ""
client:
  type: browser
  name: Chrome
  version: "76"
  engine: Blink
  engine_version: "76"
device:
  type: tv
  brand: Samsung
  model: Smart TV (2021)
os_family: Other Mobile
browser_family: Chrome
```
