### ISSUE TITLE
Vestel Production TV Devices

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7535]
Me again with the televisions :)

VSTVB refers to the device produced by Vestel. There is no such field as "Manufacturer" but Vestel can be used as a fallback "Brand" for these User Agents. In addition, MBxxx states the device's chipset, this value can be used as a "Model".

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.179 Model/Vestel-MB181 VSTVB MB100 FVC/5.0 (ALTIMO; MB181; ) SmartTvA/3.0.0
Brand: Altimo
https://www.altimo.co.uk/products/discontinued/5522uhdsm/

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.180 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; ATLANTIC; MB180; 1.65.0.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: Atlantic
https://www.atlanticelectrics.co.uk/collections/television

Mozilla/5.0 (Android armv8l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36 Model/Vestel-MB185 VSTVB MB185 FVC/6.0 (CECOTEC; MB185; ) HbbTV/1.5.1 (+DRM; CECOTEC; MB185; R2.0.1.0.0.V0.25.3; ; _TV_MSTARG31_2021;) SmartTvA/3.0.0 LaTivu_1.0.1_2022
Brand: Ceotec
https://cecotec.es/es/televisores-smart-tv

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.253 Model/Vestel-MB211 VSTVB MB200 HbbTV/1.2.1 (; CROWN; MB211; 3.33.17.0; _TV_NT72563_2017;) SmartTvA/3.0.0
Brand: Crown
https://www.crownindiatv.com/

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.259 Model/Vestel-MB130 VSTVB MB100 HbbTV/1.2.1 (; DIORA; MB130; 5.35.8.3; _TV_G10_2017;) SmartTvA/3.0.0
Brand: Diora
https://dioraghana.com/product/5305/

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.259 Model/Vestel-MB130 VSTVB MB100 HbbTV/1.2.1 (; ELEKTROLAND; MB130; 5.35.8.3; _TV_G10_2017;) SmartTvA/3.0.0
Brand: Elektroland
https://www.elektroland.at/onlineshop/unterhaltungselektronik/tv-geraete/

Opera/9.80 (Linux mips; ) Presto/2.12.407 Version/12.51 MB97/0.39.24.3 (FITCO, Mxl661L32, wireless) VSTVB_MB97 UID(00:09:DF:F9:EE:D8/MB97/FITCO/0.39.24.3)+CE-HTML;MEM:HIGH SmartTvA/3.0.0
Brand: Fitco
https://darti.ma/produit/led-fitco-smart-wifi-android-fled42dn4sm/

Opera/9.80 (Linux mips; ) Presto/2.12.407 Version/12.51 MB97/0.45.23.22 (FUEGO, Mxl661315_, wireless) VSTVB_MB97 UID(48:6D:BB:0E:DD:8E/MB97/FUEGO/0.45.23.22)+CE-HTML;MEM:HIGH SmartTvA/3.0.0
Brand: Fuego
https://www.neptun.al/categories/te_gjithe_tv/TV-FUEGO-LED-32EL600T

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.119 Model/Vestel-MB230 VSTVB MB200 HbbTV/1.5.1 (+DRM; HOFER; MB230; 0.51.19.3; ; _TV_NT72671_2019;) SmartTvA/3.0.0 CE-HTML/1.0 FXM-U2FsdGVkX1+oZew0140/QJr77MUfq4MLbdiRi2kJoV7/8uMZVrWgC9VFEmvmsz/4-END
Brand: Hofer
https://www.hofer.at/de/homepage.html

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.253 Model/Vestel-MB211 VSTVB MB200 HbbTV/1.2.1 (; KENDO; MB211; 3.33.17.0; _TV_NT72563_2017;) SmartTvA/3.0.0
Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.137 Model/Vestel-MB230 VSTVB MB200 HbbTV/1.5.1 (+DRM; KENDO; MB230; 1.15.7.0; ; _TV_NT72671_2019;) SmartTvA/3.0.0
Brand: Kendo
https://www.expert.de/shop/unsere-produkte/tv-audio/fernseher/lcd-led-fernseher?s=kendo-tv

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.164 Model/Vestel-MB230 VSTVB MB200 HbbTV/1.5.1 (+DRM; MEGA_VISION; MB230; 0.51.49.0; ; _TV_NT72671_2019;) SmartTvA/3.0.0
Brand: Mega Vision
https://www.emag.ro/televizor-led-32-mega-vision-hd-usb-hdmi-dvb-t-dvb-c-mv32hd703/pd/DGZZG9BBM/

Opera/9.80 NETTV/4.5.0 Mozilla/5.0 (Linux armv7i; CE-HTML/1.0; U; en) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Tbrowser/2.0 _TV_NT563/V8-NT563AM-LF1V033 (Nevir,32D1291,wireless)
Brand: Nevir 
https://nevir.es/catalogo/televisores/

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.119 Model/Vestel-MB230 VSTVB MB200 HbbTV/1.5.1 (+DRM; NABO; MB230; 0.51.19.3; ; _TV_NT72671_2019;) SmartTvA/3.0.0
Brand: Nabo
https://www.nabo.at/unterhaltung/tv/led-tv/

Mozilla/5.0 (Android armv8l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Safari/537.36 Model/Vestel-MB185 VSTVB MB185 FVC/6.0 (NOKIA; MB185; ) HbbTV/1.5.1 (+DRM; NOKIA; MB185; R2.0.1.0.0.V0.25.3; ; _TV_MSTARG31_2021;) SmartTvA/3.0.0 LaTivu_1.0.1_2022
Brand: Nokia
https://www.mynokia.com/smart-tvs/

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.253 Model/Vestel-MB211 VSTVB MB200 HbbTV/1.2.1 (; OCEANIC; MB211; 3.33.17.0; _TV_NT72563_2017;) SmartTvA/3.0.0
Brand: Oceanic
https://www.oceanic.eu/en/

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.258 Model/Vestel-MB211 VSTVB MB200 HbbTV/1.2.1 (; ORAVA; MB211; 3.33.17.4; _TV_NT72563_2017;) SmartTvA/3.0.0
Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.259 Model/Vestel-MB130 VSTVB MB100 HbbTV/1.2.1 (; ORAVA; MB130; 5.35.8.3; _TV_G10_2017;) SmartTvA/3.0.0
Brand: Orava
https://www.orava.eu/en/television

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.258 Model/Vestel-MB211 VSTVB MB200 HbbTV/1.2.1 (; PROSONIC; MB211; 3.33.17.4; _TV_NT72563_2017;) SmartTvA/3.0.0
Brand: Prosonic
https://prosonic.co.in/smart-tv/

Opera/9.80 (Linux mips; ) Presto/2.12.407 Version/12.51 MB97/0.45.23.22 (REGAL, Mxl66149_V, wired) VSTVB_MB97 UID(00:09:DF:FE:79:83/MB97/REGAL/0.45.23.22)+CE-HTML;MEM:HIGH SmartTvA/3.0.0
Brand: Regal
https://www.regal-tr.com/televizyonlar-c-349

Opera/9.80 (Linux mips; ) Presto/2.12.407 Version/12.51 MB97/0.45.23.64 (SEG, Mxl66149_V, wired) VSTVB_MB97 UID(00:09:DF:F9:0C:A6/MB97/SEG/0.45.23.64)+CE-HTML;MEM:HIGH SmartTvA/3.0.0
Brand: SEG
https://www.akakce.com/televizyon/seg.html

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.258 Model/Vestel-MB211 VSTVB MB200 HbbTV/1.2.1 (; SEHMAX; MB211; 3.33.17.4; _TV_NT72563_2017;) SmartTvA/3.0.0
Brand: SEHMAX
https://teleton.se/t2cs2smart/tv-sehmax-24led-sm350-dc-t2cs2-smart/index.php

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.150 Model/Vestel-MB230 VSTVB MB200 FVC/4.0 (SOLAS; MB230; ) SmartTvA/3.0.0
Brand: SOLAS
https://solasbrands.com/collections/solas-tvs

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.258 Model/Vestel-MB211 VSTVB MB200 HbbTV/1.2.1 (; SILVA_SCHNEIDER; MB211; 3.33.17.4; _TV_NT72563_2017;) SmartTvA/3.0.0
Brand: Silva Schneider
https://www.silva-schneider.at/en/home/

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.259 Model/Vestel-MB130 VSTVB MB100 HbbTV/1.2.1 (; TURBO-X; MB130; 5.35.8.3; _TV_G10_2017;) SmartTvA/3.0.0
Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.119 Model/Vestel-MB230 VSTVB MB200 HbbTV/1.5.1 (+DRM; TURBO-X; MB230; 0.51.5.5; ; _TV_NT72671_2019;) SmartTvA/3.0.0
Brand: Turbo-X
https://www.plaisio.gr/tileoraseis/turbo-x

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.179 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; VANGUARD; MB180; 1.64.1.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: Vanguard
https://www.almacenesalvarez.com/televisor-vanguard-v43u8000

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.256 Model/Vestel-MB130 VSTVB MB100 FVC/2.0 (WALKER; MB130; ) HbbTV/1.4.1 (; WALKER; MB130; 5.35.4.0_ORION; _TV_G10_2017;) SmartTvA/3.0.0
Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 OPR/46.0.2207.0 OMI/4.13.5.431.SIERRA.158 Model/Vestel-MB230 VSTVB MB200 FVC/4.0 (WALKER; MB230; ) SmartTvA/3.0.0
Brand: WALKER
https://euronics.ie/collections/walker-tvs

Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.259 Model/Vestel-MB130 VSTVB MB100 HbbTV/1.2.1 (; WONDER; MB130; 5.35.8.3; _TV_G10_2017;) SmartTvA/3.0.0
Brand: Wonder
https://www.elitedigital.pt/pt/televisores-diversos/202077-tv-led-75-wonder-wdtv17504kcsm-uhdsmart-tv-android-8436545200469.html

**Comment by EfekanPekel** [comment]
> > VSTVB refers to the device produced by Vestel. There is no such field as "Manufacturer" but Vestel can be used as a fallback "Brand" for these User Agents. In addition, MBxxx states the device's chipset, this value can be used as a "Model".
> 
> We've had a similar discussion a few years back and unless the exact model is specified, we won't use MBXXX as model. Same for Hisense.
> 
> [#6615 (comment)](https://github.com/matomo-org/device-detector/pull/6615#discussion_r567946238)

Then there is one more issue :)
For Profilo devices, still MBxxx returns as the model. 

Example:
Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36 OPR/31.0.1890.0 OMI/4.6.1.40.Dominik2.193 VSTVB MB100 HbbTV/1.2.1 (; PROFILO; MB110; 2.32.0.0; ;) SmartTvA/3.0.0

In addition, BBC shows MBxxx as a model in their support document: https://www.bbc.co.uk/iplayer/help/questions/supported-devices/vestel

BBC also has a project called Melanite to detect only TV devices. There are matching model year and segment info for each chipset number.  Maybe Smart TV (20xx) can be used as a model.
Examples:
MB90 - tv_2013_crb
MB95 - tv_2012_opera
MB100 - tv_2015_highend_fvp
MB110 - tv_2015_mb110_fvp

If you wanna check: https://raw.githubusercontent.com/bbc/melanite/main/data/production-devices-oct-2023.json

**Comment by liviuconcioiu** [comment]
> Maybe Smart TV (20xx) can be used as a model.

Some, aren't Smart TVs (but probably those don't have a user-agent), for example if you look at page 17 (https://vestelinternational.com/file/catalogue_1641469164.pdf). I'm not against it, for some even the OS name and version can be mapped based on model.

I'll let @sanchezzzhak give his opinion.

**Comment by sanchezzzhak** [comment]
the `MB 000` parameter is the motherboard number, which does not give us the exact model for the brand

https://raw.githubusercontent.com/bbc/melanite/main/data/production-devices-oct-2023.json
we try process this list. but it definitely won't be 1-in-1 (As soon as there's time, Adding mobile devices takes up my time. Because every 2-3 months hundreds of devices from (The Celestial Empire) appear. Downloading several gigabytes of logs every month and processing them is a fun activity.)

> Some, aren't Smart TVs (but probably those don't have a user-agent), for example if you look at page 17 (https://vestelinternational.com/file/catalogue_1641469164.pdf). I'm not against it, for some even the OS name and version can be mapped based on model.

I have looked through this document, all that can be found there is the type of device UHD, HD, FHD.
it will not be possible to make an exact model of the device.
