### ISSUE TITLE
CaptiveNetworkSupport agent not all identified

### ISSUE THREAD

**Issue by malle-pietje** [matomo-org/device-detector#7541]
Hi, thanks for this package, it works great for us in a number of applications!

One of our applications is a WiFi captive portal where we extract the device properties for reporting/analytics purposes.

We see a lot of iOS devices using the following user-agents which aren't identified because the only pattern I could find is `CaptiveNetworkSupport-416 wispr`:
```
CaptiveNetworkSupport-346.50.1 wispr   
CaptiveNetworkSupport-355.200.27 wispr 
CaptiveNetworkSupport-355.261.1 wispr  
CaptiveNetworkSupport-355.270.2 wispr  
CaptiveNetworkSupport-355.60.1 wispr   
CaptiveNetworkSupport-390.40.1 wispr   
CaptiveNetworkSupport-390.60.1 wispr   
CaptiveNetworkSupport-407.40.1 wispr   
CaptiveNetworkSupport-416 wispr        
CaptiveNetworkSupport-416.30.2 wispr   
CaptiveNetworkSupport-418 wispr        
CaptiveNetworkSupport-418.80.2 wispr   
CaptiveNetworkSupport-428.0.0.0.1 wispr
CaptiveNetworkSupport-428.120.3 wispr  
CaptiveNetworkSupport-428.140.2 wispr  
CaptiveNetworkSupport-441 wispr        
CaptiveNetworkSupport-443.100.2 wispr  
CaptiveNetworkSupport-443.120.3 wispr  
CaptiveNetworkSupport-443.40.1 wispr   
CaptiveNetworkSupport-457 wispr        
CaptiveNetworkSupport-461.40.3 wispr   
CaptiveNetworkSupport-461.62.1 wispr   
CaptiveNetworkSupport-461.80.2 wispr 
```
Would it be possible add a regex that catches these? We wouldn't need to know versions, results like this would be perfectly fine:
```
    name: iOS
    short_name: IOS
    version:
    platform:
    family: iOS
```

**Comment by malle-pietje** [comment]
My AI friend came up with this regex ((I'm not that comfortable with regex patterns myself 😉) that should catch the above strings:
```
"CaptiveNetworkSupport-\d+(?:\.\d+)*\s+wispr"
```

**Comment by liviuconcioiu** [comment]
It's already detected:

https://github.com/matomo-org/device-detector/commit/cbb16c12559cbeaa059aeab9308514ff896443ba
https://devicedetector.lw1.at/CaptiveNetworkSupport-461.80.2%20wispr

You should use the latest version.

**Comment by malle-pietje** [comment]
Ah, my bad. We were stuck on v4.3.1 due to older PHP versions we needed to support, we've now bumped that to v5 and hopefully we can soon move on to 6.

Nice and useful tool by the way: https://devicedetector.lw1.at/
