### ISSUE TITLE
Which other useragents are supported besides $_SERVER['HTTP_USER_AGENT']?

### ISSUE THREAD

**Issue by gb5256** [matomo-org/device-detector#7617]
In the readme it states this:

$userAgent = $_SERVER['HTTP_USER_AGENT']; // change this to the useragent you want to parse

Could you explain which other useragents would make sense to use here?
Or what the difference of them would be in terms of expected results of this extension?

Thanks for any help.
gb5256

**Comment by liviuconcioiu** [comment]
> Could you explain which other useragents would make sense to use here? Or what the difference of them would be in terms of expected results of this extension?

Depends on your usage. You can give any user-agent as variable, especially usefull if you want to parse the user-agents from a file, database, etc.

**Comment by gb5256** [comment]
@liviuconcioiu : Thanks for the reply. So that means that for web users I will stay then on the $_SERVER['HTTP_USER_AGENT'].
Thanks for explaining.
