### ISSUE TITLE
Laravel : DeviceDetector->parse() throws Class \"Spyc\" not found

### ISSUE THREAD

**Issue by Charly66** [matomo-org/device-detector#7620]
Hello,

I'm using DeviceDetector via composer version 6.3.0 on a project with PHP 8.2 and Laravel 10.

Here is my code :

> $userAgent = $_SERVER['HTTP_USER_AGENT'];
$dd = new DeviceDetector($userAgent);
$dd->parse();
$browser = $dd->getClient();

`$dd->parse();` throws the following error :

> [2024-03-07 16:18:08] production.ERROR: Class \"Spyc\" not found at ./vendor/matomo/device-detector/Yaml/Spyc.php:28)
[stacktrace]
#0 ./vendor/matomo/device-detector/Parser/AbstractParser.php(252): DeviceDetector\\Yaml\\Spyc->parseFile()
#1 ./vendor/matomo/device-detector/Parser/AbstractParser.php(382): DeviceDetector\\Parser\\AbstractParser->getRegexes()
#2 ./vendor/matomo/device-detector/Parser/Bot.php(69): DeviceDetector\\Parser\\AbstractParser->preMatchOverall()
#3 ./vendor/matomo/device-detector/DeviceDetector.php(842): DeviceDetector\\Parser\\Bot->parse()
#4 ./vendor/matomo/device-detector/DeviceDetector.php(607): DeviceDetector\\DeviceDetector->parseBot()
#5 ./app/Http/Controllers/MainController.php(37): DeviceDetector\\DeviceDetector->parse()

And here is the composer.lock :
> {
            "name": "matomo/device-detector",
            "version": "6.3.0",
            "source": {
                "type": "git",
                "url": "https://github.com/matomo-org/device-detector.git",
                "reference": "35efad75b31f2596701834d19f097497909572a4"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/matomo-org/device-detector/zipball/35efad75b31f2596701834d19f097497909572a4",
                "reference": "35efad75b31f2596701834d19f097497909572a4",
                "shasum": ""
            },
            "require": {
                "mustangostang/spyc": "*",
                "php": "^7.2|^8.0"
            },
            "replace": {
                "piwik/device-detector": "self.version"
            },
            "require-dev": {
                "matthiasmullie/scrapbook": "^1.4.7",
                "mayflower/mo4-coding-standard": "^v9.0.0",
                "phpstan/phpstan": "^1.10.44",
                "phpunit/phpunit": "^8.5.8",
                "psr/cache": "^1.0.1",
                "psr/simple-cache": "^1.0.1",
                "symfony/yaml": "^5.1.7"
            },
            "suggest": {
                "doctrine/cache": "Can directly be used for caching purpose",
                "ext-yaml": "Necessary for using the Pecl YAML parser"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "DeviceDetector\\": ""
                },
                "exclude-from-classmap": [
                    "Tests/"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "LGPL-3.0-or-later"
            ],
            "authors": [
                {
                    "name": "The Matomo Team",
                    "email": "hello@matomo.org",
                    "homepage": "https://matomo.org/team/"
                }
            ],
            "description": "The Universal Device Detection library, that parses User Agents and detects devices (desktop, tablet, mobile, tv, cars, console, etc.), clients (browsers, media players, mobile apps, feed readers, libraries, etc), operating systems, devices, brands and models.",
            "homepage": "https://matomo.org",
            "keywords": [
                "devicedetection",
                "parser",
                "useragent"
            ],
            "support": {
                "forum": "https://forum.matomo.org/",
                "issues": "https://github.com/matomo-org/device-detector/issues",
                "source": "https://github.com/matomo-org/matomo",
                "wiki": "https://dev.matomo.org/"
            },
            "time": "2024-02-16T16:26:57+00:00"
        },
...
{
            "name": "mustangostang/spyc",
            "version": "0.6.3",
            "source": {
                "type": "git",
                "url": "https://github.com/mustangostang/spyc",
                "reference": "4627c838b16550b666d15aeae1e5289dd5b77da0"
            },
            "type": "library",
            "notification-url": "https://packagist.org/downloads/"
        }

Do you have any idea of the root cause ?
Thanks

**Comment by meklis** [comment]
Have same issue. 
Seems problem from here - https://github.com/mustangostang/spyc

Do you find solution?

**Comment by liviuconcioiu** [comment]
A temporary solution for this can be something like this:

```JSON
"files": ["vendor/mustangostang/spyc/Spyc.php"]
```

under

https://github.com/matomo-org/device-detector/blob/a57ab14a3159bc45a1b58b2286a3634f3d2a8e9b/composer.json#L23

**Comment by sgiehl** [comment]
Sorry, I'm on vacation at the moment. Maybe @mneudert can help on that one.

**Comment by saulfrr** [comment]
Exact same problem here.

`use DeviceDetector\DeviceDetector;`

```
       $dd = new DeviceDetector($userAgent);
       $dd->parse();

       $clientInfo = $dd->getClient();
       $osInfo = $dd->getOs();
       $device = $dd->getDeviceName();
       $brand = $dd->getBrandName();
       $model = $dd->getModel();
```


`[2024-03-07 13:44:43] local.ERROR: Class "Spyc" not found {"userId":2,"exception":"[object] (Error(code: 0): Class \"Spyc\" not found at /var/www/project/vendor/matomo/device-detector/Yaml/Spyc.php:28)`

**Comment by liviuconcioiu** [comment]
> According to [mustangostang/spyc#90](https://github.com/mustangostang/spyc/issues/90) this may have already been fixed. Can someone verify that?

It has been fixed. Jobs are passing https://github.com/matomo-org/device-detector/actions/runs/8186046322/job/22409607131

**Comment by saulfrr** [comment]
Just tested, not getting the error anymore.

Now i get this in return

```
[2024-03-07 20:41:36] local.INFO: array (
  'clientInfo' =>
  array (
    'type' => 'browser',
    'name' => 'Firefox',
    'short_name' => 'FF',
    'version' => '123.0',
    'engine' => 'Gecko',
    'engine_version' => '123.0',
    'family' => 'Firefox',
  ),
  'osInfo' =>
  array (
    'name' => 'Mac',
    'short_name' => 'MAC',
    'version' => '10.15',
    'platform' => '',
    'family' => 'Mac',
  ),
  'device' => 'desktop',
  'brand' => 'Apple',
  'model' => '',
  'userAgent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0',
)
```

**Comment by Charly66** [comment]
I confirm it's OK now, thanks.
