### ISSUE TITLE
Add Uptimia bot

### ISSUE THREAD

**Issue by metmarkosaric** [matomo-org/device-detector#7655]
Is it possible to add Uptimia bot (used for uptime tracking) to the bot list please? 

This should be the user agent they use: 

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5…/537.36 Uptimia/1.0 (https://www.uptimia.com/)`

Thanks!

**Comment by reatlat** [comment]
@metmarkosaric TY
here is the full name of userAgent
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5002.111 Safari/537.36 Uptimia/1.0 (https://www.uptimia.com)`

I use Uptimia to track my web-porjects, and projects for my clients :) 
here is the full IPs list they use [https://www.uptimia.com/monitoring-checkpoints](https://www.uptimia.com/monitoring-checkpoints)

On some of my projects I use npm package [@rearguard/is-bot](https://github.com/proximahq/rearguard) to exclude any bots from Plausibler, and its work perfect,

TY

**Comment by sanchezzzhak** [comment]
Thank you for providing the data and creating the issue.
