### ISSUE TITLE
 DeviceDetector has more detailed information

### ISSUE THREAD

**Issue by hulang** [matomo-org/device-detector#7682]
`Mozilla/5.0 (Linux; Android 10; TEL-AN10 Build/HONORTEL-AN10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36 T7/13.56 BDOS/1.0 (HarmonyOS 2.2.0) light/1.0 SP-engine/2.95.0 baiduboxapp/13.56.5.10 (Baidu; P1 10)`
brand=Huawei
model=Honor X10 5G
what model is : 
1=Honor
2=X10 5G

**Comment by hulang** [comment]
`Mozilla/5.0 (Linux; Android 12; FIN-AL60 Build/HUAWEIFIN-AL60; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36 T7/13.51 BDOS/1.0 (HarmonyOS 3.0.0) light/1.0 SP-engine/2.81.0 matrixstyle/0 lite baiduboxapp/6.25.0.10 (Baidu; P1 12)`
model=FIN-AL60
`FIN-AL60` = `nova 12`

**Comment by sanchezzzhak** [comment]
* FIN-AL60 -  cn: `Nova 12 活力版`  en: `Nova 12 Vitality Edition`
* FIN-AL60a - Nova 12 Lite ( need rename model name for current detection)

**Comment by hulang** [comment]
@sanchezzzhak 
`Mozilla/5.0 (Linux; Android 11; ZTE 7531N Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36 T7/13.25 light/1.0 SP-engine/2.63.0 baiduboxapp/13.25.0.10 (Baidu; P1 11)`
7531N=中兴远航30s

`Mozilla/5.0 (Linux; Android 10; FGD-AL00 Build/HUAWEIFGD-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36 T7/13.51 BDOS/1.0 (HarmonyOS 2.2.0) light/1.0 SP-engine/2.81.0 matrixstyle/0 lite baiduboxapp/6.25.0.10 (Baidu; P1 10)`
FGD-AL00=华为畅享70

`Mozilla/5.0 (Linux; Android 10; CHA-AL80 Build/HUAWEICHA-AL80; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36 T7/13.51 BDOS/1.0 (HarmonyOS 2.2.0) light/1.0 SP-engine/2.81.0 matrixstyle/0 lite baiduboxapp/6.25.0.10 (Baidu; P1 10)`
CHA-AL80=华为Nova10z

**Comment by sanchezzzhak** [comment]
* `FGD-AL00` - already defined as `Enjoy 70` in master branch.
* `BAL-AL80`, `CHA-AL80`, `ZTE 7531N`  - added

**Comment by hulang** [comment]
`Mozilla/5.0 (Linux; Android 12; ADY-AL00 Build/HUAWEIADY-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36 T7/13.56 BDOS/1.0 (HarmonyOS 3.0.0) light/1.0 SP-engine/2.95.0 baiduboxapp/13.56.0.11 (Baidu; P1 12)`
ADY-AL00=Pura70
