### ISSUE TITLE
WebOS Devices - Brand Identification

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7808]
Hi guys, WebOS changed its UA format and removed the manufacturer and brand information. However, model names are still on the UA. So, based on the model name patterns, the brands can be derived. I am sharing the ones that I found.

### AKAI

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; AK50KA315; 04.50.61; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, AK50KA315, wireless)

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; ALT42SMF; 04.50.61; 0x00000001; DTV_C20L); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, ALT42SMF, wireless)
https://hezkart.com/Best-Price-For/Akai-ALT42SMF-42-Inch-UHD-LED-Smart-TV/5310.html

### AWOX
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; B213900SW; 04.50.62; 0x00000001; DTV_C20L); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, B213900SW, wireless)
https://www.epey.com/televizyon/awox-b213900sw.html

### DIJITSU
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 50DW9900; 04.41.32; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 50DW9900, wireless)
http://dijitsu.com.tr/en/tv-en/50-dw-9900-webos-tv/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 58DW9900; 04.41.32; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 58DW9900, wireless)

### GWC
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 50GW6100; 04.41.32; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 50GW6100, wireless)
https://www.carrefourksa.com/mafsau/en/uhd-tv/gvc-pro-webos-tv-4k-50-inch/p/6287022145160

### NEXT & NEXTSTAR
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; YE-65020FS2-4K; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, YE-65020FS2-4K, wireless)
https://www.epey.com/televizyon/next-ye-65020fs2-4k.html

### SUNNY
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; SN50FMN242-0246; 04.50.61; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, SN50FMN242-0246, wireless)
https://www.sunny.com.tr/sunny-50-frameless-uhd-4k-webos-smart-tv-sn50fmn242/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; SN55FMN243-0246; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, SN55FMN243-0246, wireless)
https://www.sunny.com.tr/sunny-55-frameless-uhd-4k-webos-smart-tv-sn55fmn243/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; SNY55WOS; 04.50.61; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, SNY55WOS, wireless)
https://www.storeexpress.iq/%D8%AA%D9%84%D9%81%D8%B2%D9%8A%D9%88%D9%86-%D8%B3%D9%85%D8%A7%D8%B1%D8%AA-%D8%B3%D9%88%D9%86%D9%8A-55-%D8%A8%D9%88%D8%B5%D8%A9-%D8%B0%D9%83%D9%8A-%D8%8C-uhd-%D8%8C-k4-%D8%8C-%D9%84%D9%8A%D8%AF-sny55wos-%D9%85%D9%86-sunny?srsltid=AfmBOorhGJDVDRWs5voxW30fcyjKbou2l6pVchbt4E7m8FJXuPUimdwi

### SKYTECH
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; ST-5090; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, ST-5090, wireless)
https://skytech.com.tr/televizyonlar/st-5090/

### STREAM SMART
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; WSTRF4022FTP; 04.50.61; 0x00000001; DTV_C20L); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, WSTRF4022FTP, wireless)
https://webstar-electro.com/tv/fiche-technique-televiseurs-stream-wstrf4022ftp-algerie-12524-12963698.htm

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; WSTRH3222FTP; 04.50.62; 0x00000001; DTV_C20L); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, WSTRH3222FTP, wireless)
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; WSTRU4322FTP; 04.50.61; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, WSTRU4322FTP, wireless)
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; WSTRU5522FTP; 04.50.61; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, WSTRU5522FTP, wireless)

### VISION TECHNOLOGY
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; VS-55LDB971WO; 04.50.61; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, VS-55LDB971WO, wireless)
https://vision-ma.com/produit/vs-55ldb971/

### WANSA
- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; WLE32KWO62; 04.50.61; 0x00000001; DTV_C20L); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, WLE32KWO62, wireless)
https://www.xcite.com/wansa-32-hd-smart-led-tv-wansa-32-inch-hd-smart-led-tv/p?srsltid=AfmBOoo8RT58c7xc6LSFhkt0sCwTGvL-7gkK7264xHRP8zmhFV7_L6ez

**Comment by sanchezzzhak** [comment]
Ty all
