### ISSUE TITLE
Add detection for `ohdear.app` as a bot

### ISSUE THREAD

**Issue by chescos** [matomo-org/device-detector#7836]
[ohdear.app](https://ohdear.app/docs/faq/what-is-the-oh-dear-crawler-doing-in-my-logs) is a monitoring tool that uses a few different UAs for their services. The UA always contains their domain name. Here are some examples:

```
Oh Dear Sitemap check https://ohdear.app
Mozilla/5.0 (compatible; OhDear/1.1; +https://ohdear.app/checker; brokenLinks)
```

**Comment by Felipe-Rafael-Rosa** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler
