### ISSUE TITLE
AbstractDeviceParser::getDeviceName(): Argument #1 ($deviceType) must be of type int, string given

### ISSUE THREAD

**Issue by ghnp5** [matomo-org/device-detector#7846]
Hello,

Just got this today (never had this problem before, and it's obviously working for 99.99% of the users):

> Uncaught TypeError [0]: DeviceDetector\Parser\Device\AbstractDeviceParser::getDeviceName(): Argument #.1 ($deviceType) must be of type int, string given, called in /.../vendor/matomo/device-detector/Parser/Device/AbstractDeviceParser.php on line 2271
> at /.../vendor/matomo/device-detector/Parser/Device/AbstractDeviceParser.php(2075)
> Stack trace:
> #.0 /.../vendor/matomo/device-detector/Parser/Device/AbstractDeviceParser.php(2271): DeviceDetector\Parser\Device\AbstractDeviceParser::**getDeviceName('desktop')**
> #.1 /.../vendor/matomo/device-detector/Parser/Device/AbstractDeviceParser.php(2152): DeviceDetector\Parser\Device\AbstractDeviceParser->parseClientHints()
> #.2 /.../vendor/matomo/device-detector/DeviceDetector.php(899): DeviceDetector\Parser\Device\AbstractDeviceParser->parse()
> #.3 /.../vendor/matomo/device-detector/DeviceDetector.php(622): DeviceDetector\DeviceDetector->parseDevice()
> #.4 myscript.php(123): DeviceDetector\DeviceDetector->parse()
> #.5 myscript.php(456): getBrowser(**'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36', Array**)

Unfortunately, I can't know what were the Client Hints, because the stack trace just shows "Array" in that last line. But I suspect it was something with that.

It's passing "desktop" in the parameter for `getDeviceName`, instead of passing one of the constants that maps to that key.

Thanks!

**Comment by sanchezzzhak** [comment]
@sgiehl need new version release.
We have fixed some critical errors.

@ghnp5 there is a small bug in the current version/

As a temporary solution before using DeviceDetector set value
```
$_SERVER['HTTP_SEC_CH_UA_FORM_FACTORS'] = '';
```

**Comment by sgiehl** [comment]
Ok. I'll create another release

**Comment by ghnp5** [comment]
Thank you very much!!
