### ISSUE TITLE
Other TV Devices

### ISSUE THREAD

**Issue by EfekanPekel** [matomo-org/device-detector#7885]
- [x] Mozilla/5.0 (Astro;AS620SM;2.2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
Brand: Astro, Model: AS620SM, Device: tv (https://www.manualslib.com/products/Astro-Gx-As620sm-11660261.html)

- [x] Mozilla/5.0 (Astro;AS630SM;2.2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15

- [x] Mozilla/5.0 (Astro;KSTB6112;2.2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15
Brand: Astro, Model: KSTB6112, Device: tv (https://www.manualslib.com/manual/2541673/Astro-Ulti-Box.html)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 OPR/40.0.2207.0 OMI/4.9.0.237.DOM3-OPT.256 Model/Vestel-MB130 VSTVB MB100 HbbTV/1.2.1 (; GN_ELECTRONICS; MB130; 5.35.4.0; _TV_G10_2017;) SmartTvA/3.0.0
Brand: GN Electronics (https://gnelectronics.in/32led)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.179 Model/Vestel-MB181 VSTVB MB100 HbbTV/1.5.1 (+DRM; GRAETZ; MB181; 1.87.7.0; ; _TV_G36_2020;) SmartTvA/3.0.0
Brand: Graetz (https://www.graetzitalia.it/product-category/smart/)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.183 Model/Vestel-MB181 VSTVB MB100 HbbTV/1.5.1 (+DRM; UNITED; MB181; 1.89.9.0; ; _TV_G36_2020;) SmartTvA/3.0.0
Brand: United (https://shop.united-tv.eu/en/16-hd-led-tv)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.192 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; FUJICOM; MB180; 1.73.2.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: Fujicom (https://fujicom.co.il/%D7%A7%D7%98%D7%92%D7%95%D7%A8%D7%99%D7%99%D7%AA-%D7%9E%D7%95%D7%A6%D7%A8/%d7%98%d7%9c%d7%95%d7%95%d7%99%d7%96%d7%99%d7%95%d7%aa-%d7%95%d7%9e%d7%a1%d7%9b%d7%99-%d7%9e%d7%97%d7%a9%d7%91/)

- [x] Mozilla/5.0 (Linux ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/46.0.2207.0 OMI/4.20.5.61.LIMA.192 Model/Vestel-MB180 VSTVB MB100 HbbTV/1.5.1 (+DRM; TUCSON; MB180; 1.73.2.0; ; _TV_G32_2020;) SmartTvA/3.0.0
Brand: Tucson (https://www.backmarket.co.uk/en-gb/p/tucson-315-inch-tl32dled309b16-1920-x-1080-tv/fd69a662-fcd9-4c62-bfc1-76433ae07fe9)

### LG - WebOS Devices

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/79.0.3945.79 Safari/537.36 LG Browser/8.00.00(LGE; 27ART10AKPL; 03.44.00; 0x00000001; DTV_N21D); webOS.TV-2021; LG NetCast.TV-2013 Compatible (LGE, 27ART10AKPL, wireless)
Brand: LG https://www.lg.com/tr/lifestyle-ekranlar/stanbyme/27art10akpl/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/38.0.2125.122 Safari/537.36 LG Browser/8.00.00(LGE; 32LH604V-ZB; 05.70.40; 1; DTV_W16R); webOS.TV-2016; LG NetCast.TV-2013 Compatible (LGE, 32LH604V-ZB, wireless)
Brand: LG https://www.lg.com/tr/tv-soundbar/led-tvs/32lh604v/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/38.0.2125.122 Safari/537.36 LG Browser/8.00.00(LGE; 32LJ550Z-TA; 06.10.35; 1; DTV_W17R); webOS.TV-2017; LG NetCast.TV-2013 Compatible (LGE, 32LJ550Z-TA, wireless)
Brand: LG https://www.lg.com/il/support/product/lg-32LJ550Z.AMFQ

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/53.0.2785.34 Safari/537.36 LG Browser/8.00.00(LGE; 32LK6100PLB; 05.50.40; 1; DTV_W18R); webOS.TV-2018; LG NetCast.TV-2013 Compatible (LGE, 32LK6100PLB, wireless)
Brand: LG https://www.lg.com/uk/tvs-soundbars/smart-tvs/32lk6100plb/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/53.0.2785.34 Safari/537.36 LG Browser/8.00.00(LGE; 32LM6300PLA; 05.40.45; 1; DTV_W19R); webOS.TV-2019; LG NetCast.TV-2013 Compatible (LGE, 32LM6300PLA, wireless)
Brand: LG https://www.lg.com/tr/tv-soundbar/smart-tv/32lm6300pla/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 32LQ63006LA; 04.41.05; 0x00000001; DTV_W22L); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 32LQ63006LA, wireless)
Brand: LG https://www.lg.com/tr/tv-soundbar/smart-tv/32lq63006la/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 27LX5QKNA; 04.41.06; 0x00000001; DTV_N22D); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 27LX5QKNA, wireless)
Brand: LG https://www.lg.com/tr/lifestyle-ekranlar/stanbyme-go/27lx5qkna/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/38.0.2125.122 Safari/537.36 LG Browser/8.00.00(LGE; 28MT49S-PSS; 06.10.35; 1; DTV_W17R); webOS.TV-2017; LG NetCast.TV-2013 Compatible (LGE, 28MT49S-PSS, wireless)
Brand: LG https://www.lg.com/tr/monitor/smart-monitorler/24tl510s-pz/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/108.0.5359.211 Safari/537.36 LG Browser/8.00.00(LGE; 55NANO81T6A.BPISLJP; 23.20.65; 0x00000001; DTV_W24P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 55NANO81T6A.BPISLJP, wireless)
Brand: LG Model: 55NANO81T6A https://www.lg.com/tr/tv-soundbar/nanocell/55nano81t6a/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/108.0.5359.211 Safari/537.36 LG Browser/8.00.00(LGE; 50NANO81T6A; 23.20.65; 0x00000001; DTV_W24P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 50NANO81T6A, wireless)
Brand: LG https://www.lg.com/tr/tv-soundbar/nanocell/50nano81t6a/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/38.0.2125.122 Safari/537.36 LG Browser/8.00.00(LGE; 49SJ800V-TA; 06.10.45; 1; DTV_W17H); webOS.TV-2017; LG NetCast.TV-2013 Compatible (LGE, 49SJ800V-TA, wired)
Brand: LG https://www.lg.com/uk/tvs-soundbars/smart-tvs/49sj800v/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/38.0.2125.122 Safari/537.36 LG Browser/8.00.00(LGE; 49SK7900PLA; 06.10.45; 1; DTV_W17H); webOS.TV-2017; LG NetCast.TV-2013 Compatible (LGE, 49SK7900PLA, wired)
Brand: LG https://www.lg.com/tr/tv-soundbar/led-tvs/49sk7900pla/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/53.0.2785.34 Safari/537.36 LG Browser/8.00.00(LGE; 49SM8000PLA; 05.40.20; 1; DTV_W19P); webOS.TV-2019; LG NetCast.TV-2013 Compatible (LGE, 49SM8000PLA, wireless)
Brand: LG https://www.lg.com/tr/tv-soundbar/smart-tv/49sm8000pla/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/38.0.2125.122 Safari/537.36 LG Browser/8.00.00(LGE; 24TL510S-PZ; 06.10.35; 1; DTV_W17R); webOS.TV-2017; LG NetCast.TV-2013 Compatible (LGE, 24TL510S-PZ, wired)
Brand: LG https://www.lg.com/tr/monitor/smart-monitorler/24tl510s-pz/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/53.0.2785.34 Safari/537.36 LG Browser/8.00.00(LGE; 24TN510S-WZ; 05.40.45; 1; DTV_W19R); webOS.TV-2019; LG NetCast.TV-2013 Compatible (LGE, 24TN510S-WZ, wireless)
Brand: LG https://www.lg.com/tr/monitor/fhd-qhd/24tn510s-pz/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/38.0.2125.122 Safari/537.36 LG Browser/8.00.00(LGE; 43UH603V-ZE; 05.70.35; 1; DTV_W16P); webOS.TV-2016; LG NetCast.TV-2013 Compatible (LGE, 43UH603V-ZE, wireless)
Brand: LG https://www.lg.com/uk/tvs-soundbars/smart-tvs/43uh603v

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/38.0.2125.122 Safari/537.36 LG Browser/8.00.00(LGE; 43UJ630V-ZA; 06.00.15; 1; DTV_W17P); webOS.TV-2017; LG NetCast.TV-2013 Compatible (LGE, 43UJ630V-ZA, wireless)
Brand: LG https://www.lg.com/tr/tv-soundbar/lcd-tvs/43uj630v/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/38.0.2125.122 Safari/537.36 LG Browser/8.00.00(LGE; 65UK6100PLB; 06.10.50; 1; DTV_W17P); webOS.TV-2017; LG NetCast.TV-2013 Compatible (LGE, 65UK6100PLB, wired)
Brand: LG https://www.lg.com/tr/tv-soundbar/led-tvs/65uk6100plb/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/53.0.2785.34 Safari/537.36 LG Browser/8.00.00(LGE; 43UM7100PLB; 05.40.45; 1; DTV_W19P); webOS.TV-2019; LG NetCast.TV-2013 Compatible (LGE, 43UM7100PLB, wired)
Brand: LG https://www.lg.com/tr/tv-soundbar/4k-uhd-tvs/43um7100plb/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; 43UN71006LB; 03.01.05; 0x00000001; DTV_W20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, 43UN71006LB, wireless)
Brand: LG https://www.lg.com/tr/tv-soundbar/4k-uhd-tvs/43un71006lb/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/79.0.3945.79 Safari/537.36 LG Browser/8.00.00(LGE; 43UP75006LF; 03.41.00; 0x00000001; DTV_W21A); webOS.TV-2021; LG NetCast.TV-2013 Compatible (LGE, 43UP75006LF, wireless)
Brand: LG https://www.lg.com/tr/tv-soundbar/4k-uhd-tvs/43up75006lf/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 43UQ75003LF; 04.41.05; 0x00000001; DTV_W22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 43UQ75003LF, wireless)
Brand: LG https://www.lg.com/hu/televiziok/lg-43uq75003lf

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/94.0.4606.128 Safari/537.36 LG Browser/8.00.00(LGE; 43UR78006LK; 03.31.82; 0x00000001; DTV_W23A); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 43UR78006LK, wireless)
Brand: LG https://www.lg.com/uk/tvs-soundbars/smart-tvs/43ur78006lk/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/108.0.5359.211 Safari/537.36 LG Browser/8.00.00(LGE; 43UT81006LA; 23.20.65; 0x00000001; DTV_W24P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 43UT81006LA, wired)
Brand: LG https://www.lg.com/tr/tv-soundbar/4k-uhd-tvs/43ut81006la/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/53.0.2785.34 Safari/537.36 LG Browser/8.00.00(LGE; HF60LS-EU; 03.00.08; 1; DTV_W18Z); webOS.TV-2018; LG NetCast.TV-2013 Compatible (LGE, HF60LS-EU, wireless)
Brand: LG https://www.lg.com/tr/projektorler/lazer-projektor/hf60ls/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/108.0.5359.211 Safari/537.36 LG Browser/8.00.00(LGE; OLED48C34LA; 23.20.50; 0x00000001; DTV_W23O); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, OLED48C34LA, wired)
Brand: LG https://www.lg.com/tr/tv-soundbar/oled-evo/oled48c34la/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/108.0.5359.211 Safari/537.36 LG Browser/8.00.00(LGE; OLED55B42LA.DVSQLJP; 23.20.21; 0x00000001; DTV_W24H); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, OLED55B42LA.DVSQLJP, wireless)
Brand: LG https://www.lg.com/uk/tvs-soundbars/oled/oled55b42la/

### non-LG WebOS Devices

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; WS-508G; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, WS-508G, wireless)
Brand: Aiwa https://aiwa.com.sg/shop/55%E2%80%B3-508g-4k-ultra-hd-webos-smart-tv-frameless-tv/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; ASSTV55WF4K; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, ASSTV55WF4K, wireless)
Brand: Allstar https://www.powertechstore.com/it/tv%2Bled%2B55%2522%2Ball%2Bstar%2B4k%2Basstv55wf4k%2Bsmart%2Btv%2Bwebos%2Bitalia%2Bblack

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; AX50FIL242-0246; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, AX50FIL242-0246, wireless)
Brand: Axen https://www.axen.com.tr/axen-50-126-ekran-frameless-ultra-hd-4k-webos-smart-tv-ax50fil242/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; B213200SW; 04.50.62; 0x00000001; DTV_C20L); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, B213200SW, wireless)
Brand: Awox https://www.epey.com/televizyon/awox-b213200sw.html

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; ATV85UHDW-0122; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, ATV85UHDW-0122, wired)
Brand: Bauhn https://bauhn.com.au/85-4k-ultra-hd-webos-smart-tv/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 55UW5000T; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 55UW5000T, wireless)
Brand: Blaupunkt https://catalog.onliner.by/tv/blaupunkt/55uw5000t

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 58BSE9503; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 58BSE9503, wireless)
Brand: Botech, https://www.epey.com/televizyon/botech-58bse9503.html

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 65DYW60; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 65DYW60, wireless)
Brand: Dora, https://www.jehazcom.com/product/%D8%B4%D8%A7%D8%B4%D8%A9-65-%D8%A8%D9%88%D8%B5%D8%A9-%D8%AF%D9%88%D8%B1%D8%A7-%D8%B3%D9%85%D8%A7%D8%B1%D8%AA-4k-webos/?srsltid=AfmBOopGQ2XltbImKi7Oy_nFjVibbBt_SDqp98pgs3eCMS-wQ_fqpnN2

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; K55USW; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, K55USW, wired)
Brand: Eko https://www.eko-entertainment.com.au/weboshub

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; B50UHD4EKC; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, B50UHD4EKC, wireless)
Brand: Elista, https://www.elistaworld.com/uae/4k-uhd-smart/led-b50uhd4ekc

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; GVC-65WS7100; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, GVC-65WS7100, wireless)
Brand: GVC Pro https://www.noon.com/saudi-en/65-inch-4k-smart-tv-webos-with-free-mount-gvc-65ws7100-black/N70094741V/p/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; WEE5-75EU-FDVB; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, WEE5-75EU-FDVB, wireless)
Brand: Horion https://www.ammancart.com/products/horion-smart-4k-led-tv-75-inch-wee5-75eu?srsltid=AfmBOorOSvOe1ymKDwUI8EhSAB6bYW-vpscVhbsWb5MUtwptLFXMmRh2 

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; 50HYN3205; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, 50HYN3205, wireless)
Brand: Hyundai https://hyundaitr.com/televizyonlar/50hyn3205/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; LT-98N7125; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, LT-98N7125, wireless)
Brand: JVC https://uae.sharafdg.com/product/jvc-lt-98n7125-4k-uhd-smart-led-television-with-lg-webos-and-dolby-sound-black-98inch/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 0V50500; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 0V50500, wireless)
Brand: ONVO https://www.epey.com/televizyon/onvo-ov50500.html

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; OV43400; 04.50.62; 0x00000001; DTV_C20L); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, OV43400, wireless)
Brand: ONVO https://onvo.com.tr/urunler/televizyonlar/onvo-ov43400-43-full-hd-webos-smart-led/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; PQ32DAL540-0276; 04.41.46; 0x00000001; DTV_C22L); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, PQ32DAL540-0276, wireless)
Brand: PEAQ https://www.epey.com/televizyon/peaq-pq32dal540.html

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; RWOSU6547; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, RWOSU6547, wireless)
Brand: RCA https://rca-televisions.com/product/rwosu6547/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 43SFSW4M; 03.34.40; 0x00000001; DTV_C22L); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 43SFSW4M, wireless)
Brand: Simfer https://simfer.com.tr/simfer-43sfsw4m-109-ekran-43-webos-led-full-hd-televizyon

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; 50ST3204; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, 50ST3204, wired)
Brand: Skytech https://skytech.com.tr/en/televizyonlar/50st3204/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; ST65SMWOS4K; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, ST65SMWOS4K, wireless)
Brand: Stilevs, https://stilevskktc.com/index.php?route=product/product&product_id=263

- [ ] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 14AT542; 03.34.35; 0x00000001; DTV_C22L); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 14AT542, wireless)
- [ ] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/94.0.4606.128 Safari/537.36 LG Browser/8.00.00(LGE; 14AT543; 03.11.45; 0x00000001; DTV_C23L); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 14AT543, wireless)
Brand: Sunny https://www.sunny.com.tr/wp-content/uploads/Urun-Bilgi-Formu-43-WEBOS-14AT542-R01.pdf 
As far as I understand, 14AT542 and 14AT543 are actually motherboard info, not model info. They probably forgot to change this for a significant model.

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; SUNNYSN55UAL253-; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, SUNNYSN55UAL253-, wireless)
Brand: Sunny, Model: SN55UAL253 https://www.epey.com/televizyon/sunny-sn55ual253-0276.html

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/68.0.3440.106 Safari/537.36 LG Browser/8.00.00(LGE; VN50WOS2021; 04.50.62; 0x00000001; DTV_C20P); webOS.TV-2020; LG NetCast.TV-2013 Compatible (LGE, VN50WOS2021, wireless)
Brand: VEON https://shop.cashconverters.co.nz/Listing/Details/97399148

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; V65G2; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, V65G2, wireless)
Brand: Viendo https://www.noon.com/saudi-en/65-inch-webos-smart-4k-anti-shatter-screen-v65g2/ZAC24E55392E7E67D2760Z/p/?o=zac24e55392e7e67d2760z-1

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 65WS3205; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 65WS3205, wireless)
Brand: Weston, https://weston.com.tr/televizyonlar/65ws3205/

- [x] Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chr0me/87.0.4280.88 Safari/537.36 LG Browser/8.00.00(LGE; 65W600U; 04.41.33; 0x00000001; DTV_C22P); webOS.TV-2022; LG NetCast.TV-2013 Compatible (LGE, 65W600U, wireless)
Brand: Ziffler, https://alifshop.uz/ru/offer/prochaya-bytovaya-tehnika-s-elektrodvigatelem-ne-perechislennaya-v-drugih-subpoziciyah-ziffler-5

**Comment by EfekanPekel** [comment]
@liviuconcioiu 

https://www.lg.com/us/support/help-library/lg-tv-how-to-find-the-model-number--20153215656505

![image](https://github.com/user-attachments/assets/7b858565-cf75-4cd2-96c0-41c2698d22ef)
![image](https://github.com/user-attachments/assets/f1bfd95d-56a0-4796-91d1-933f24e35910)

This might help you with LG devices.

**Comment by liviuconcioiu** [comment]
I think this issue can be closed. The other two, we can't detect them since is the motherboard model. I did some digging and there are other brands that use it too.
