### ISSUE TITLE
Windows 11 detected as Windows 10 despite browser hints are used

### ISSUE THREAD

**Issue by wilsonchenbhs** [matomo-org/device-detector#7909]
Hi,

Here my user agent on Windows 11 + Edge:

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0

According to Microsoft document: https://learn.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance

> **platformVersion Hint**
> The operating system version token in the User-Agent header hasn't been updated for Windows 11, and still reports Windows NT 10.0.
> 
> To distinguish between Windows 10 and Windows 11, request the platformVersion client hint in Microsoft Edge. Values between and including 1.0.0 and 12.0.0 represent releases of Windows 10, while values of 14.0.0 or later represent releases of Windows 11.

I've used the client hints:
`$clientHints = ClientHints::factory($_SERVER);`

But it's still showing Windows 10.

Any idea?

**Comment by liviuconcioiu** [comment]
You should request client hints from browser if you aren't doing it already. Some browsers, platforms don't send them by default.

```PHP
header('Accept-CH: Sec-CH-UA, Sec-CH-UA-Mobile, Sec-CH-UA-Platform, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Arch, Sec-CH-UA-Model, Sec-CH-UA-Form-Factors, Sec-CH-UA-Bitness, Sec-CH-UA-WoW64');
```

**Comment by liviuconcioiu** [comment]
@sgiehl can you please update the `Usage` description in README when you have free time? This will prevent issues being open in the future.

It should be some sort of example on how to accept the client hints, either PHP or meta tags.

From https://developer.mozilla.org/en-US/docs/Web/HTTP/Client_hints:

_A server must announce that it supports client hints, using the [Accept-CH](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH) header to specify the hints that it is interested in receiving._
